import E213.Theory.Raw.PrimitiveTower

/-!
# Theory.Raw.RawNat — the naturals object generated by the distinguishing's own successor

Leg 1 of the descent-leg programme (`research-notes/frontiers/the_descent_leg.md`): the naturals are
not *borrowed* from Lean's `Nat` but *generated* as a reading of `Raw`.  The carrier is a class of
`Raw` elements; the successor is a `slash`-operation; Peano holds; and Lean's `Nat` is recovered as
the **`depth` Lens reading** — a homomorphism, not the source.

  * carrier  `RawNat` — the `slash`-successor spine `{ r : Raw // ∃ n, rawTower n = r }`.
  * `zero`   — the seed `rawTower 0 = b` (the first distinguishing, no `slash` yet).
  * `succ`   — `slashOrSelf Raw.a` (point at it once more with `a`): the *same* `slash` the tower
    iterates, so a step IS one more distinguishing, not an imported `+1`.
  * Peano: `succ_inj`, `succ_ne_zero`, `rec` (induction) — the natural-number *structure* carried by
    `Raw`'s combinatorics.
  * `toNat`/`ofNat` — the `depth` Lens and its inverse, a Peano isomorphism `RawNat ≃ ℕ`
    (`toNat_zero`, `toNat_succ`, `toNat_ofNat`, `ofNat_toNat`): Lean's `Nat` is the depth-reading of
    this spine.

**Honest accounting** (skeptic's Attack 1, the borrowed/generated boundary): the kernel's `inductive`
`Tree` is borrowed to have `Raw` at all, and Lean's `Nat` is borrowed as the *index/readout type*.
What is *generated* — not borrowed — is the natural-number **structure** (zero, successor, the Peano
laws, induction), carried here by `Raw`'s `slash`-spine, with `Nat` recovered as a Lens reading rather
than assumed.  This does not yet replace the kernel `Nat` used as the readout; it shows the Peano
content is a reading of the distinguishing.

∅-axiom.
-/

namespace E213.Theory.Raw.RawNat

open E213.Theory
open E213.Theory.Raw.Endomorphic (slashOrSelf)
open E213.Theory.Raw.PrimitiveTower (rawTower rawTower_depth)

/-! ## §1 — successor as a `slash`-operation, and the spine's injectivity -/

/-- The successor on `Raw`: point at it once more with `a`.  The *same* arrow `rawTower` iterates
    (`rawTower (n+1) = rawSucc (rawTower n)` by definition). -/
def rawSucc (r : Raw) : Raw := slashOrSelf Raw.a r

theorem rawSucc_tower (n : Nat) : rawSucc (rawTower n) = rawTower (n + 1) := rfl

/-- The spine is depth-injective: distinct indices give distinct rungs (each rung's `depth` is its
    index, `rawTower_depth`). -/
theorem rawTower_inj {m n : Nat} (h : rawTower m = rawTower n) : m = n := by
  calc m = (rawTower m).depth := (rawTower_depth m).symm
    _ = (rawTower n).depth := congrArg Raw.depth h
    _ = n := rawTower_depth n

/-! ## §2 — the carrier and its Peano structure -/

/-- The naturals object: the `slash`-successor spine inside `Raw`. -/
def RawNat : Type := { r : Raw // ∃ n, rawTower n = r }

namespace RawNat

/-- `0` is the seed `b` — the first distinguishing, no `slash` applied. -/
def zero : RawNat := ⟨rawTower 0, ⟨0, rfl⟩⟩

/-- Successor: apply the spine's arrow `rawSucc` once more.  The carrier proof advances the index. -/
def succ (x : RawNat) : RawNat :=
  ⟨rawSucc x.val, by
    obtain ⟨n, hn⟩ := x.2
    exact ⟨n + 1, by rw [← hn]; rfl⟩⟩

/-- The `depth` Lens reading: the rung's depth is its natural-number value. -/
def toNat (x : RawNat) : Nat := x.val.depth

/-- The inverse reading: the `n`-th rung. -/
def ofNat (n : Nat) : RawNat := ⟨rawTower n, ⟨n, rfl⟩⟩

@[simp] theorem toNat_ofNat (n : Nat) : toNat (ofNat n) = n := rawTower_depth n

theorem ofNat_toNat (x : RawNat) : ofNat (toNat x) = x := by
  obtain ⟨n, hn⟩ := x.2
  apply Subtype.ext
  show rawTower x.val.depth = x.val
  rw [← hn, rawTower_depth]

/-- `depth` injects the carrier into `ℕ`. -/
theorem toNat_inj {x y : RawNat} (h : toNat x = toNat y) : x = y := by
  rw [← ofNat_toNat x, ← ofNat_toNat y, h]

theorem toNat_zero : toNat zero = 0 := rfl

/-- The Lens commutes with successor: `depth (succ x) = depth x + 1`.  The structural heart — one
    `slash`-step is exactly one unit of depth. -/
theorem toNat_succ (x : RawNat) : toNat (succ x) = toNat x + 1 := by
  obtain ⟨n, hn⟩ := x.2
  show (rawSucc x.val).depth = x.val.depth + 1
  rw [← hn, rawSucc_tower, rawTower_depth, rawTower_depth]

theorem ofNat_zero : ofNat 0 = zero := rfl

theorem ofNat_succ (n : Nat) : ofNat (n + 1) = succ (ofNat n) := by
  apply Subtype.ext
  show rawTower (n + 1) = rawSucc (rawTower n)
  rw [rawSucc_tower]

/-- **Peano P3 — successor is injective.**  From the depth Lens: `succ` adds one unit of depth, and
    depth injects. -/
theorem succ_inj {x y : RawNat} (h : succ x = succ y) : x = y := by
  apply toNat_inj
  have : toNat (succ x) = toNat (succ y) := congrArg toNat h
  rw [toNat_succ, toNat_succ] at this
  exact Nat.succ.inj this

/-- **Peano P4 — `0` is not a successor.**  `succ x` has positive depth; `zero` has depth `0`. -/
theorem succ_ne_zero (x : RawNat) : succ x ≠ zero := by
  intro h
  have : toNat (succ x) = toNat zero := congrArg toNat h
  rw [toNat_succ, toNat_zero] at this
  exact Nat.noConfusion this

/-- **Peano induction.**  Every element is reached from `zero` by `succ` — the spine has no elements
    off the `rawTower` thread.  Proved by transporting Lean's `Nat.rec` across the `depth` iso. -/
theorem rec {P : RawNat → Prop} (h0 : P zero) (hs : ∀ x, P x → P (succ x)) : ∀ x, P x := by
  intro x
  rw [← ofNat_toNat x]
  induction (toNat x) with
  | zero => rw [ofNat_zero]; exact h0
  | succ n ih => rw [ofNat_succ]; exact hs (ofNat n) ih

end RawNat

/-! ## §3 — arithmetic generated by iterating the `slash`-successor

`+` and `·` are not borrowed from `Nat`: `add x y` applies the spine's successor `rawSucc` to `x`
exactly as many times as `y`'s depth (a Lens reading of `y`), and `mul` iterates `add`.  The `depth`
Lens is then proved to be a **semiring homomorphism** onto Lean's `ℕ` — the generated operations
*read as* `Nat`'s `+`/`·`, so the commutative-semiring discipline transports back through the
injection (`add_comm`, `mul_comm` below) without re-proving it on `Raw`. -/

/-- Iterate the spine successor `k` times. -/
def addRaw (r : Raw) : Nat → Raw
  | 0     => r
  | k + 1 => rawSucc (addRaw r k)

theorem addRaw_tower (n : Nat) : ∀ k, addRaw (rawTower n) k = rawTower (n + k)
  | 0     => rfl
  | k + 1 => by
    show rawSucc (addRaw (rawTower n) k) = rawTower (n + (k + 1))
    rw [addRaw_tower n k]
    exact rawSucc_tower (n + k)

namespace RawNat

/-- Addition: apply the `slash`-successor to `x`, `depth y` times. -/
def add (x y : RawNat) : RawNat :=
  ⟨addRaw x.val (toNat y), by
    obtain ⟨n, hn⟩ := x.2
    exact ⟨n + toNat y, by rw [← hn]; exact (addRaw_tower n (toNat y)).symm⟩⟩

/-- ★ **The `depth` Lens is additive.**  `depth (add x y) = depth x + depth y` — the generated `+`
    reads as `Nat`'s `+`. -/
theorem toNat_add (x y : RawNat) : toNat (add x y) = toNat x + toNat y := by
  obtain ⟨n, hn⟩ := x.2
  show (addRaw x.val (toNat y)).depth = x.val.depth + toNat y
  rw [← hn, addRaw_tower, rawTower_depth, rawTower_depth]

/-- Multiplication: iterate `add x`, `depth y` times, from `zero`. -/
def mul (x : RawNat) : Nat → RawNat
  | 0     => zero
  | k + 1 => add (mul x k) x

/-- ★ **The `depth` Lens is multiplicative.**  `depth (mul x (depth y)) = depth x · depth y`. -/
theorem toNat_mul (x : RawNat) : ∀ k, toNat (mul x k) = toNat x * k
  | 0     => rfl
  | k + 1 => by
    show toNat (add (mul x k) x) = toNat x * (k + 1)
    rw [toNat_add, toNat_mul x k, Nat.mul_succ]

/-! ### The discipline transports through the injection (no re-proof on `Raw`) -/

/-- `+` is commutative — transported from `Nat` through the depth injection. -/
theorem add_comm (x y : RawNat) : add x y = add y x := by
  apply toNat_inj
  rw [toNat_add, toNat_add, Nat.add_comm]

/-- `+` is associative. -/
theorem add_assoc (x y z : RawNat) : add (add x y) z = add x (add y z) := by
  apply toNat_inj
  rw [toNat_add, toNat_add, toNat_add, toNat_add, Nat.add_assoc]

/-- `zero` is a left identity (the seed `b` adds nothing). -/
theorem zero_add (x : RawNat) : add zero x = x := by
  apply toNat_inj
  rw [toNat_add, toNat_zero, Nat.zero_add]

end RawNat

end E213.Theory.Raw.RawNat
