import E213.Theory.Raw.PrimitiveTower
import E213.Theory.Raw.MuNuMirror

/-!
# Theory.Raw.RawNat — the naturals object generated by the distinguishing's own successor

Leg 1 of the descent-leg programme (`research-notes/frontiers/the_descent_leg.md`): the naturals are
not *borrowed* from Lean's `Nat` but *generated* as a reading of `Raw`.  The carrier is a class of
`Raw` elements; the successor is a `slash`-operation; Peano holds; and Lean's `Nat` is recovered as
the **`depth` Lens reading** — a homomorphism, not the source.

  * carrier  `RawNat` — the `slash`-successor spine `{ r : Raw // ∃ n, rawTower n = r }`.
  * `zero`   — the seed `rawTower 0 = b` (the first distinguishing, no `slash` yet).
  * `succ`   — `slashOrSelf Raw.a` (point at it once more with `a`): the *same* `slash` the tower
    iterates, so a step IS one more distinguishing, not an imported `+1`.
  * Peano: `succ_inj`, `succ_ne_zero`, `rec` (induction) — the natural-number *structure* carried by
    `Raw`'s combinatorics.
  * `toNat`/`ofNat` — the `depth` Lens and its inverse, a Peano isomorphism `RawNat ≃ ℕ`
    (`toNat_zero`, `toNat_succ`, `toNat_ofNat`, `ofNat_toNat`): Lean's `Nat` is the depth-reading of
    this spine.

**Honest accounting** (skeptic's Attack 1, the borrowed/generated boundary): the kernel's `inductive`
`Tree` is borrowed to have `Raw` at all, and Lean's `Nat` is borrowed as the *index/readout type*.
What is *generated* — not borrowed — is the natural-number **structure** (zero, successor, the Peano
laws, induction), carried here by `Raw`'s `slash`-spine, with `Nat` recovered as a Lens reading rather
than assumed.  This does not yet replace the kernel `Nat` used as the readout; it shows the Peano
content is a reading of the distinguishing.

∅-axiom.
-/

namespace E213.Theory.Raw.RawNat

open E213.Theory
open E213.Theory.Raw.Endomorphic (slashOrSelf)
open E213.Theory.Raw.PrimitiveTower (rawTower rawTower_depth)
open E213.Theory.Raw.Lambek (IsPart isPart_wf)
open E213.Theory.Raw.MuNuMirror (tower_ascent_isPart)

/-! ## §1 — successor as a `slash`-operation, and the spine's injectivity -/

/-- The successor on `Raw`: point at it once more with `a`.  The *same* arrow `rawTower` iterates
    (`rawTower (n+1) = rawSucc (rawTower n)` by definition). -/
def rawSucc (r : Raw) : Raw := slashOrSelf Raw.a r

theorem rawSucc_tower (n : Nat) : rawSucc (rawTower n) = rawTower (n + 1) := rfl

/-- The spine is depth-injective: distinct indices give distinct rungs (each rung's `depth` is its
    index, `rawTower_depth`). -/
theorem rawTower_inj {m n : Nat} (h : rawTower m = rawTower n) : m = n := by
  calc m = (rawTower m).depth := (rawTower_depth m).symm
    _ = (rawTower n).depth := congrArg Raw.depth h
    _ = n := rawTower_depth n

/-! ## §2 — the carrier and its Peano structure -/

/-- The naturals object: the `slash`-successor spine inside `Raw`. -/
def RawNat : Type := { r : Raw // ∃ n, rawTower n = r }

namespace RawNat

/-- `0` is the seed `b` — the first distinguishing, no `slash` applied. -/
def zero : RawNat := ⟨rawTower 0, ⟨0, rfl⟩⟩

/-- Successor: apply the spine's arrow `rawSucc` once more.  The carrier proof advances the index. -/
def succ (x : RawNat) : RawNat :=
  ⟨rawSucc x.val, by
    obtain ⟨n, hn⟩ := x.2
    exact ⟨n + 1, by rw [← hn]; rfl⟩⟩

/-- The `depth` Lens reading: the rung's depth is its natural-number value. -/
def toNat (x : RawNat) : Nat := x.val.depth

/-- The inverse reading: the `n`-th rung. -/
def ofNat (n : Nat) : RawNat := ⟨rawTower n, ⟨n, rfl⟩⟩

@[simp] theorem toNat_ofNat (n : Nat) : toNat (ofNat n) = n := rawTower_depth n

theorem ofNat_toNat (x : RawNat) : ofNat (toNat x) = x := by
  obtain ⟨n, hn⟩ := x.2
  apply Subtype.ext
  show rawTower x.val.depth = x.val
  rw [← hn, rawTower_depth]

/-- `depth` injects the carrier into `ℕ`. -/
theorem toNat_inj {x y : RawNat} (h : toNat x = toNat y) : x = y := by
  rw [← ofNat_toNat x, ← ofNat_toNat y, h]

theorem toNat_zero : toNat zero = 0 := rfl

/-- The Lens commutes with successor: `depth (succ x) = depth x + 1`.  The structural heart — one
    `slash`-step is exactly one unit of depth. -/
theorem toNat_succ (x : RawNat) : toNat (succ x) = toNat x + 1 := by
  obtain ⟨n, hn⟩ := x.2
  show (rawSucc x.val).depth = x.val.depth + 1
  rw [← hn, rawSucc_tower, rawTower_depth, rawTower_depth]

theorem ofNat_zero : ofNat 0 = zero := rfl

theorem ofNat_succ (n : Nat) : ofNat (n + 1) = succ (ofNat n) := by
  apply Subtype.ext
  show rawTower (n + 1) = rawSucc (rawTower n)
  rw [rawSucc_tower]

/-- **Peano P3 — successor is injective.**  From the depth Lens: `succ` adds one unit of depth, and
    depth injects. -/
theorem succ_inj {x y : RawNat} (h : succ x = succ y) : x = y := by
  apply toNat_inj
  have : toNat (succ x) = toNat (succ y) := congrArg toNat h
  rw [toNat_succ, toNat_succ] at this
  exact Nat.succ.inj this

/-- **Peano P4 — `0` is not a successor.**  `succ x` has positive depth; `zero` has depth `0`. -/
theorem succ_ne_zero (x : RawNat) : succ x ≠ zero := by
  intro h
  have : toNat (succ x) = toNat zero := congrArg toNat h
  rw [toNat_succ, toNat_zero] at this
  exact Nat.noConfusion this

/-- **Peano induction.**  Every element is reached from `zero` by `succ` — the spine has no elements
    off the `rawTower` thread.  Proved by transporting Lean's `Nat.rec` across the `depth` iso. -/
theorem rec {P : RawNat → Prop} (h0 : P zero) (hs : ∀ x, P x → P (succ x)) : ∀ x, P x := by
  intro x
  rw [← ofNat_toNat x]
  induction (toNat x) with
  | zero => rw [ofNat_zero]; exact h0
  | succ n ih => rw [ofNat_succ]; exact hs (ofNat n) ih

end RawNat

/-! ## §3 — arithmetic generated by iterating the `slash`-successor

`+` and `·` are not borrowed from `Nat`: `add x y` applies the spine's successor `rawSucc` to `x`
exactly as many times as `y`'s depth (a Lens reading of `y`), and `mul` iterates `add`.  The `depth`
Lens is then proved to be a **semiring homomorphism** onto Lean's `ℕ` — the generated operations
*read as* `Nat`'s `+`/`·`, so the commutative-semiring discipline transports back through the
injection (`add_comm`, `mul_comm` below) without re-proving it on `Raw`. -/

/-- Iterate the spine successor `k` times. -/
def addRaw (r : Raw) : Nat → Raw
  | 0     => r
  | k + 1 => rawSucc (addRaw r k)

theorem addRaw_tower (n : Nat) : ∀ k, addRaw (rawTower n) k = rawTower (n + k)
  | 0     => rfl
  | k + 1 => by
    show rawSucc (addRaw (rawTower n) k) = rawTower (n + (k + 1))
    rw [addRaw_tower n k]
    exact rawSucc_tower (n + k)

namespace RawNat

/-- Addition: apply the `slash`-successor to `x`, `depth y` times. -/
def add (x y : RawNat) : RawNat :=
  ⟨addRaw x.val (toNat y), by
    obtain ⟨n, hn⟩ := x.2
    exact ⟨n + toNat y, by rw [← hn]; exact (addRaw_tower n (toNat y)).symm⟩⟩

/-- ★ **The `depth` Lens is additive.**  `depth (add x y) = depth x + depth y` — the generated `+`
    reads as `Nat`'s `+`. -/
theorem toNat_add (x y : RawNat) : toNat (add x y) = toNat x + toNat y := by
  obtain ⟨n, hn⟩ := x.2
  show (addRaw x.val (toNat y)).depth = x.val.depth + toNat y
  rw [← hn, addRaw_tower, rawTower_depth, rawTower_depth]

/-- `1` is the first `slash`-rung, `succ zero = a/b`. -/
def one : RawNat := ofNat 1

@[simp] theorem toNat_one : toNat one = 1 := toNat_ofNat 1

/-- Multiplication iterator: add `x` to itself `k` times. -/
def mulNat (x : RawNat) : Nat → RawNat
  | 0     => zero
  | k + 1 => add (mulNat x k) x

theorem toNat_mulNat (x : RawNat) : ∀ k, toNat (mulNat x k) = toNat x * k
  | 0     => rfl
  | k + 1 => by
    show toNat (add (mulNat x k) x) = toNat x * (k + 1)
    rw [toNat_add, toNat_mulNat x k, Nat.mul_succ]

/-- Multiplication: iterate `add x`, `depth y` times — `·` generated from `+`, itself from `slash`. -/
def mul (x y : RawNat) : RawNat := mulNat x (toNat y)

/-- ★ **The `depth` Lens is multiplicative.**  `depth (mul x y) = depth x · depth y` — the generated
    `·` reads as `Nat`'s `·`. -/
theorem toNat_mul (x y : RawNat) : toNat (mul x y) = toNat x * toNat y :=
  toNat_mulNat x (toNat y)

/-! ### `RawNat` is a commutative semiring — the arithmetic discipline realised on `Raw`

Every law transports through the depth injection (`toNat_inj`) from `ℕ`'s, so the discipline is
*read off* `Raw`'s `slash`-spine, not re-proved on it.  The `depth` homomorphism (`toNat_add`,
`toNat_mul`) is the load-bearing content; the laws follow. -/

theorem add_comm (x y : RawNat) : add x y = add y x := by
  apply toNat_inj; rw [toNat_add, toNat_add, Nat.add_comm]

theorem add_assoc (x y z : RawNat) : add (add x y) z = add x (add y z) := by
  apply toNat_inj; rw [toNat_add, toNat_add, toNat_add, toNat_add, Nat.add_assoc]

theorem zero_add (x : RawNat) : add zero x = x := by
  apply toNat_inj; rw [toNat_add, toNat_zero, Nat.zero_add]

theorem add_zero (x : RawNat) : add x zero = x := by
  apply toNat_inj; rw [toNat_add, toNat_zero, Nat.add_zero]

theorem mul_comm (x y : RawNat) : mul x y = mul y x := by
  apply toNat_inj; rw [toNat_mul, toNat_mul, Nat.mul_comm]

theorem mul_assoc (x y z : RawNat) : mul (mul x y) z = mul x (mul y z) := by
  apply toNat_inj
  rw [toNat_mul, toNat_mul, toNat_mul, toNat_mul]
  exact E213.Tactic.NatHelper.mul_assoc _ _ _

theorem one_mul (x : RawNat) : mul one x = x := by
  apply toNat_inj; rw [toNat_mul, toNat_one, Nat.one_mul]

theorem mul_one (x : RawNat) : mul x one = x := by
  apply toNat_inj; rw [toNat_mul, toNat_one, Nat.mul_one]

theorem zero_mul (x : RawNat) : mul zero x = zero := by
  apply toNat_inj; rw [toNat_mul, toNat_zero, Nat.zero_mul]

theorem mul_zero (x : RawNat) : mul x zero = zero := by
  apply toNat_inj; rw [toNat_mul, toNat_zero, Nat.mul_zero]

/-- Left distributivity `x·(y+z) = x·y + x·z` (`Nat.mul_add` is propext-clean). -/
theorem left_distrib (x y z : RawNat) : mul x (add y z) = add (mul x y) (mul x z) := by
  apply toNat_inj
  rw [toNat_mul, toNat_add, toNat_add, toNat_mul, toNat_mul, Nat.mul_add]

/-- Right distributivity `(x+y)·z = x·z + y·z` (`NatHelper.add_mul`; core `Nat.add_mul` leaks
    propext). -/
theorem right_distrib (x y z : RawNat) : mul (add x y) z = add (mul x z) (mul y z) := by
  apply toNat_inj
  rw [toNat_mul, toNat_add, toNat_add, toNat_mul, toNat_mul]
  exact E213.Tactic.NatHelper.add_mul _ _ _

/-! ### §4 — the recursion engine grounded in `Raw`'s own descent (`isPart_wf`)

The induction principle `rec` above transports `Nat.rec`.  Here it is grounded *intrinsically*: a
`RawNat` recurses on the `slash`-peel relation `IsPart` of `Raw`, which is well-founded by a Theory-ring
theorem (`isPart_wf`, `0` `Nat` constants in its cone), **not** by `Nat`'s order.  So the
natural-number recursion descends on the distinguishing's own peel, and `rec_grounded` re-derives the
Peano induction with the descent supplied by `tower_ascent_isPart` (each rung is a part of the next),
no `Nat` well-foundedness. -/

/-- **Strong induction grounded in `isPart_wf`.**  To prove `P` for all of `RawNat`, prove it for `x`
    given it holds for every `RawNat` whose carrier is an `IsPart`-peel of `x`'s.  The descent is
    `Raw`'s proven well-founded peel, not `Nat.lt`. -/
theorem strongRec_isPart {P : RawNat → Prop}
    (ih : ∀ x : RawNat, (∀ y : RawNat, IsPart y.val x.val → P y) → P x) : ∀ x, P x := by
  have key : ∀ r : Raw, ∀ hr : ∃ n, rawTower n = r, P ⟨r, hr⟩ := fun r =>
    isPart_wf.induction (C := fun r => ∀ hr : ∃ n, rawTower n = r, P ⟨r, hr⟩) r
      (fun x IH hr => ih ⟨x, hr⟩ (fun y hy => IH y.val hy y.2))
  exact fun x => key x.val x.2

/-- Carrier case analysis: every `RawNat` is `zero` or `succ` of an `IsPart`-smaller predecessor.  The
    predecessor's descent is `tower_ascent_isPart` — the peel that `isPart_wf` discharges. -/
theorem zero_or_succ (x : RawNat) :
    x = zero ∨ ∃ w : RawNat, x = succ w ∧ IsPart w.val x.val := by
  obtain ⟨n, hn⟩ := x.2
  cases n with
  | zero => exact Or.inl (Subtype.ext hn.symm)
  | succ m =>
    refine Or.inr ⟨⟨rawTower m, ⟨m, rfl⟩⟩, ?_, ?_⟩
    · apply Subtype.ext
      show x.val = rawSucc (rawTower m)
      rw [rawSucc_tower]; exact hn.symm
    · show IsPart (rawTower m) x.val
      rw [← hn]; exact tower_ascent_isPart m

/-- ★ **Peano induction, descent grounded in `isPart_wf`.**  Same conclusion as `rec`, but the
    recursion runs on `Raw`'s `slash`-peel (`strongRec_isPart` + `zero_or_succ`/`tower_ascent_isPart`),
    not on `Nat.rec` — the natural-number recursion engine *is* the distinguishing's descent. -/
theorem rec_grounded {P : RawNat → Prop} (h0 : P zero) (hs : ∀ x, P x → P (succ x)) : ∀ x, P x := by
  apply strongRec_isPart
  intro x IH
  rcases zero_or_succ x with hz | ⟨w, hw, hpart⟩
  · rw [hz]; exact h0
  · rw [hw]; exact hs w (IH w hpart)

end RawNat

/-! ## §5 — the carrier defined *without* `Nat`: the `slash`-successor closure

§4 grounded the recursion *descent* in `isPart_wf`, but the carrier `{ r // ∃ n, rawTower n = r }`
still mentions `Nat` (the index `n`).  Here the carrier is given with **no `Nat` at all**: `IsRawNat`
is the inductive closure of the seed `b` under the `slash`-successor `rawSucc`.  Its own recursor
`IsRawNat.rec` *is* natural-number induction — structural, no `Nat`, no well-foundedness machinery —
and it coincides exactly with the tower carrier (`isRawNat_iff`). -/

/-- `IsRawNat r` — `r` is reachable from the first distinguishing `b` by the `slash`-successor
    `rawSucc` ("point once more with `a`").  The naturals as a purely `Raw` inductive closure; no
    `Nat` in sight. -/
inductive IsRawNat : Raw → Prop where
  | base : IsRawNat Raw.b
  | step {r : Raw} : IsRawNat r → IsRawNat (rawSucc r)

/-- ★ **Nat-free induction.**  Proving `P` over the whole successor-closure needs only the seed `b`
    and the `rawSucc`-step: `IsRawNat.rec`, with **no `Nat`** and no well-foundedness — the inductive's
    own recursor is the natural-number recursion. -/
theorem rawNat_induction {P : Raw → Prop} (hb : P Raw.b)
    (hs : ∀ r, IsRawNat r → P r → P (rawSucc r)) {r : Raw} (h : IsRawNat r) : P r := by
  induction h with
  | base => exact hb
  | step hr ih => exact hs _ hr ih

/-- The seed is `rawTower 0` and `rawSucc` is the tower step, so the `Nat`-free closure is exactly the
    tower image. -/
theorem isRawNat_of_tower : ∀ n, IsRawNat (rawTower n)
  | 0     => IsRawNat.base
  | n + 1 => (isRawNat_of_tower n).step

theorem tower_of_isRawNat {r : Raw} (h : IsRawNat r) : ∃ n, rawTower n = r := by
  induction h with
  | base => exact ⟨0, rfl⟩
  | step _ ih => obtain ⟨n, hn⟩ := ih; exact ⟨n + 1, by rw [← hn]; rfl⟩

/-- ★ **The two carriers coincide.**  The `Nat`-free `IsRawNat` and the tower-index `∃ n` define the
    same subset of `Raw` — so `RawNat` could be carried by `IsRawNat` with no `Nat` in its definition,
    the `∃ n` form being just its tower reading. -/
theorem isRawNat_iff (r : Raw) : IsRawNat r ↔ ∃ n, rawTower n = r :=
  ⟨tower_of_isRawNat, fun ⟨n, hn⟩ => hn ▸ isRawNat_of_tower n⟩

end E213.Theory.Raw.RawNat
