import E213.Lib.Math.Cohomology.Bipartite.V33EnrichedParametric
import E213.Lib.Math.Cohomology.Infrastructure.BoolXORFold
import E213.Meta.Nat.Beq213

/-!
# Parametric dual-span at K_{3,3}^{(c)} — Direction C scaffolding

★★★★★★★★★★★★★★★ **Dual-span scaffolding for the upper-bound
side of the c-counter at K_{3,3}^{(c)}.**
★★★★★★★★★★★★★★★

Companion to `V33EnrichedParametric` (which establishes the lower
bound `codim ≥ c` via c independent ψ-discriminators).  This file
builds the SPAN structure needed for the matching upper bound
`codim ≤ c`:

  · `psi_layer_linear` — ψ_m is F₂-linear over pointwise XOR
  · `weighted_e_sum b` — the F₂-linear combination
    `Σ_m (b m) · e_face_layer m`, a c-dim subspace of EnrichedFaceVal
  · `psi_layer_weighted_e_sum` — ψ_{m'}(weighted_e_sum b) = b m'
    (ψ-vector hits any target ⟹ Ψ : EnrichedFaceVal → (Fin c → Bool)
    is surjective)
  · `psi_projection v` / `psi_residual v` — canonical decomposition
    of v as `psi_projection v ⊕ psi_residual v`, with the projection
    in `weighted_e_sum`-form and the residual in the joint
    ψ-kernel.
  · `InPrimaryCupSpanPlusBoundary` — F₂-linear span of PRIMARY
    cup-products `cupOpp_param (starS i m) β` (left factor an
    S-star) and `cupOpp_param α (incidT j m)` (right factor a
    T-incidence), and coboundaries `delta1_enr_param σ`.  This
    matches the subspace on which ψ-functionals (as proven in
    `V33EnrichedParametric`) vanish.  The FULL cup-image span
    is NOT in ψ-kernel — see `psi_layer_arbitrary_cup_not_kill`
    (single-edge cup pairs along face diagonals reproduce every
    face indicator, so the full cup-image span = entire
    `EnrichedFaceVal c`).
  · `primary_cup_span_soundness_conditional` — given Direction B's
    arbitrary-m kill hypotheses, every element of
    `InPrimaryCupSpanPlusBoundary` lies in the joint ψ-kernel
    (well-definedness of the conditional structure).
  · `primary_cup_span_soundness_all_c` — UNCONDITIONAL all-c
    soundness `InPrimary ⊆ joint ψ-kernel`, obtained by chaining
    `primary_cup_span_soundness_on_layer` with Direction B's
    closed `parametric_arbitrary_m_full_kill_capstone` from
    `V33EnrichedParametric`.  Generalises
    `primary_cup_span_soundness_c1` (single-layer) to every
    multiplicity.
  · `codim_upper_bound_conditional` — IF the joint ψ-kernel is
    contained in `InPrimaryCupSpanPlusBoundary`, THEN every v
    decomposes canonically modulo `InPrimaryCupSpanPlusBoundary`
    into its `weighted_e_sum` representative.  Equivalently, the
    c ψ-discriminators SPAN the dual of
    `EnrichedFaceVal c / InPrimaryCupSpanPlusBoundary`.

The unconditional `codim ≤ c` against the PRIMARY cup-image
reduces to ONE remaining open piece:
  · **Per-layer completeness (HARD direction)** — the per-layer
    K_{3,3} fact that 9-element face space modulo (im δ¹ +
    primary cup-image) has dim 1, generated by `e_face_layer m`.
    Layer-disjointness lifts this to ∀c.

Direction B (arbitrary-m kill) is now closed via
`parametric_arbitrary_m_full_kill_capstone`; the EASY direction
(`primary_cup_span_soundness_all_c`) is now unconditional at
every c.  See `theory/RESEARCH_PLAN.md` §1.1.

STRICT ∅-AXIOM.
-/

namespace E213.Lib.Math.Cohomology.Bipartite.V33EnrichedParametricDualSpan

open E213.Lib.Math.Cohomology.Bipartite.V33EnrichedParametric
open E213.Lib.Math.Cohomology.Infrastructure.BoolXORFold
open E213.Meta.Nat.Beq213

/-! ## §1 — ψ_m is F₂-linear over pointwise XOR

Lifts `psi_layer c m` through the `psiNatPos`-based abstract XOR
fold (see `Infrastructure.BoolXORFold`) so that pointwise XOR
distributes through the ψ-sum.  `psi_layer_flat` is a `Nat → Bool`
view of the 9 face values at layer m. -/

def psi_layer_flat (c : Nat) (m : Fin c) (v : EnrichedFaceVal c) : Nat → Bool
  | 0 => v ⟨0, by decide⟩ ⟨0, by decide⟩ m
  | 1 => v ⟨0, by decide⟩ ⟨1, by decide⟩ m
  | 2 => v ⟨0, by decide⟩ ⟨2, by decide⟩ m
  | 3 => v ⟨1, by decide⟩ ⟨0, by decide⟩ m
  | 4 => v ⟨1, by decide⟩ ⟨1, by decide⟩ m
  | 5 => v ⟨1, by decide⟩ ⟨2, by decide⟩ m
  | 6 => v ⟨2, by decide⟩ ⟨0, by decide⟩ m
  | 7 => v ⟨2, by decide⟩ ⟨1, by decide⟩ m
  | 8 => v ⟨2, by decide⟩ ⟨2, by decide⟩ m
  | _+9 => false

theorem psi_layer_eq_psiNatPos (c : Nat) (m : Fin c) (v : EnrichedFaceVal c) :
    psi_layer c m v = psiNatPos 8 (psi_layer_flat c m v) := rfl

theorem psi_layer_flat_xor (c : Nat) (m : Fin c) (v w : EnrichedFaceVal c) (i : Nat) :
    psi_layer_flat c m (fun s t m' => xor (v s t m') (w s t m')) i
      = xor (psi_layer_flat c m v i) (psi_layer_flat c m w i) := by
  match i with
  | 0 => rfl
  | 1 => rfl
  | 2 => rfl
  | 3 => rfl
  | 4 => rfl
  | 5 => rfl
  | 6 => rfl
  | 7 => rfl
  | 8 => rfl
  | _+9 => rfl

theorem psi_layer_linear (c : Nat) (m : Fin c) (v w : EnrichedFaceVal c) :
    psi_layer c m (fun s t m' => xor (v s t m') (w s t m'))
      = xor (psi_layer c m v) (psi_layer c m w) := by
  rw [psi_layer_eq_psiNatPos, psi_layer_eq_psiNatPos, psi_layer_eq_psiNatPos]
  rw [psiNatPos_congr_all 8
       (psi_layer_flat c m (fun s t m' => xor (v s t m') (w s t m')))
       (fun i => xor (psi_layer_flat c m v i) (psi_layer_flat c m w i))
       (psi_layer_flat_xor c m v w)]
  exact psiNatPos_linear 8 (psi_layer_flat c m v) (psi_layer_flat c m w)

/-! ## §2 — `weighted_e_sum`: F₂-combination of `e_face_layer` indicators

`weighted_e_sum c b` is supported only at `(s, t, m') = (0, 0, m')`,
where it carries the value `b m'`.  Equivalently the F₂-linear
combination `⊕_{m ∈ Fin c} (b m) · e_face_layer c m`.

The ψ-vector image `(ψ_0(v), …, ψ_{c-1}(v))` is FULLY HIT by
`weighted_e_sum`: for any target b, `weighted_e_sum c b` realises
it.  Hence the map Ψ : EnrichedFaceVal c → (Fin c → Bool),
v ↦ (m ↦ ψ_m(v)), is SURJECTIVE. -/

def weighted_e_sum (c : Nat) (b : Fin c → Bool) : EnrichedFaceVal c :=
  fun s t m' => (decide (s.val = 0) && decide (t.val = 0)) && b m'

theorem psi_layer_weighted_e_sum (c : Nat) (b : Fin c → Bool) (m' : Fin c) :
    psi_layer c m' (weighted_e_sum c b) = b m' := by
  unfold psi_layer weighted_e_sum
  cases b m' <;> rfl

/-- Surjectivity of the joint ψ-vector map.  For any target
    `b : Fin c → Bool`, the cochain `weighted_e_sum c b` has
    `(ψ_0, …, ψ_{c-1}) = b` exactly. -/
theorem psi_vector_surjective (c : Nat) (b : Fin c → Bool) :
    ∃ v : EnrichedFaceVal c, ∀ m' : Fin c, psi_layer c m' v = b m' :=
  ⟨weighted_e_sum c b, psi_layer_weighted_e_sum c b⟩

/-! ## §3 — Canonical ψ-decomposition

For every v : EnrichedFaceVal c, define
`psi_projection v := weighted_e_sum c (m ↦ ψ_m v)` and
`psi_residual v := v ⊕ psi_projection v`.  Then:

  · `v = psi_projection v ⊕ psi_residual v` (pointwise XOR)
  · `ψ_m(psi_residual v) = false` for all m

So every v decomposes canonically into a c-dim `weighted_e_sum`
representative (carrying the full ψ-vector data) and a residual
in the joint ψ-kernel. -/

def psi_projection (c : Nat) (v : EnrichedFaceVal c) : EnrichedFaceVal c :=
  weighted_e_sum c (fun m => psi_layer c m v)

def psi_residual (c : Nat) (v : EnrichedFaceVal c) : EnrichedFaceVal c :=
  fun s t m' => xor (v s t m') (psi_projection c v s t m')

theorem psi_residual_kills_all_psi (c : Nat) (v : EnrichedFaceVal c) (m' : Fin c) :
    psi_layer c m' (psi_residual c v) = false := by
  show psi_layer c m'
      (fun s t m' => xor (v s t m') (psi_projection c v s t m')) = false
  rw [psi_layer_linear c m' v (psi_projection c v)]
  show xor (psi_layer c m' v)
        (psi_layer c m' (weighted_e_sum c (fun m => psi_layer c m v))) = false
  rw [psi_layer_weighted_e_sum c (fun m => psi_layer c m v) m']
  cases psi_layer c m' v <;> rfl

theorem psi_canonical_decomposition (c : Nat) (v : EnrichedFaceVal c)
    (s t : Fin 3) (m' : Fin c) :
    v s t m' = xor (psi_projection c v s t m') (psi_residual c v s t m') := by
  show v s t m'
      = xor (psi_projection c v s t m')
            (xor (v s t m') (psi_projection c v s t m'))
  cases psi_projection c v s t m' <;> cases v s t m' <;> rfl

/-! ## §4 — `InPrimaryCupSpanPlusBoundary`: F₂-span of PRIMARY cup-products + δ¹-image

Inductively defined: closed under coboundaries `delta1_enr_param σ`,
**primary** cup-products `cupOpp_param (starS i m) β` (left factor
is an S-star) and `cupOpp_param α (incidT j m)` (right factor is a
T-incidence), and pointwise XOR.  This matches exactly the subspace
of `EnrichedFaceVal c` on which the bottom-layer ψ_0 functional
vanishes (see `psi_layer_kills_cupOpp_S{0,1,2}star_left_at_bottom`,
`psi_layer_kills_cupOpp_T{0,1,2}incid_right_at_bottom`, and
`psi_layer_kills_delta1`).

NOTE: The corresponding **full** cup-image span (`cupOpp_param α β`
for arbitrary edge cochains α, β) is NOT in ψ-kernel — indeed the
full cup-image span equals all of `EnrichedFaceVal c` since every
face indicator is a single cup `cupOpp_param e_a e_b` for a
diagonal edge pair (a, b).  Concrete witness:
`psi_layer_arbitrary_cup_not_kill`. -/

inductive InPrimaryCupSpanPlusBoundary (c : Nat) : EnrichedFaceVal c → Prop where
  | zero : InPrimaryCupSpanPlusBoundary c (fun _ _ _ => false)
  | coboundary (σ : EnrichedEdgeCoch c) :
      InPrimaryCupSpanPlusBoundary c (delta1_enr_param c σ)
  | starCup (i : Fin 3) (m : Fin c) (β : EnrichedEdgeCoch c) :
      InPrimaryCupSpanPlusBoundary c (cupOpp_param c (starS c i m) β)
  | incidCup (j : Fin 3) (m : Fin c) (α : EnrichedEdgeCoch c) :
      InPrimaryCupSpanPlusBoundary c (cupOpp_param c α (incidT c j m))
  | xor_add (v w : EnrichedFaceVal c) :
      InPrimaryCupSpanPlusBoundary c v → InPrimaryCupSpanPlusBoundary c w →
      InPrimaryCupSpanPlusBoundary c (fun s t m => xor (v s t m) (w s t m))
  /-- Closure under pointwise equality.  Used in the HARD direction
      (`joint ψ-kernel ⊆ InPrimary`) where we build a candidate
      `xor_add`-chain that is pointwise — but not as a function-literal —
      equal to the target.  Without `funext` (which uses `Quot.sound`,
      forbidden by the ∅-axiom standard) we need this bridge.  See
      `V33EnrichedParametricDualSpanHard` for the consumer site. -/
  | cong (v w : EnrichedFaceVal c) (h : ∀ s t m, v s t m = w s t m) :
      InPrimaryCupSpanPlusBoundary c w → InPrimaryCupSpanPlusBoundary c v

/-! ## §4.5 — Why PRIMARY (not full) cup-image: counter-example

Concrete witness that ψ_0 does NOT kill arbitrary cup-products.
The single-edge cochains at edges 0 and 4 form a diagonal of face
(0, 0, 0) (S-pair {0, 1}, T-pair {0, 1}); their cup is the
single-face indicator at (0, 0, 0), which ψ_0 detects as
true (XOR of one nonzero face).

Consequence: the FULL cup-image span (closing `cupOpp_param α β`
over arbitrary edge cochains α, β under F₂-XOR) is NOT contained
in the joint ψ-kernel.  Indeed, single-edge cup pairs along face
diagonals reproduce every face indicator, so the full cup-image
span equals all of `EnrichedFaceVal c`.  This is the structural
reason the codim claim must be against the PRIMARY cup-image (one
factor a star or incidence), NOT the full one. -/

theorem psi_layer_arbitrary_cup_not_kill :
    psi_layer 1 ⟨0, by decide⟩
      (cupOpp_param 1 (fun e => decide (e.val = 0))
                      (fun e => decide (e.val = 4))) = true := by
  unfold psi_layer cupOpp_param diag_pair_param pair_lo pair_hi edge_idx
  decide

/-! ## §4.6 — Conditional soundness of `InPrimaryCupSpanPlusBoundary`

`InPrimaryCupSpanPlusBoundary` is the F₂-span of (δ¹σ), arbitrary-m
primary cups (starS i m ∪ β) and (α ∪ incidT j m).  For it to be
contained in the joint ψ-kernel, we need:

  · `ψ_{m'} kills cupOpp_param (starS c i m) β` for ALL m, m'
    (when m = m', this is `psi_layer_kills_cupOpp_S{i}star_left_at_bottom`
    at m = 0 only — Direction B in HANDOFF; when m ≠ m', the cup
    has no support at layer m', so ψ_{m'} = 0 trivially)
  · symmetric statement for `incidT j m`

Both reduce to Direction B's open piece (arbitrary-m kill via
Nat.beq cancellation).  Given those hypotheses the soundness
follows by induction + ψ-linearity (`psi_layer_linear`). -/

/-- `psi_layer` only reads the 9 values `v ⟨s,_⟩ ⟨t,_⟩ m`, so pointwise
    equality of two face cochains implies equal ψ-evaluations. -/
theorem psi_layer_pw_congr (c : Nat) (m : Fin c) (v w : EnrichedFaceVal c)
    (h : ∀ s t m', v s t m' = w s t m') :
    psi_layer c m v = psi_layer c m w := by
  unfold psi_layer
  rw [h ⟨0, by decide⟩ ⟨0, by decide⟩ m, h ⟨0, by decide⟩ ⟨1, by decide⟩ m,
      h ⟨0, by decide⟩ ⟨2, by decide⟩ m, h ⟨1, by decide⟩ ⟨0, by decide⟩ m,
      h ⟨1, by decide⟩ ⟨1, by decide⟩ m, h ⟨1, by decide⟩ ⟨2, by decide⟩ m,
      h ⟨2, by decide⟩ ⟨0, by decide⟩ m, h ⟨2, by decide⟩ ⟨1, by decide⟩ m,
      h ⟨2, by decide⟩ ⟨2, by decide⟩ m]

theorem primary_cup_span_soundness_conditional (c : Nat)
    (H_star : ∀ (m' : Fin c) (i : Fin 3) (m : Fin c) (β : EnrichedEdgeCoch c),
        psi_layer c m' (cupOpp_param c (starS c i m) β) = false)
    (H_incid : ∀ (m' : Fin c) (j : Fin 3) (m : Fin c) (α : EnrichedEdgeCoch c),
        psi_layer c m' (cupOpp_param c α (incidT c j m)) = false) :
    ∀ v, InPrimaryCupSpanPlusBoundary c v →
      ∀ (m' : Fin c), psi_layer c m' v = false := by
  intro v hv
  induction hv with
  | zero => intro m'; unfold psi_layer; rfl
  | coboundary σ => intro m'; exact psi_layer_kills_delta1 c σ m'
  | starCup i m β => intro m'; exact H_star m' i m β
  | incidCup j m α => intro m'; exact H_incid m' j m α
  | xor_add v w _ _ ih1 ih2 =>
      intro m'
      rw [psi_layer_linear]
      rw [ih1 m', ih2 m']
      rfl
  | cong v w h_eq _ ih =>
      intro m'
      rw [psi_layer_pw_congr c m' v w h_eq]
      exact ih m'

/-! ## §4.7 — Unconditional soundness at c = 1 (single layer)

At `c = 1` the parametric index `m : Fin 1` is forced to
`⟨0, _⟩`, so the conditional hypotheses `H_star` and `H_incid` of
`primary_cup_span_soundness_conditional` reduce to the
bottom-layer kills already proven in `V33EnrichedParametric`
(`psi_layer_kills_cupOpp_S{0,1,2}star_left_at_bottom` and
`psi_layer_kills_cupOpp_T{0,1,2}incid_right_at_bottom`).
Hence the soundness is UNCONDITIONAL at single layer. -/

private theorem fin1_eq_zero (m : Fin 1) : m = ⟨0, by decide⟩ := by
  match m with
  | ⟨0, _⟩ => rfl
  | ⟨n+1, h⟩ =>
      exfalso
      exact absurd (Nat.le_add_left 1 n) (Nat.not_le_of_lt h)

private theorem fin3_cases {P : Fin 3 → Prop}
    (h0 : P ⟨0, by decide⟩) (h1 : P ⟨1, by decide⟩) (h2 : P ⟨2, by decide⟩)
    (i : Fin 3) : P i := by
  match i with
  | ⟨0, _⟩ => exact h0
  | ⟨1, _⟩ => exact h1
  | ⟨2, _⟩ => exact h2
  | ⟨n+3, h⟩ =>
      exfalso
      exact absurd (Nat.le_add_left 3 n) (Nat.not_le_of_lt h)

theorem primary_cup_span_soundness_c1 :
    ∀ v, InPrimaryCupSpanPlusBoundary 1 v →
      ∀ (m' : Fin 1), psi_layer 1 m' v = false :=
  primary_cup_span_soundness_conditional 1
    (fun m' i m β => by
      rw [fin1_eq_zero m, fin1_eq_zero m']
      refine @fin3_cases
        (fun k => psi_layer 1 ⟨0, by decide⟩
                  (cupOpp_param 1 (starS 1 k ⟨0, by decide⟩) β) = false) ?_ ?_ ?_ i
      · exact psi_layer_kills_cupOpp_S0star_left_at_bottom 1 (by decide) β
      · exact psi_layer_kills_cupOpp_S1star_left_at_bottom 1 (by decide) β
      · exact psi_layer_kills_cupOpp_S2star_left_at_bottom 1 (by decide) β)
    (fun m' j m α => by
      rw [fin1_eq_zero m, fin1_eq_zero m']
      refine @fin3_cases
        (fun k => psi_layer 1 ⟨0, by decide⟩
                  (cupOpp_param 1 α (incidT 1 k ⟨0, by decide⟩)) = false) ?_ ?_ ?_ j
      · exact psi_layer_kills_cupOpp_T0incid_right_at_bottom 1 (by decide) α
      · exact psi_layer_kills_cupOpp_T1incid_right_at_bottom 1 (by decide) α
      · exact psi_layer_kills_cupOpp_T2incid_right_at_bottom 1 (by decide) α)

/-! ## §4.8 — Cross-layer vanishing (structural piece of Direction B)

For `m ≠ m'`, the primary cup `cupOpp_param (starS i m) β` has no
support at layer m' (since `starS i m` evaluates to false at every
layer-m' edge by 9-block disjointness — `nine_block_disjoint_op`).
Hence `ψ_{m'}` automatically kills these cross-layer primary cups.

This closes the CROSS-LAYER half of the soundness hypothesis of
`primary_cup_span_soundness_conditional` UNCONDITIONALLY (for any
c, any layer pair m ≠ m').  The remaining open piece is the
on-layer kill (`m = m'` case): extending the bottom-layer
`psi_layer_kills_cupOpp_S{i}star_left_at_bottom` from `m = 0` to
arbitrary `m`, which is Direction B's targeted-`rw` challenge over
`9·m + …` offsets. -/

theorem starS_layer_disjoint (c : Nat) (i : Fin 3) (m m' : Fin c)
    (h : m.val ≠ m'.val) (j k : Fin 3) :
    starS c i m (edge_idx c j k m') = false := by
  have h_mm' : m'.val ≠ m.val := Ne.symm h
  have hj : j.val ≤ 2 := Nat.le_of_lt_succ j.isLt
  have hk : k.val ≤ 2 := Nat.le_of_lt_succ k.isLt
  have hi : i.val ≤ 2 := Nat.le_of_lt_succ i.isLt
  have hjk_lt : 3 * j.val + k.val < 9 :=
    Nat.lt_of_le_of_lt (Nat.add_le_add (Nat.mul_le_mul_left 3 hj) hk) (by decide)
  have hi_le_6 : 3 * i.val ≤ 6 := Nat.mul_le_mul_left 3 hi
  have hi_lt_9 : 3 * i.val < 9 := Nat.lt_of_le_of_lt hi_le_6 (by decide)
  have hi1_lt_9 : 3 * i.val + 1 < 9 :=
    Nat.lt_of_le_of_lt (Nat.add_le_add hi_le_6 (Nat.le_refl 1)) (by decide)
  have hi2_lt_9 : 3 * i.val + 2 < 9 :=
    Nat.lt_of_le_of_lt (Nat.add_le_add hi_le_6 (Nat.le_refl 2)) (by decide)
  show ((9 * m'.val + 3 * j.val + k.val == 9 * m.val + 3 * i.val)
        || (9 * m'.val + 3 * j.val + k.val == 9 * m.val + 3 * i.val + 1)
        || (9 * m'.val + 3 * j.val + k.val == 9 * m.val + 3 * i.val + 2)) = false
  rw [Nat.add_assoc (9 * m'.val) (3 * j.val) k.val]
  rw [Nat.add_assoc (9 * m.val) (3 * i.val) 1]
  rw [Nat.add_assoc (9 * m.val) (3 * i.val) 2]
  rw [nine_block_disjoint_op h_mm' hjk_lt hi_lt_9]
  rw [nine_block_disjoint_op h_mm' hjk_lt hi1_lt_9]
  rw [nine_block_disjoint_op h_mm' hjk_lt hi2_lt_9]
  rfl

theorem incidT_layer_disjoint (c : Nat) (j : Fin 3) (m m' : Fin c)
    (h : m.val ≠ m'.val) (s t : Fin 3) :
    incidT c j m (edge_idx c s t m') = false := by
  have h_mm' : m'.val ≠ m.val := Ne.symm h
  have hs : s.val ≤ 2 := Nat.le_of_lt_succ s.isLt
  have ht : t.val ≤ 2 := Nat.le_of_lt_succ t.isLt
  have hj : j.val ≤ 2 := Nat.le_of_lt_succ j.isLt
  have hst_lt : 3 * s.val + t.val < 9 :=
    Nat.lt_of_le_of_lt (Nat.add_le_add (Nat.mul_le_mul_left 3 hs) ht) (by decide)
  have hj_lt : j.val < 9 := Nat.lt_of_le_of_lt hj (by decide)
  have h3j_lt : 3 + j.val < 9 :=
    Nat.lt_of_le_of_lt (Nat.add_le_add (Nat.le_refl 3) hj) (by decide)
  have h6j_lt : 6 + j.val < 9 :=
    Nat.lt_of_le_of_lt (Nat.add_le_add (Nat.le_refl 6) hj) (by decide)
  show ((9 * m'.val + 3 * s.val + t.val == 9 * m.val + j.val)
        || (9 * m'.val + 3 * s.val + t.val == 9 * m.val + 3 + j.val)
        || (9 * m'.val + 3 * s.val + t.val == 9 * m.val + 6 + j.val)) = false
  rw [Nat.add_assoc (9 * m'.val) (3 * s.val) t.val]
  rw [Nat.add_assoc (9 * m.val) 3 j.val]
  rw [Nat.add_assoc (9 * m.val) 6 j.val]
  rw [nine_block_disjoint_op h_mm' hst_lt hj_lt]
  rw [nine_block_disjoint_op h_mm' hst_lt h3j_lt]
  rw [nine_block_disjoint_op h_mm' hst_lt h6j_lt]
  rfl

theorem cupOpp_starS_cross_layer_zero (c : Nat) (i : Fin 3) (m m' : Fin c)
    (h : m.val ≠ m'.val) (β : EnrichedEdgeCoch c) (s t : Fin 3) :
    cupOpp_param c (starS c i m) β s t m' = false := by
  unfold cupOpp_param diag_pair_param
  rw [starS_layer_disjoint c i m m' h (pair_lo s) (pair_lo t)]
  rw [starS_layer_disjoint c i m m' h (pair_hi s) (pair_hi t)]
  rw [starS_layer_disjoint c i m m' h (pair_hi s) (pair_lo t)]
  rw [starS_layer_disjoint c i m m' h (pair_lo s) (pair_hi t)]
  rfl

theorem cupOpp_incidT_cross_layer_zero (c : Nat) (j : Fin 3) (m m' : Fin c)
    (h : m.val ≠ m'.val) (α : EnrichedEdgeCoch c) (s t : Fin 3) :
    cupOpp_param c α (incidT c j m) s t m' = false := by
  unfold cupOpp_param diag_pair_param
  rw [incidT_layer_disjoint c j m m' h (pair_lo s) (pair_lo t)]
  rw [incidT_layer_disjoint c j m m' h (pair_hi s) (pair_hi t)]
  rw [incidT_layer_disjoint c j m m' h (pair_hi s) (pair_lo t)]
  rw [incidT_layer_disjoint c j m m' h (pair_lo s) (pair_hi t)]
  -- After rewrites the incidT-side factor is false; `_ && false`
  -- doesn't reduce by `rfl` (Bool.and matches first arg), so use
  -- explicit `Bool.and_false` rewrites.
  rw [Bool.and_false, Bool.and_false, Bool.and_false, Bool.and_false]
  rfl

theorem psi_layer_starCup_cross_layer (c : Nat) (i : Fin 3) (m m' : Fin c)
    (h : m.val ≠ m'.val) (β : EnrichedEdgeCoch c) :
    psi_layer c m' (cupOpp_param c (starS c i m) β) = false := by
  unfold psi_layer
  rw [cupOpp_starS_cross_layer_zero c i m m' h β ⟨0, by decide⟩ ⟨0, by decide⟩]
  rw [cupOpp_starS_cross_layer_zero c i m m' h β ⟨0, by decide⟩ ⟨1, by decide⟩]
  rw [cupOpp_starS_cross_layer_zero c i m m' h β ⟨0, by decide⟩ ⟨2, by decide⟩]
  rw [cupOpp_starS_cross_layer_zero c i m m' h β ⟨1, by decide⟩ ⟨0, by decide⟩]
  rw [cupOpp_starS_cross_layer_zero c i m m' h β ⟨1, by decide⟩ ⟨1, by decide⟩]
  rw [cupOpp_starS_cross_layer_zero c i m m' h β ⟨1, by decide⟩ ⟨2, by decide⟩]
  rw [cupOpp_starS_cross_layer_zero c i m m' h β ⟨2, by decide⟩ ⟨0, by decide⟩]
  rw [cupOpp_starS_cross_layer_zero c i m m' h β ⟨2, by decide⟩ ⟨1, by decide⟩]
  rw [cupOpp_starS_cross_layer_zero c i m m' h β ⟨2, by decide⟩ ⟨2, by decide⟩]
  rfl

theorem psi_layer_incidCup_cross_layer (c : Nat) (j : Fin 3) (m m' : Fin c)
    (h : m.val ≠ m'.val) (α : EnrichedEdgeCoch c) :
    psi_layer c m' (cupOpp_param c α (incidT c j m)) = false := by
  unfold psi_layer
  rw [cupOpp_incidT_cross_layer_zero c j m m' h α ⟨0, by decide⟩ ⟨0, by decide⟩]
  rw [cupOpp_incidT_cross_layer_zero c j m m' h α ⟨0, by decide⟩ ⟨1, by decide⟩]
  rw [cupOpp_incidT_cross_layer_zero c j m m' h α ⟨0, by decide⟩ ⟨2, by decide⟩]
  rw [cupOpp_incidT_cross_layer_zero c j m m' h α ⟨1, by decide⟩ ⟨0, by decide⟩]
  rw [cupOpp_incidT_cross_layer_zero c j m m' h α ⟨1, by decide⟩ ⟨1, by decide⟩]
  rw [cupOpp_incidT_cross_layer_zero c j m m' h α ⟨1, by decide⟩ ⟨2, by decide⟩]
  rw [cupOpp_incidT_cross_layer_zero c j m m' h α ⟨2, by decide⟩ ⟨0, by decide⟩]
  rw [cupOpp_incidT_cross_layer_zero c j m m' h α ⟨2, by decide⟩ ⟨1, by decide⟩]
  rw [cupOpp_incidT_cross_layer_zero c j m m' h α ⟨2, by decide⟩ ⟨2, by decide⟩]
  rfl

/-! ## §4.9 — Strengthened soundness (only on-layer kill required)

Combining `primary_cup_span_soundness_conditional` with the cross-layer
vanishing theorems above: the soundness `InPrimary ⊆ joint ψ-kernel`
now only requires the **on-layer** kill `ψ_m(starS i m ∪ β) = 0`
(and the T-analogue) for each `m`.  Cross-layer cases are dispatched
automatically by `psi_layer_starCup_cross_layer` /
`psi_layer_incidCup_cross_layer`.

This isolates Direction B's remaining work to a SINGLE conceptual
target: extend the bottom-layer kill to arbitrary `m`.  All
structural cross-layer reasoning is now closed. -/

theorem primary_cup_span_soundness_on_layer (c : Nat)
    (H_star_on : ∀ (i : Fin 3) (m : Fin c) (β : EnrichedEdgeCoch c),
        psi_layer c m (cupOpp_param c (starS c i m) β) = false)
    (H_incid_on : ∀ (j : Fin 3) (m : Fin c) (α : EnrichedEdgeCoch c),
        psi_layer c m (cupOpp_param c α (incidT c j m)) = false) :
    ∀ v, InPrimaryCupSpanPlusBoundary c v →
      ∀ (m' : Fin c), psi_layer c m' v = false := by
  apply primary_cup_span_soundness_conditional c
  · intro m' i m β
    cases hmm : decide (m.val = m'.val) with
    | true =>
        have hm_eq : m.val = m'.val := of_decide_eq_true hmm
        have hm : m = m' := Fin.ext hm_eq
        rw [hm]
        exact H_star_on i m' β
    | false =>
        have hm_ne : m.val ≠ m'.val := of_decide_eq_false hmm
        exact psi_layer_starCup_cross_layer c i m m' hm_ne β
  · intro m' j m α
    cases hmm : decide (m.val = m'.val) with
    | true =>
        have hm_eq : m.val = m'.val := of_decide_eq_true hmm
        have hm : m = m' := Fin.ext hm_eq
        rw [hm]
        exact H_incid_on j m' α
    | false =>
        have hm_ne : m.val ≠ m'.val := of_decide_eq_false hmm
        exact psi_layer_incidCup_cross_layer c j m m' hm_ne α

/-! ## §4.10 — Unconditional all-c soundness

Chaining `primary_cup_span_soundness_on_layer` with
`parametric_arbitrary_m_full_kill_capstone` (Direction B's
arbitrary-m bilateral kill) discharges both on-layer hypotheses
`H_star_on` and `H_incid_on`.  Hence `InPrimary ⊆ joint ψ-kernel`
holds UNCONDITIONALLY for every `c`, generalising
`primary_cup_span_soundness_c1` (§4.7) from single-layer to
arbitrary multiplicity.

Closes the EASY direction (soundness) of the c-counter upper
bound at every Stern-Brocot position.  The matching HARD
direction (joint ψ-kernel ⊆ InPrimary) remains an open piece,
reducible to the single-layer K_{3,3} dim count (`theory/RESEARCH_PLAN.md`
§1.1).  -/

theorem primary_cup_span_soundness_all_c (c : Nat) :
    ∀ v, InPrimaryCupSpanPlusBoundary c v →
      ∀ (m' : Fin c), psi_layer c m' v = false := by
  apply primary_cup_span_soundness_on_layer c
  · intro i m β
    refine @fin3_cases
        (fun k => psi_layer c m (cupOpp_param c (starS c k m) β) = false) ?_ ?_ ?_ i
    · exact (parametric_arbitrary_m_full_kill_capstone c m).1 β |>.1
    · exact (parametric_arbitrary_m_full_kill_capstone c m).1 β |>.2.1
    · exact (parametric_arbitrary_m_full_kill_capstone c m).1 β |>.2.2
  · intro j m α
    refine @fin3_cases
        (fun k => psi_layer c m (cupOpp_param c α (incidT c k m)) = false) ?_ ?_ ?_ j
    · exact (parametric_arbitrary_m_full_kill_capstone c m).2 α |>.1
    · exact (parametric_arbitrary_m_full_kill_capstone c m).2 α |>.2.1
    · exact (parametric_arbitrary_m_full_kill_capstone c m).2 α |>.2.2

/-! ## §5 — Conditional `codim ≤ c` upper bound

Given the joint-ψ-kernel hypothesis (`H_kernel_in_span`: every face
cochain killed by all c ψ's lies in `InPrimaryCupSpanPlusBoundary`),
every v decomposes — modulo `InPrimaryCupSpanPlusBoundary` — as its
canonical `weighted_e_sum c (ψ-vector v)` representative.

Corollary: the c ψ-discriminators SPAN the dual of
`EnrichedFaceVal c / InPrimaryCupSpanPlusBoundary`, matching the
parametric lower bound (`codim ≥ c`) and closing the c-counter
upper bound for the PRIMARY cup-image (the substantive sense in
which `codim = c`). -/

theorem codim_upper_bound_conditional (c : Nat)
    (H_kernel_in_span :
      ∀ r : EnrichedFaceVal c,
        (∀ m, psi_layer c m r = false) → InPrimaryCupSpanPlusBoundary c r) :
    ∀ v : EnrichedFaceVal c,
      InPrimaryCupSpanPlusBoundary c (psi_residual c v)
      ∧ (∀ s t m', v s t m'
            = xor (weighted_e_sum c (fun m => psi_layer c m v) s t m')
                  (psi_residual c v s t m')) := by
  intro v
  refine ⟨H_kernel_in_span (psi_residual c v) (psi_residual_kills_all_psi c v), ?_⟩
  intro s t m'
  exact psi_canonical_decomposition c v s t m'

/-! ## §6 — Capstone: parametric dual-span (conditional)

The c functionals `(ψ_0, …, ψ_{c-1})` are linearly independent
(established in `V33EnrichedParametric` via the dual basis
`e_face_layer m` with Kronecker-δ signature) and, conditionally
on the per-layer cup-image span hypothesis, span the dual of
`EnrichedFaceVal c / InPrimaryCupSpanPlusBoundary`.

The hypothesis `H` reduces parametrically to a single per-layer
fact at K_{3,3}: the 9-element face space modulo (im δ¹ +
primary cup-image) has dim 1.  Layer-disjointness of δ¹ and
the primary cup-image lifts this per-layer fact to the c-layer
parametric statement. -/

theorem parametric_dual_span_capstone (c : Nat)
    (H : ∀ r : EnrichedFaceVal c,
      (∀ m, psi_layer c m r = false) → InPrimaryCupSpanPlusBoundary c r) :
    ∀ v : EnrichedFaceVal c, ∃ b : Fin c → Bool,
      (∀ m, b m = psi_layer c m v)
      ∧ InPrimaryCupSpanPlusBoundary c (psi_residual c v)
      ∧ (∀ s t m', v s t m'
            = xor (weighted_e_sum c b s t m') (psi_residual c v s t m')) := by
  intro v
  refine ⟨fun m => psi_layer c m v, ?_, ?_, ?_⟩
  · intro _; rfl
  · exact H (psi_residual c v) (psi_residual_kills_all_psi c v)
  · intro s t m'
    exact psi_canonical_decomposition c v s t m'

end E213.Lib.Math.Cohomology.Bipartite.V33EnrichedParametricDualSpan
