import E213.Lib.Math.Cohomology.Bipartite.V33EnrichedParametricDualSpan

/-!
# Per-layer completeness: HARD direction at K_{3,3}^{(c=1)}

★★★★★★★★★★★★★★★ **Joint ψ-kernel ⊆ InPrimary at c = 1 — HARD
direction closure.** ★★★★★★★★★★★★★★★

Companion to `V33EnrichedParametricDualSpan`.  The EASY direction
(`primary_cup_span_soundness_all_c`) gives unconditional `InPrimary
⊆ joint ψ-kernel` at every c.  This file closes the HARD direction
at single-layer `c = 1`: every face cochain `v : EnrichedFaceVal 1`
with `ψ_0(v) = 0` lies in `InPrimaryCupSpanPlusBoundary 1`.

## Strategy

The 9-element face space at `c = 1` decomposes as
  9 = dim(ψ-kernel) + 1 = 8 + 1
with the missing dimension generated by `e_face_layer 1 ⟨0, _⟩`.
We exhibit 8 explicit primary cup-product generators
`g_1, …, g_8 ∈ InPrimary 1` spanning the dim-8 ψ-kernel:

  · g_1 = cupOpp(starS 0 0, e_{(1,0)})  =  e_{(0,0)} ⊕ e_{(0,1)}
  · g_2 = cupOpp(starS 0 0, e_{(1,1)})  =  e_{(0,0)} ⊕ e_{(0,2)}
  · g_3 = cupOpp(starS 0 0, e_{(2,0)})  =  e_{(1,0)} ⊕ e_{(1,1)}
  · g_4 = cupOpp(starS 0 0, e_{(2,1)})  =  e_{(1,0)} ⊕ e_{(1,2)}
  · g_5 = cupOpp(starS 1 0, e_{(2,0)})  =  e_{(2,0)} ⊕ e_{(2,1)}
  · g_6 = cupOpp(starS 1 0, e_{(2,1)})  =  e_{(2,0)} ⊕ e_{(2,2)}
  · g_7 = cupOpp(e_{(0,1)}, incidT 0 0) =  e_{(0,0)} ⊕ e_{(1,0)}
  · g_8 = cupOpp(e_{(2,1)}, incidT 0 0) =  e_{(1,0)} ⊕ e_{(2,0)}

These 8 are linearly independent in `EnrichedFaceVal 1` (8 distinct
support patterns, none in the span of the others by row/column
parity).  Any `v` with `ψ_0(v) = 0` admits the closed-form
decomposition
  v = b₁·g_1 ⊕ b₂·g_2 ⊕ ⋯ ⊕ b₈·g_8
with coefficients
  b₁ = v(0,1), b₂ = v(0,2), b₃ = v(1,1), b₄ = v(1,2),
  b₅ = v(2,1), b₆ = v(2,2),
  b₇ = v(0,0) ⊕ v(0,1) ⊕ v(0,2),
  b₈ = v(2,0) ⊕ v(2,1) ⊕ v(2,2).

The position-(1,0) equation `v(1,0) = b₃ ⊕ b₄ ⊕ b₇ ⊕ b₈` is exactly
the consequence of `ψ_0(v) = 0` (XOR-sum of the 9 face values).

## c-lift via layer-disjointness

For `c > 1`, decompose `v` as XOR over `m ∈ Fin c` of its layer-`m`
slice `(fun s t m' => if m'.val = m.val then v s t m else false)`.
Each layer-`m` slice lies in `InPrimary c` by lifting the c=1
construction with `starS i m` / `incidT j m` in place of layer-0
generators.

STRICT ∅-AXIOM.
-/

namespace E213.Lib.Math.Cohomology.Bipartite.V33EnrichedParametricDualSpanHard

open E213.Lib.Math.Cohomology.Bipartite.V33EnrichedParametric
open E213.Lib.Math.Cohomology.Bipartite.V33EnrichedParametricDualSpan

/-! ## §1 — Single-edge cochain at a fixed (i, j, m) -/

/-- The single-edge indicator at edge `(i, j, m)` in `Fin (9·c)`. -/
def e_edge (c : Nat) (i j : Fin 3) (m : Fin c) : EnrichedEdgeCoch c :=
  fun e => decide (e.val = (edge_idx c i j m).val)

/-! ## §2 — The 8 explicit generators at `c = 1`

Each generator is a single primary cup-product (witness via `starCup`
or `incidCup` constructor).  Their face-value patterns are computed
in §3 below; the labels reflect "row pair-difference" (rows 0, 1, 2)
and "column pair-difference" (col 0). -/

/-- Layer-0 mult index at c=1. -/
private def m0 : Fin 1 := ⟨0, by decide⟩

private def i0 : Fin 3 := ⟨0, by decide⟩
private def i1 : Fin 3 := ⟨1, by decide⟩
private def i2 : Fin 3 := ⟨2, by decide⟩

/-- g_1 = cupOpp(starS 0 0, e_{edge (1,0)})  =  e_{(0,0)} ⊕ e_{(0,1)}. -/
def g1 : EnrichedFaceVal 1 :=
  cupOpp_param 1 (starS 1 i0 m0) (e_edge 1 i1 i0 m0)

/-- g_2 = cupOpp(starS 0 0, e_{edge (1,1)})  =  e_{(0,0)} ⊕ e_{(0,2)}. -/
def g2 : EnrichedFaceVal 1 :=
  cupOpp_param 1 (starS 1 i0 m0) (e_edge 1 i1 i1 m0)

/-- g_3 = cupOpp(starS 0 0, e_{edge (2,0)})  =  e_{(1,0)} ⊕ e_{(1,1)}. -/
def g3 : EnrichedFaceVal 1 :=
  cupOpp_param 1 (starS 1 i0 m0) (e_edge 1 i2 i0 m0)

/-- g_4 = cupOpp(starS 0 0, e_{edge (2,1)})  =  e_{(1,0)} ⊕ e_{(1,2)}. -/
def g4 : EnrichedFaceVal 1 :=
  cupOpp_param 1 (starS 1 i0 m0) (e_edge 1 i2 i1 m0)

/-- g_5 = cupOpp(starS 1 0, e_{edge (2,0)})  =  e_{(2,0)} ⊕ e_{(2,1)}. -/
def g5 : EnrichedFaceVal 1 :=
  cupOpp_param 1 (starS 1 i1 m0) (e_edge 1 i2 i0 m0)

/-- g_6 = cupOpp(starS 1 0, e_{edge (2,1)})  =  e_{(2,0)} ⊕ e_{(2,2)}. -/
def g6 : EnrichedFaceVal 1 :=
  cupOpp_param 1 (starS 1 i1 m0) (e_edge 1 i2 i1 m0)

/-- g_7 = cupOpp(e_{edge (0,1)}, incidT 0 0)  =  e_{(0,0)} ⊕ e_{(1,0)}. -/
def g7 : EnrichedFaceVal 1 :=
  cupOpp_param 1 (e_edge 1 i0 i1 m0) (incidT 1 i0 m0)

/-- g_8 = cupOpp(e_{edge (2,1)}, incidT 0 0)  =  e_{(1,0)} ⊕ e_{(2,0)}. -/
def g8 : EnrichedFaceVal 1 :=
  cupOpp_param 1 (e_edge 1 i2 i1 m0) (incidT 1 i0 m0)

/-! ## §3 — Each generator lies in `InPrimaryCupSpanPlusBoundary 1`

By a single `starCup` or `incidCup` constructor application. -/

theorem g1_in_primary : InPrimaryCupSpanPlusBoundary 1 g1 :=
  InPrimaryCupSpanPlusBoundary.starCup i0 m0 (e_edge 1 i1 i0 m0)

theorem g2_in_primary : InPrimaryCupSpanPlusBoundary 1 g2 :=
  InPrimaryCupSpanPlusBoundary.starCup i0 m0 (e_edge 1 i1 i1 m0)

theorem g3_in_primary : InPrimaryCupSpanPlusBoundary 1 g3 :=
  InPrimaryCupSpanPlusBoundary.starCup i0 m0 (e_edge 1 i2 i0 m0)

theorem g4_in_primary : InPrimaryCupSpanPlusBoundary 1 g4 :=
  InPrimaryCupSpanPlusBoundary.starCup i0 m0 (e_edge 1 i2 i1 m0)

theorem g5_in_primary : InPrimaryCupSpanPlusBoundary 1 g5 :=
  InPrimaryCupSpanPlusBoundary.starCup i1 m0 (e_edge 1 i2 i0 m0)

theorem g6_in_primary : InPrimaryCupSpanPlusBoundary 1 g6 :=
  InPrimaryCupSpanPlusBoundary.starCup i1 m0 (e_edge 1 i2 i1 m0)

theorem g7_in_primary : InPrimaryCupSpanPlusBoundary 1 g7 :=
  InPrimaryCupSpanPlusBoundary.incidCup i0 m0 (e_edge 1 i0 i1 m0)

theorem g8_in_primary : InPrimaryCupSpanPlusBoundary 1 g8 :=
  InPrimaryCupSpanPlusBoundary.incidCup i0 m0 (e_edge 1 i2 i1 m0)

/-! ## §4 — Value patterns of `g_1 … g_8`

Concrete computation of `g_k ⟨s,_⟩ ⟨t,_⟩ ⟨0,_⟩` at the 9 face
positions.  Used in §5 to verify the decomposition equation.

Each pattern can be read directly off the support set declared in §2.
Verified by `rfl` once the cup expansion is unfolded. -/

private def f00 : Fin 3 × Fin 3 := (i0, i0)
private def f01 : Fin 3 × Fin 3 := (i0, i1)
private def f02 : Fin 3 × Fin 3 := (i0, i2)
private def f10 : Fin 3 × Fin 3 := (i1, i0)
private def f11 : Fin 3 × Fin 3 := (i1, i1)
private def f12 : Fin 3 × Fin 3 := (i1, i2)
private def f20 : Fin 3 × Fin 3 := (i2, i0)
private def f21 : Fin 3 × Fin 3 := (i2, i1)
private def f22 : Fin 3 × Fin 3 := (i2, i2)

/-! ## §5 — Scaling generators by Bool coefficients

To form `b_i · g_i` (a face cochain) we use `scaled b w`, which is
either `w` (when `b = true`) or zero (when `b = false`).  Both
choices preserve `InPrimary`, allowing us to build the candidate
XOR-add chain. -/

/-- Scalar product of a Bool and a face cochain. -/
def scaled (b : Bool) (w : EnrichedFaceVal 1) : EnrichedFaceVal 1 :=
  match b with
  | true => w
  | false => fun _ _ _ => false

theorem scaled_in_primary (b : Bool) (w : EnrichedFaceVal 1)
    (hw : InPrimaryCupSpanPlusBoundary 1 w) :
    InPrimaryCupSpanPlusBoundary 1 (scaled b w) := by
  cases b
  · exact InPrimaryCupSpanPlusBoundary.zero
  · exact hw

theorem scaled_val (b : Bool) (w : EnrichedFaceVal 1) (s t : Fin 3) (m : Fin 1) :
    scaled b w s t m = (b && w s t m) := by
  cases b <;> rfl

/-! ## §6 — Candidate decomposition

Given `v : EnrichedFaceVal 1`, define its canonical decomposition
into `g_1 … g_8`:

  b₁ = v(0,1), b₂ = v(0,2), b₃ = v(1,1), b₄ = v(1,2),
  b₅ = v(2,1), b₆ = v(2,2),
  b₇ = v(0,0) ⊕ v(0,1) ⊕ v(0,2),
  b₈ = v(2,0) ⊕ v(2,1) ⊕ v(2,2).

The candidate function is the XOR-add chain `⊕ᵢ (b_i · g_i)`. -/

def b1_of (v : EnrichedFaceVal 1) : Bool := v i0 i1 m0
def b2_of (v : EnrichedFaceVal 1) : Bool := v i0 i2 m0
def b3_of (v : EnrichedFaceVal 1) : Bool := v i1 i1 m0
def b4_of (v : EnrichedFaceVal 1) : Bool := v i1 i2 m0
def b5_of (v : EnrichedFaceVal 1) : Bool := v i2 i1 m0
def b6_of (v : EnrichedFaceVal 1) : Bool := v i2 i2 m0
def b7_of (v : EnrichedFaceVal 1) : Bool :=
  xor (xor (v i0 i0 m0) (v i0 i1 m0)) (v i0 i2 m0)
def b8_of (v : EnrichedFaceVal 1) : Bool :=
  xor (xor (v i2 i0 m0) (v i2 i1 m0)) (v i2 i2 m0)

/-- The XOR-add chain of scaled generators.  Built so that
    its function-literal form is exactly what `xor_add` produces. -/
def candidate (v : EnrichedFaceVal 1) : EnrichedFaceVal 1 :=
  fun s t m' =>
    xor (scaled (b1_of v) g1 s t m')
     (xor (scaled (b2_of v) g2 s t m')
      (xor (scaled (b3_of v) g3 s t m')
       (xor (scaled (b4_of v) g4 s t m')
        (xor (scaled (b5_of v) g5 s t m')
         (xor (scaled (b6_of v) g6 s t m')
          (xor (scaled (b7_of v) g7 s t m')
               (scaled (b8_of v) g8 s t m')))))))

theorem candidate_in_primary (v : EnrichedFaceVal 1) :
    InPrimaryCupSpanPlusBoundary 1 (candidate v) :=
  InPrimaryCupSpanPlusBoundary.xor_add _ _
    (scaled_in_primary (b1_of v) g1 g1_in_primary)
    (InPrimaryCupSpanPlusBoundary.xor_add _ _
      (scaled_in_primary (b2_of v) g2 g2_in_primary)
      (InPrimaryCupSpanPlusBoundary.xor_add _ _
        (scaled_in_primary (b3_of v) g3 g3_in_primary)
        (InPrimaryCupSpanPlusBoundary.xor_add _ _
          (scaled_in_primary (b4_of v) g4 g4_in_primary)
          (InPrimaryCupSpanPlusBoundary.xor_add _ _
            (scaled_in_primary (b5_of v) g5 g5_in_primary)
            (InPrimaryCupSpanPlusBoundary.xor_add _ _
              (scaled_in_primary (b6_of v) g6 g6_in_primary)
              (InPrimaryCupSpanPlusBoundary.xor_add _ _
                (scaled_in_primary (b7_of v) g7 g7_in_primary)
                (scaled_in_primary (b8_of v) g8 g8_in_primary)))))))

/-! ## §7 — Per-position values of `g_1 … g_8`

For each of the 9 face positions, the value of each generator is a
concrete Bool, computed by `decide` after unfolding the cup, star, and
incidence definitions. -/

theorem g_vals_at_00 :
    g1 i0 i0 m0 = true ∧ g2 i0 i0 m0 = true ∧ g3 i0 i0 m0 = false ∧
    g4 i0 i0 m0 = false ∧ g5 i0 i0 m0 = false ∧ g6 i0 i0 m0 = false ∧
    g7 i0 i0 m0 = true ∧ g8 i0 i0 m0 = false := by
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩ <;> decide

theorem g_vals_at_01 :
    g1 i0 i1 m0 = true ∧ g2 i0 i1 m0 = false ∧ g3 i0 i1 m0 = false ∧
    g4 i0 i1 m0 = false ∧ g5 i0 i1 m0 = false ∧ g6 i0 i1 m0 = false ∧
    g7 i0 i1 m0 = false ∧ g8 i0 i1 m0 = false := by
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩ <;> decide

theorem g_vals_at_02 :
    g1 i0 i2 m0 = false ∧ g2 i0 i2 m0 = true ∧ g3 i0 i2 m0 = false ∧
    g4 i0 i2 m0 = false ∧ g5 i0 i2 m0 = false ∧ g6 i0 i2 m0 = false ∧
    g7 i0 i2 m0 = false ∧ g8 i0 i2 m0 = false := by
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩ <;> decide

theorem g_vals_at_10 :
    g1 i1 i0 m0 = false ∧ g2 i1 i0 m0 = false ∧ g3 i1 i0 m0 = true ∧
    g4 i1 i0 m0 = true ∧ g5 i1 i0 m0 = false ∧ g6 i1 i0 m0 = false ∧
    g7 i1 i0 m0 = true ∧ g8 i1 i0 m0 = true := by
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩ <;> decide

theorem g_vals_at_11 :
    g1 i1 i1 m0 = false ∧ g2 i1 i1 m0 = false ∧ g3 i1 i1 m0 = true ∧
    g4 i1 i1 m0 = false ∧ g5 i1 i1 m0 = false ∧ g6 i1 i1 m0 = false ∧
    g7 i1 i1 m0 = false ∧ g8 i1 i1 m0 = false := by
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩ <;> decide

theorem g_vals_at_12 :
    g1 i1 i2 m0 = false ∧ g2 i1 i2 m0 = false ∧ g3 i1 i2 m0 = false ∧
    g4 i1 i2 m0 = true ∧ g5 i1 i2 m0 = false ∧ g6 i1 i2 m0 = false ∧
    g7 i1 i2 m0 = false ∧ g8 i1 i2 m0 = false := by
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩ <;> decide

theorem g_vals_at_20 :
    g1 i2 i0 m0 = false ∧ g2 i2 i0 m0 = false ∧ g3 i2 i0 m0 = false ∧
    g4 i2 i0 m0 = false ∧ g5 i2 i0 m0 = true ∧ g6 i2 i0 m0 = true ∧
    g7 i2 i0 m0 = false ∧ g8 i2 i0 m0 = true := by
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩ <;> decide

theorem g_vals_at_21 :
    g1 i2 i1 m0 = false ∧ g2 i2 i1 m0 = false ∧ g3 i2 i1 m0 = false ∧
    g4 i2 i1 m0 = false ∧ g5 i2 i1 m0 = true ∧ g6 i2 i1 m0 = false ∧
    g7 i2 i1 m0 = false ∧ g8 i2 i1 m0 = false := by
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩ <;> decide

theorem g_vals_at_22 :
    g1 i2 i2 m0 = false ∧ g2 i2 i2 m0 = false ∧ g3 i2 i2 m0 = false ∧
    g4 i2 i2 m0 = false ∧ g5 i2 i2 m0 = false ∧ g6 i2 i2 m0 = true ∧
    g7 i2 i2 m0 = false ∧ g8 i2 i2 m0 = false := by
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩ <;> decide

/-! ## §8 — Per-position candidate equation

For each face position `(s, t)`, prove `candidate v s t m0 = v s t m0`.
Cases (0,0), (2,0), (1,0) require Bool reasoning; (1,0) additionally
uses `ψ_0(v) = false`.  The remaining 6 positions are trivial (only
one generator contributes). -/

/-- Bool identity: at the (0,0) position the candidate reduces to a
    three-variable XOR equation whose pure-Bool form yields the target.
    All 8 v-position arguments must appear because the goal has them
    syntactically; the irrelevant ones are absorbed by `_ && false`. -/
private theorem bool_id_00 (a b c d3 d4 d5 d6 d8 : Bool) :
    xor (a && true) (xor (b && true) (xor (d3 && false) (xor (d4 && false)
      (xor (d5 && false) (xor (d6 && false)
        (xor ((xor (xor c a) b) && true) (d8 && false))))))) = c := by
  cases a <;> cases b <;> cases c <;> cases d3 <;> cases d4 <;>
    cases d5 <;> cases d6 <;> cases d8 <;> rfl

/-- Helper: unfold candidate + scaled + g-values into a Bool expression
    for position `(s, t)`.  Each rewrite chain is identical except for
    the `g_vals_at_*` lemma used. -/
private theorem candidate_unfold (v : EnrichedFaceVal 1) (s t : Fin 3) :
    candidate v s t m0 =
      xor ((b1_of v) && g1 s t m0)
       (xor ((b2_of v) && g2 s t m0)
        (xor ((b3_of v) && g3 s t m0)
         (xor ((b4_of v) && g4 s t m0)
          (xor ((b5_of v) && g5 s t m0)
           (xor ((b6_of v) && g6 s t m0)
            (xor ((b7_of v) && g7 s t m0) ((b8_of v) && g8 s t m0))))))) := by
  unfold candidate
  rw [scaled_val (b1_of v) g1, scaled_val (b2_of v) g2,
      scaled_val (b3_of v) g3, scaled_val (b4_of v) g4,
      scaled_val (b5_of v) g5, scaled_val (b6_of v) g6,
      scaled_val (b7_of v) g7, scaled_val (b8_of v) g8]

theorem candidate_at_00 (v : EnrichedFaceVal 1) :
    candidate v i0 i0 m0 = v i0 i0 m0 := by
  rw [candidate_unfold v i0 i0]
  obtain ⟨h1, h2, h3, h4, h5, h6, h7, h8⟩ := g_vals_at_00
  rw [h1, h2, h3, h4, h5, h6, h7, h8]
  unfold b1_of b2_of b3_of b4_of b5_of b6_of b7_of b8_of
  exact bool_id_00 (v i0 i1 m0) (v i0 i2 m0) (v i0 i0 m0)
    (v i1 i1 m0) (v i1 i2 m0) (v i2 i1 m0) (v i2 i2 m0)
    (xor (xor (v i2 i0 m0) (v i2 i1 m0)) (v i2 i2 m0))

/-- Position (0,1): only g_1 contributes (`g1(0,1) = true`, others false).
    The active coefficient is `b1_of v = v(0,1)`. -/
theorem candidate_at_01 (v : EnrichedFaceVal 1) :
    candidate v i0 i1 m0 = v i0 i1 m0 := by
  rw [candidate_unfold v i0 i1]
  obtain ⟨h1, h2, h3, h4, h5, h6, h7, h8⟩ := g_vals_at_01
  rw [h1, h2, h3, h4, h5, h6, h7, h8]
  unfold b1_of b2_of b3_of b4_of b5_of b6_of b7_of b8_of
  cases v i0 i0 m0 <;> cases v i0 i1 m0 <;> cases v i0 i2 m0 <;>
    cases v i1 i1 m0 <;> cases v i1 i2 m0 <;>
    cases v i2 i0 m0 <;> cases v i2 i1 m0 <;> cases v i2 i2 m0 <;> rfl

/-- Position (0,2): only g_2 contributes; active coefficient `b2_of v = v(0,2)`. -/
theorem candidate_at_02 (v : EnrichedFaceVal 1) :
    candidate v i0 i2 m0 = v i0 i2 m0 := by
  rw [candidate_unfold v i0 i2]
  obtain ⟨h1, h2, h3, h4, h5, h6, h7, h8⟩ := g_vals_at_02
  rw [h1, h2, h3, h4, h5, h6, h7, h8]
  unfold b1_of b2_of b3_of b4_of b5_of b6_of b7_of b8_of
  cases v i0 i0 m0 <;> cases v i0 i1 m0 <;> cases v i0 i2 m0 <;>
    cases v i1 i1 m0 <;> cases v i1 i2 m0 <;>
    cases v i2 i0 m0 <;> cases v i2 i1 m0 <;> cases v i2 i2 m0 <;> rfl

/-- Position (1,1): only g_3 contributes; active coefficient `b3_of v = v(1,1)`. -/
theorem candidate_at_11 (v : EnrichedFaceVal 1) :
    candidate v i1 i1 m0 = v i1 i1 m0 := by
  rw [candidate_unfold v i1 i1]
  obtain ⟨h1, h2, h3, h4, h5, h6, h7, h8⟩ := g_vals_at_11
  rw [h1, h2, h3, h4, h5, h6, h7, h8]
  unfold b1_of b2_of b3_of b4_of b5_of b6_of b7_of b8_of
  cases v i0 i0 m0 <;> cases v i0 i1 m0 <;> cases v i0 i2 m0 <;>
    cases v i1 i1 m0 <;> cases v i1 i2 m0 <;>
    cases v i2 i0 m0 <;> cases v i2 i1 m0 <;> cases v i2 i2 m0 <;> rfl

/-- Position (1,2): only g_4 contributes; active coefficient `b4_of v = v(1,2)`. -/
theorem candidate_at_12 (v : EnrichedFaceVal 1) :
    candidate v i1 i2 m0 = v i1 i2 m0 := by
  rw [candidate_unfold v i1 i2]
  obtain ⟨h1, h2, h3, h4, h5, h6, h7, h8⟩ := g_vals_at_12
  rw [h1, h2, h3, h4, h5, h6, h7, h8]
  unfold b1_of b2_of b3_of b4_of b5_of b6_of b7_of b8_of
  cases v i0 i0 m0 <;> cases v i0 i1 m0 <;> cases v i0 i2 m0 <;>
    cases v i1 i1 m0 <;> cases v i1 i2 m0 <;>
    cases v i2 i0 m0 <;> cases v i2 i1 m0 <;> cases v i2 i2 m0 <;> rfl

/-- Position (2,1): only g_5 contributes; active coefficient `b5_of v = v(2,1)`. -/
theorem candidate_at_21 (v : EnrichedFaceVal 1) :
    candidate v i2 i1 m0 = v i2 i1 m0 := by
  rw [candidate_unfold v i2 i1]
  obtain ⟨h1, h2, h3, h4, h5, h6, h7, h8⟩ := g_vals_at_21
  rw [h1, h2, h3, h4, h5, h6, h7, h8]
  unfold b1_of b2_of b3_of b4_of b5_of b6_of b7_of b8_of
  cases v i0 i0 m0 <;> cases v i0 i1 m0 <;> cases v i0 i2 m0 <;>
    cases v i1 i1 m0 <;> cases v i1 i2 m0 <;>
    cases v i2 i0 m0 <;> cases v i2 i1 m0 <;> cases v i2 i2 m0 <;> rfl

/-- Position (2,2): only g_6 contributes; active coefficient `b6_of v = v(2,2)`. -/
theorem candidate_at_22 (v : EnrichedFaceVal 1) :
    candidate v i2 i2 m0 = v i2 i2 m0 := by
  rw [candidate_unfold v i2 i2]
  obtain ⟨h1, h2, h3, h4, h5, h6, h7, h8⟩ := g_vals_at_22
  rw [h1, h2, h3, h4, h5, h6, h7, h8]
  unfold b1_of b2_of b3_of b4_of b5_of b6_of b7_of b8_of
  cases v i0 i0 m0 <;> cases v i0 i1 m0 <;> cases v i0 i2 m0 <;>
    cases v i1 i1 m0 <;> cases v i1 i2 m0 <;>
    cases v i2 i0 m0 <;> cases v i2 i1 m0 <;> cases v i2 i2 m0 <;> rfl

/-- Position (2,0): generators g_5, g_6, g_8 contribute; analogous to
    `candidate_at_00` with row 2 in place of row 0. -/
theorem candidate_at_20 (v : EnrichedFaceVal 1) :
    candidate v i2 i0 m0 = v i2 i0 m0 := by
  rw [candidate_unfold v i2 i0]
  obtain ⟨h1, h2, h3, h4, h5, h6, h7, h8⟩ := g_vals_at_20
  rw [h1, h2, h3, h4, h5, h6, h7, h8]
  unfold b1_of b2_of b3_of b4_of b5_of b6_of b7_of b8_of
  cases v i0 i0 m0 <;> cases v i0 i1 m0 <;> cases v i0 i2 m0 <;>
    cases v i1 i1 m0 <;> cases v i1 i2 m0 <;>
    cases v i2 i0 m0 <;> cases v i2 i1 m0 <;> cases v i2 i2 m0 <;> rfl

/-- Helper: re-express `psi_layer 1 m0 v` using the `i0/i1/i2/m0` aliases. -/
theorem psi_layer_one_eq (v : EnrichedFaceVal 1) :
    psi_layer 1 m0 v =
      xor (xor (xor (xor (xor (xor (xor (xor
        (v i0 i0 m0) (v i0 i1 m0)) (v i0 i2 m0))
        (v i1 i0 m0)) (v i1 i1 m0)) (v i1 i2 m0))
        (v i2 i0 m0)) (v i2 i1 m0)) (v i2 i2 m0) := rfl

-- Bool identity for position (1, 0): the only case requiring `ψ_0 = false`.
-- Cases where the antecedent is impossible (`true = false`) are
-- dismissed by `absurd`; the satisfiable cases reduce to `rfl`.
set_option maxHeartbeats 1600000 in
private theorem bool_id_10
    (v00 v01 v02 v10 v11 v12 v20 v21 v22 : Bool)
    (hpsi : xor (xor (xor (xor (xor (xor (xor (xor
      v00 v01) v02) v10) v11) v12) v20) v21) v22 = false) :
    xor (v01 && false) (xor (v02 && false) (xor (v11 && true)
      (xor (v12 && true) (xor (v21 && false) (xor (v22 && false)
        (xor ((xor (xor v00 v01) v02) && true)
             ((xor (xor v20 v21) v22) && true))))))) = v10 := by
  cases v00 <;> cases v01 <;> cases v02 <;> cases v10 <;> cases v11 <;>
    cases v12 <;> cases v20 <;> cases v21 <;> cases v22 <;>
    first | rfl | exact absurd hpsi (by decide)

/-- Position (1,0): the structural case requiring `ψ_0(v) = false`.
    Generators g_3, g_4, g_7, g_8 all contribute; the decomposition
    is equivalent to `v(1,0) = sum_of_others`, which is exactly the
    ψ_0-kernel condition. -/
theorem candidate_at_10 (v : EnrichedFaceVal 1)
    (hpsi : psi_layer 1 m0 v = false) :
    candidate v i1 i0 m0 = v i1 i0 m0 := by
  rw [candidate_unfold v i1 i0]
  obtain ⟨h1, h2, h3, h4, h5, h6, h7, h8⟩ := g_vals_at_10
  rw [h1, h2, h3, h4, h5, h6, h7, h8]
  unfold b1_of b2_of b3_of b4_of b5_of b6_of b7_of b8_of
  rw [psi_layer_one_eq] at hpsi
  exact bool_id_10 (v i0 i0 m0) (v i0 i1 m0) (v i0 i2 m0) (v i1 i0 m0)
    (v i1 i1 m0) (v i1 i2 m0) (v i2 i0 m0) (v i2 i1 m0) (v i2 i2 m0) hpsi

/-! ## §9 — Capstone: pointwise equality and HARD direction at c = 1

Bundle the 9 per-position equations into pointwise equality
`candidate v = v` (for any (s, t, m')); then `cong` lifts the
established `InPrimary 1 (candidate v)` to `InPrimary 1 v`. -/

theorem candidate_eq_pointwise (v : EnrichedFaceVal 1)
    (hpsi : psi_layer 1 m0 v = false)
    (s t : Fin 3) (m' : Fin 1) :
    candidate v s t m' = v s t m' := by
  match m' with
  | ⟨0, _⟩ =>
    match s, t with
    | ⟨0, _⟩, ⟨0, _⟩ => exact candidate_at_00 v
    | ⟨0, _⟩, ⟨1, _⟩ => exact candidate_at_01 v
    | ⟨0, _⟩, ⟨2, _⟩ => exact candidate_at_02 v
    | ⟨1, _⟩, ⟨0, _⟩ => exact candidate_at_10 v hpsi
    | ⟨1, _⟩, ⟨1, _⟩ => exact candidate_at_11 v
    | ⟨1, _⟩, ⟨2, _⟩ => exact candidate_at_12 v
    | ⟨2, _⟩, ⟨0, _⟩ => exact candidate_at_20 v
    | ⟨2, _⟩, ⟨1, _⟩ => exact candidate_at_21 v
    | ⟨2, _⟩, ⟨2, _⟩ => exact candidate_at_22 v
    | ⟨n+3, h⟩, _ => exfalso; exact absurd (Nat.le_add_left 3 n) (Nat.not_le_of_lt h)
    | _, ⟨n+3, h⟩ => exfalso; exact absurd (Nat.le_add_left 3 n) (Nat.not_le_of_lt h)
  | ⟨n+1, h⟩ => exfalso; exact absurd (Nat.le_add_left 1 n) (Nat.not_le_of_lt h)

/-- **HARD direction at c = 1**: every face cochain `v : EnrichedFaceVal 1`
    with `ψ_0(v) = false` lies in `InPrimaryCupSpanPlusBoundary 1`.

    Constructed via the 8-generator decomposition + cong constructor. -/
theorem joint_psi_kernel_subset_primary_c1 (v : EnrichedFaceVal 1)
    (hpsi : psi_layer 1 m0 v = false) :
    InPrimaryCupSpanPlusBoundary 1 v :=
  InPrimaryCupSpanPlusBoundary.cong v (candidate v)
    (fun s t m' => (candidate_eq_pointwise v hpsi s t m').symm)
    (candidate_in_primary v)

end E213.Lib.Math.Cohomology.Bipartite.V33EnrichedParametricDualSpanHard
