import E213.Lib.Math.Real213.GoldenFormMarkov
import E213.Lib.Physics.Simplex.Counts

/-!
# MarkovTree — the Markov equation `x²+y²+z² = 3xyz`, the Vieta tree, and `3 = NS`

The Lagrange/Markov spectrum below `3` is `{√(9m²−4)/m : m a Markov number}`, the Markov
numbers `1, 2, 5, 13, 29, …` being the largest entries of the **Markov triples** — solutions
of `x² + y² + z² = 3xyz`.  `GoldenFormMarkov` pinned the first two values `√5` (golden, `m=1`)
and `√8` (silver, `m=2`); the whole spectrum is generated by the **Markov tree**, the binary
tree of triples under Vieta jumping.

Two `213`-native facts here, both ∅-axiom:

  * the Markov coefficient is **`NS = 3`** (`markov_coefficient_is_NS`): the equation is
    `x² + y² + z² = NS·xyz`, the atomic `3` of the simplex counts — the same `3` that is the
    trace of the golden matrix `P = [[2,1],[1,1]]`;
  * **Vieta jumping** (`markov_vieta`): the two roots `z, z'` of the quadratic `t² − 3xy·t +
    (x²+y²) = 0` satisfy `z + z' = 3xy`, and if `(x,y,z)` is a triple so is `(x,y,z')`.  The
    clean engine is the involution invariant `x² + y² = z·z'` (`markov_xy`) — proved with no
    subtraction (cancel `z²` via `3xyz = z² + z·z'`), so the jump is pure `ℕ` arithmetic.

The tree from the root `(1,1,1)` (`markov_tree_branch`): `(1,1,1) → (1,1,2) → (1,2,5) →
(1,5,13) → (2,5,29)` — each a verified solution, the Markov numbers `1,2,5,13,29` whose
Lagrange values `√5, √8, √(221)/5, …` build the bottom of the approximation spectrum off the
single atomic coefficient `NS = 3`.
-/

namespace E213.Lib.Math.Real213.MarkovTree

open E213.Lib.Math.Real213.GoldenFormMarkov (add_left_cancel_pure)
open E213.Lib.Physics.Simplex.Counts (NS)

/-- The Markov equation `x² + y² + z² = 3·x·y·z`. -/
abbrev markovEq (x y z : Nat) : Prop := x * x + y * y + z * z = 3 * x * y * z

/-! ## §1 — the Vieta involution invariant `x² + y² = z·z'` -/

/-- ★★★ **The Vieta invariant.**  If `(x,y,z)` is a Markov triple and `z + z' = 3xy` (the two
    roots of `t² − 3xy·t + (x²+y²)`), then `x² + y² = z·z'`.  Pure `ℕ`: cancel `z²` from
    `3xyz = z² + z·z'`. -/
theorem markov_xy (x y z z' : Nat) (hz : z + z' = 3 * x * y) (h : markovEq x y z) :
    x * x + y * y = z * z' := by
  have h3z : 3 * x * y * z = z * z + z * z' := by
    rw [← hz, E213.Tactic.NatHelper.add_mul, Nat.mul_comm z' z]
  rw [markovEq, h3z, Nat.add_comm (x * x + y * y) (z * z)] at h
  exact add_left_cancel_pure _ _ _ h

/-- ★★★ **Vieta jumping preserves the Markov equation.**  With `z + z' = 3xy`, if `(x,y,z)`
    is a triple then `(x,y,z')` is — `x²+y²+z'² = z·z' + z'² = z'(z+z') = z'·3xy`.  Pure `ℕ`,
    no subtraction.  This is the edge relation of the Markov tree. -/
theorem markov_vieta (x y z z' : Nat) (hz : z + z' = 3 * x * y) (h : markovEq x y z) :
    markovEq x y z' := by
  have hxy : x * x + y * y = z * z' := markov_xy x y z z' hz h
  show x * x + y * y + z' * z' = 3 * x * y * z'
  rw [hxy, Nat.mul_comm z z', ← Nat.mul_add, hz, Nat.mul_comm z' (3 * x * y)]

/-! ## §2 — the coefficient is `NS`, and the tree from `(1,1,1)` -/

/-- The Markov coefficient `3` is the atomic count `NS` (trace of `P = [[2,1],[1,1]]`). -/
theorem markov_coefficient_is_NS : (3 : Nat) = NS := rfl

/-- ★★★ **The Markov tree branch `(1,1,1) → (1,1,2) → (1,2,5) → (1,5,13) → (2,5,29)`.**  Each
    is a verified solution of `x²+y²+z² = 3xyz`; the Markov numbers `1,2,5,13,29` carry the
    Lagrange values `√5, √8, √221/5, √1517/13, √7565/29` — the bottom of the spectrum. -/
theorem markov_tree_branch :
    markovEq 1 1 1 ∧ markovEq 1 1 2 ∧ markovEq 1 2 5 ∧ markovEq 1 5 13 ∧ markovEq 2 5 29 := by
  refine ⟨?_, ?_, ?_, ?_, ?_⟩ <;> decide

/-- The first Vieta jump `(1,1,1) → (1,1,2)` via `markov_vieta` (`z=1, z'=2`, `z+z' = 3 =
    3·1·1`), tying the tree engine to the `√5 → √8` step (golden → silver Markov form). -/
theorem markov_first_jump : markovEq 1 1 2 :=
  markov_vieta 1 1 1 2 (by decide) (by decide)

end E213.Lib.Math.Real213.MarkovTree
