import E213.Lib.Math.Cauchy.ZeroRunNonHolonomic
import E213.Lib.Math.DyadicFSM.Forward.ForwardPeriodicity
import E213.Meta.Tactic.NatHelper

/-!
# Morse–Hedlund — bounded + finitely-deterministic ⟹ eventually periodic

The autonomous (time-invariant) finite-state machine `AutoRec` is escaped by `χ` (powers of
two) via the all-zero window's two continuations.  That route needs *long zero-runs*.  **Dense**
aperiodic sequences (bounded run-length, e.g. Thue–Morse) have no long runs, so a different
argument is required: the **Morse–Hedlund** direction.

> A `Bool`-sequence that is **`k`-step deterministic** (the next value is a function of the
> length-`k` window) is **eventually periodic** — finitely many windows, a deterministic shift,
> pigeonhole.

Contrapositive: a **non-eventually-periodic** `Bool` sequence is, for every `k`, **not**
`k`-step deterministic — i.e. some length-`k` window occurs with two different next-values — so
(by `distinct_next_equal_window_not_autoRec`) it is generated by **no** autonomous finite-state
machine.  This is the dense companion to the sparse zero-run criterion.

This file builds the reusable binary-window encoding (Phase A) and the core theorem (Phase B).
-/

namespace E213.Lib.Math.Cauchy.MorseHedlund

/-! ## Phase A — binary window encoding and its injectivity -/

/-- `Bool` as a bit. -/
def b2n (b : Bool) : Nat := if b then 1 else 0

theorem b2n_lt_two (b : Bool) : b2n b < 2 := by cases b <;> decide

/-- Encode the length-`k` window of `f` from index `0` as a binary number
    `Σ_{t<k} b2n(f t)·2^t`, low bit first. -/
def binEnc : Nat → (Nat → Bool) → Nat
  | 0,     _ => 0
  | k + 1, f => b2n (f 0) + 2 * binEnc k (fun t => f (t + 1))

/-- The encoding fits in `k` bits. -/
theorem binEnc_lt (k : Nat) (f : Nat → Bool) : binEnc k f < 2 ^ k := by
  induction k generalizing f with
  | zero => show (0 : Nat) < 2 ^ 0; decide
  | succ k ih =>
    show b2n (f 0) + 2 * binEnc k (fun t => f (t + 1)) < 2 ^ (k + 1)
    have hr : binEnc k (fun t => f (t + 1)) + 1 ≤ 2 ^ k := ih (fun t => f (t + 1))
    calc b2n (f 0) + 2 * binEnc k (fun t => f (t + 1))
        < 2 + 2 * binEnc k (fun t => f (t + 1)) :=
          Nat.add_lt_add_right (b2n_lt_two (f 0)) _
      _ = 2 * (1 + binEnc k (fun t => f (t + 1))) := by rw [Nat.mul_add, Nat.mul_one]
      _ ≤ 2 * 2 ^ k := Nat.mul_le_mul_left 2 (by rw [Nat.add_comm]; exact hr)
      _ = 2 ^ (k + 1) := by rw [Nat.pow_succ, Nat.mul_comm]

/-- `b2n` is injective. -/
theorem b2n_inj {a b : Bool} (h : b2n a = b2n b) : a = b := by
  cases a <;> cases b <;> first | rfl | (exfalso; exact absurd h (by decide))

/-- Low-bit recovery (the only half `binEnc_inj` needs): `(b2n c + 2·r) % 2 = b2n c`. -/
theorem split_mod (c : Bool) (r : Nat) : (b2n c + 2 * r) % 2 = b2n c := by
  rw [Nat.mul_comm 2 r, E213.Tactic.NatHelper.add_mul_mod_self_pure (b2n c) 2 r]
  cases c <;> decide

/-- **Binary encoding is injective on windows** — equal codes ⟹ equal windows. -/
theorem binEnc_inj (k : Nat) (f g : Nat → Bool)
    (h : binEnc k f = binEnc k g) : ∀ t, t < k → f t = g t := by
  induction k generalizing f g with
  | zero => intro t ht; exact absurd ht (Nat.not_lt_zero t)
  | succ k ih =>
    have hf : binEnc (k + 1) f = b2n (f 0) + 2 * binEnc k (fun t => f (t + 1)) := rfl
    have hg : binEnc (k + 1) g = b2n (g 0) + 2 * binEnc k (fun t => g (t + 1)) := rfl
    rw [hf, hg] at h
    -- low bits equal
    have hmodf := split_mod (f 0) (binEnc k (fun t => f (t + 1)))
    have hmodg := split_mod (g 0) (binEnc k (fun t => g (t + 1)))
    have hb0 : b2n (f 0) = b2n (g 0) := by
      rw [← hmodf, ← hmodg, h]
    -- high parts equal
    have hf0 : f 0 = g 0 := b2n_inj hb0
    have hhigh : 2 * binEnc k (fun t => f (t + 1)) = 2 * binEnc k (fun t => g (t + 1)) := by
      have h2 := h
      rw [hb0] at h2
      exact E213.Tactic.NatHelper.add_left_cancel_pure h2
    have hrec : binEnc k (fun t => f (t + 1)) = binEnc k (fun t => g (t + 1)) :=
      E213.Tactic.NatHelper.mul_left_cancel_pos (by decide) hhigh
    have ihrec := ih (fun t => f (t + 1)) (fun t => g (t + 1)) hrec
    intro t ht
    cases t with
    | zero => exact hf0
    | succ t => exact ihrec t (Nat.lt_of_succ_lt_succ ht)

/-! ## Phase B — `k`-step determinism + boundedness ⟹ eventually periodic -/

/-- `a` is **`k`-step deterministic**: the value after a length-`k` window is determined by the
    window.  (For a `Bool`-sequence — automatically bounded — this is exactly autonomous
    finite-state generability with memory `k`.) -/
def kStepDet (a : Nat → Bool) (k : Nat) : Prop :=
  ∀ i j, (∀ t, t < k → a (i + t) = a (j + t)) → a (i + k) = a (j + k)

/-- Determinism propagates a window agreement forward forever. -/
theorem window_propagate (a : Nat → Bool) (k i j : Nat) (hdet : kStepDet a k)
    (hbase : ∀ t, t < k → a (i + t) = a (j + t)) : ∀ t, a (i + t) = a (j + t) := by
  have aux : ∀ T t, t < T → a (i + t) = a (j + t) := by
    intro T
    induction T with
    | zero => intro t ht; exact absurd ht (Nat.not_lt_zero t)
    | succ T ihT =>
      intro t ht
      rcases Nat.lt_or_ge t k with htk | hkt
      · exact hbase t htk
      · have hle : t ≤ T := Nat.le_of_lt_succ ht
        have hwin : ∀ s, s < k → a (i + (t - k) + s) = a (j + (t - k) + s) := by
          intro s hs
          have h1 : (t - k) + s < (t - k) + k := Nat.add_lt_add_left hs (t - k)
          rw [E213.Tactic.NatHelper.sub_add_cancel hkt] at h1
          have hih := ihT ((t - k) + s) (Nat.lt_of_lt_of_le h1 hle)
          rwa [← Nat.add_assoc, ← Nat.add_assoc] at hih
        have hd := hdet (i + (t - k)) (j + (t - k)) hwin
        have hidx : ∀ x, (x + (t - k)) + k = x + t := fun x => by
          rw [Nat.add_assoc, E213.Tactic.NatHelper.sub_add_cancel hkt]
        rw [hidx i, hidx j] at hd
        exact hd
  intro t; exact aux (t + 1) t (Nat.lt_succ_self t)

/-- A `Bool`-sequence is **eventually periodic**. -/
def EvPeriodic (a : Nat → Bool) : Prop := ∃ p, 1 ≤ p ∧ ∃ N, ∀ n, N ≤ n → a (n + p) = a n

/-- ★★★ **Morse–Hedlund (the bounded direction).**  A `k`-step-deterministic `Bool`-sequence is
    eventually periodic — finitely many length-`k` windows (`binEnc_lt`), a deterministic shift,
    pigeonhole (`ForwardPeriodicity.pigeonhole_collision`), forward propagation. -/
theorem kStepDet_periodic (a : Nat → Bool) (k : Nat) (hdet : kStepDet a k) : EvPeriodic a := by
  let g : Fin (2 ^ k + 1) → Fin (2 ^ k) :=
    fun t => ⟨binEnc k (fun s => a (t.val + s)), binEnc_lt k _⟩
  obtain ⟨i, hi, j, hj, hij, hcoll⟩ :=
    E213.Lib.Math.DyadicFSM.Forward.ForwardPeriodicity.pigeonhole_collision
      (Nat.lt_succ_self (2 ^ k)) g
  have hval : binEnc k (fun s => a (i + s)) = binEnc k (fun s => a (j + s)) :=
    E213.Lib.Math.DyadicFSM.Forward.ForwardPeriodicity.collTest_imp_val_eq g i j hi hj hcoll
  have hwin0 : ∀ t, t < k → a (i + t) = a (j + t) :=
    binEnc_inj k (fun s => a (i + s)) (fun s => a (j + s)) hval
  have hprop := window_propagate a k i j hdet hwin0
  refine ⟨j - i, E213.Tactic.NatHelper.le_pred_of_succ_le (Nat.succ_le_of_lt hij), i, ?_⟩
  intro n hn
  have ht := hprop (n - i)
  rw [E213.Tactic.NatHelper.add_sub_of_le hn] at ht
  have hj_eq : j + (n - i) = n + (j - i) := by
    have e : (j - i) + i = j := E213.Tactic.NatHelper.sub_add_cancel (Nat.le_of_lt hij)
    calc j + (n - i) = ((j - i) + i) + (n - i) := by rw [e]
      _ = (j - i) + (i + (n - i)) := Nat.add_assoc _ _ _
      _ = (j - i) + n := by rw [E213.Tactic.NatHelper.add_sub_of_le hn]
      _ = n + (j - i) := Nat.add_comm _ _
  rw [hj_eq] at ht
  exact ht.symm

/-! ## Phase C — the autonomous machine over `Int`: aperiodic ⟹ `¬ AutoRec` -/

open E213.Lib.Math.Cauchy.ZeroRunNonHolonomic (AutoRec)

/-- `b2n` is injective into `Int` (`{0,1}` distinct). -/
theorem b2nInt_inj {a b : Bool} (h : ((b2n a : Nat) : Int) = ((b2n b : Nat) : Int)) : a = b := by
  cases a <;> cases b <;> first | rfl | (exfalso; exact absurd h (by decide))

/-- An autonomous finite-state machine over the `{0,1}`-embedding of a `Bool`-sequence forces
    that sequence to be `k`-step deterministic, hence eventually periodic (Phase B). -/
theorem bool_autoRec_periodic (a : Nat → Bool)
    (h : AutoRec (fun n => ((b2n (a n) : Nat) : Int))) : EvPeriodic a := by
  obtain ⟨k, F, hdep, hrec⟩ := h
  have hdet : kStepDet a k := by
    intro i j hwin
    have hwinI : ∀ t, t < k →
        (fun s => ((b2n (a (i + s)) : Nat) : Int)) t
          = (fun s => ((b2n (a (j + s)) : Nat) : Int)) t := by
      intro t ht
      show ((b2n (a (i + t)) : Nat) : Int) = ((b2n (a (j + t)) : Nat) : Int)
      rw [hwin t ht]
    have hF := hdep _ _ hwinI
    have hvals : ((b2n (a (i + k)) : Nat) : Int) = ((b2n (a (j + k)) : Nat) : Int) :=
      (hrec i).trans (hF.trans (hrec j).symm)
    exact b2nInt_inj hvals
  exact kStepDet_periodic a k hdet

/-- ★★★ **Aperiodic ⟹ generated by no autonomous finite-state machine** (Morse–Hedlund,
    contrapositive).  Any non-eventually-periodic `Bool`-sequence — *including dense ones with no
    long runs* (Thue–Morse, Sturmian) — escapes every autonomous finite-state machine.  The
    dense companion to the sparse zero-run / `χ` route.  Feeds
    `ZeroRunNonHolonomic.distinct_next_equal_window_not_autoRec` at the level of the whole class. -/
theorem aperiodic_not_autoRec (a : Nat → Bool) (h : ¬ EvPeriodic a) :
    ¬ AutoRec (fun n => ((b2n (a n) : Nat) : Int)) :=
  fun hauto => h (bool_autoRec_periodic a hauto)

end E213.Lib.Math.Cauchy.MorseHedlund
