import E213.Meta.Int213.PolyIntM
import E213.Meta.Int213.PolyIntMTactic

/-!
# Continued-fraction convergents: the fundamental determinant identity (∅-axiom)

For a sequence of partial quotients `a : Nat → Nat`, the continued-fraction
convergents `pₙ/qₙ` are generated by the two-step recurrences

  p 0 = a 0,   p 1 = a 1 * a 0 + 1,   p (n+2) = a (n+2) * p (n+1) + p n
  q 0 = 1,     q 1 = a 1,             q (n+2) = a (n+2) * q (n+1) + q n.

The **fundamental determinant identity** (unimodularity / Stern–Brocot adjacency
of consecutive convergents):

  ★★★ `p (n+1) * q n − p n * q (n+1) = (−1)^n`   (over `Int`).

Everything is `Nat`-valued, lifted to `Int` for the `(−1)^n` sign.  To avoid
well-founded-recursion non-reduction, the convergent pair is produced by a
window helper `cfWindow : Nat → Int × Int × Int × Int` carrying
`(p n, q n, p (n+1), q (n+1))`, built by structural recursion on `Nat`.

All declarations PURE (∅-axiom).
-/

namespace E213.Lib.Math.NumberTheory.ContinuedFractionConvergents

open E213.Meta.Int213.PolyIntM (powInt powInt_add)
open E213.Meta.Int213 (mul_neg mul_one neg_mul mul_assoc mul_comm mul_sub)

/-- `(−1)^(n+1) = −(−1)^n` over `Int`, with `powInt` the project power.
    Uses the ∅-axiom `Int213` neg/mul lemmas (core `Int.mul_neg` is propext-dirty). -/
theorem powNegOne_succ (n : Nat) : powInt (-1) (n + 1) = - powInt (-1) n := by
  show powInt (-1) n * (-1) = - powInt (-1) n
  rw [mul_neg, mul_one]

/-- **Convergent window**: `cfWindow a n = (p n, q n, p (n+1), q (n+1))`,
    all coordinates lifted to `Int`.  Two-step recurrence packaged as a
    one-step structural recursion on the window. -/
def cfWindow (a : Nat → Nat) : Nat → Int × Int × Int × Int
  | 0 =>
      -- (p 0, q 0, p 1, q 1) = (a0, 1, a1*a0 + 1, a1)
      ((a 0 : Int), 1, (a 1 : Int) * (a 0 : Int) + 1, (a 1 : Int))
  | n + 1 =>
      -- shift window: new (p (n+1), q (n+1), p (n+2), q (n+2))
      let w := cfWindow a n
      (w.2.2.1, w.2.2.2,
        (a (n + 2) : Int) * w.2.2.1 + w.1,
        (a (n + 2) : Int) * w.2.2.2 + w.2.1)

/-- `p n`: numerator of the `n`-th convergent. -/
def cfP (a : Nat → Nat) (n : Nat) : Int := (cfWindow a n).1
/-- `q n`: denominator of the `n`-th convergent. -/
def cfQ (a : Nat → Nat) (n : Nat) : Int := (cfWindow a n).2.1

/-- The window equals `(p n, q n, p (n+1), q (n+1))`: its tail two coords are
    exactly `cfP a (n+1)` and `cfQ a (n+1)`.  By def `cfWindow a (n+1)`'s
    head two coords are the previous window's tail two coords. -/
theorem cfWindow_tail (a : Nat → Nat) (n : Nat) :
    (cfWindow a n).2.2.1 = cfP a (n + 1) ∧ (cfWindow a n).2.2.2 = cfQ a (n + 1) := by
  -- cfP a (n+1) = (cfWindow a (n+1)).1 = (cfWindow a n).2.2.1 by def
  -- cfQ a (n+1) = (cfWindow a (n+1)).2.1 = (cfWindow a n).2.2.2 by def
  exact ⟨rfl, rfl⟩

theorem cfP_tail (a : Nat → Nat) (n : Nat) : (cfWindow a n).2.2.1 = cfP a (n + 1) :=
  (cfWindow_tail a n).1
theorem cfQ_tail (a : Nat → Nat) (n : Nat) : (cfWindow a n).2.2.2 = cfQ a (n + 1) :=
  (cfWindow_tail a n).2

/-- Base values. -/
theorem cfP_zero (a : Nat → Nat) : cfP a 0 = (a 0 : Int) := rfl
theorem cfQ_zero (a : Nat → Nat) : cfQ a 0 = 1 := rfl
theorem cfP_one (a : Nat → Nat) : cfP a 1 = (a 1 : Int) * (a 0 : Int) + 1 := rfl
theorem cfQ_one (a : Nat → Nat) : cfQ a 1 = (a 1 : Int) := rfl

/-- Two-step recurrence for `p`: `p (n+2) = a (n+2) * p (n+1) + p n`. -/
theorem cfP_rec (a : Nat → Nat) (n : Nat) :
    cfP a (n + 2) = (a (n + 2) : Int) * cfP a (n + 1) + cfP a n := by
  -- cfP a (n+2) = (cfWindow a (n+1)).2.2.1   [def: head of cfWindow a (n+2)]
  show (cfWindow a (n + 1)).2.2.1 = (a (n + 2) : Int) * cfP a (n + 1) + cfP a n
  -- (cfWindow a (n+1)).2.2.1 = a(n+2) * (cfWindow a n).2.2.1 + (cfWindow a n).1  [def]
  show (a (n + 2) : Int) * (cfWindow a n).2.2.1 + (cfWindow a n).1
      = (a (n + 2) : Int) * cfP a (n + 1) + cfP a n
  rw [cfP_tail]
  rfl

/-- Two-step recurrence for `q`: `q (n+2) = a (n+2) * q (n+1) + q n`. -/
theorem cfQ_rec (a : Nat → Nat) (n : Nat) :
    cfQ a (n + 2) = (a (n + 2) : Int) * cfQ a (n + 1) + cfQ a n := by
  show (cfWindow a (n + 1)).2.2.2 = (a (n + 2) : Int) * cfQ a (n + 1) + cfQ a n
  show (a (n + 2) : Int) * (cfWindow a n).2.2.2 + (cfWindow a n).2.1
      = (a (n + 2) : Int) * cfQ a (n + 1) + cfQ a n
  rw [cfQ_tail]
  rfl

/-! ## The fundamental determinant identity -/

/-- Algebraic step kernel: from `D n = p(n+1) q n − p n q(n+1)`, the next
    determinant `D (n+1) = p(n+2) q(n+1) − p(n+1) q(n+2)` collapses to `−D n`.

    Substituting the recurrences:
      p(n+2) q(n+1) − p(n+1) q(n+2)
        = (A·p(n+1)+p n)·q(n+1) − p(n+1)·(A·q(n+1)+q n)
        = A·p(n+1)q(n+1) + p n·q(n+1) − A·p(n+1)q(n+1) − p(n+1)·q n
        = p n·q(n+1) − p(n+1)·q n
        = −(p(n+1)·q n − p n·q(n+1)).
    Pure `Int` ring rearrangement (the multiplier `A` cancels). -/
theorem det_step (A P0 Q0 P1 Q1 : Int) :
    (A * P1 + P0) * Q1 - P1 * (A * Q1 + Q0)
      = -(P1 * Q0 - P0 * Q1) := by
  ring_intZ

/-- ★★★ **Fundamental determinant identity** (unimodularity of consecutive
    convergents): `p (n+1) * q n − p n * q (n+1) = (−1)^n` over `Int`. -/
theorem cf_determinant (a : Nat → Nat) (n : Nat) :
    cfP a (n + 1) * cfQ a n - cfP a n * cfQ a (n + 1) = powInt (-1) n := by
  induction n with
  | zero =>
    -- p1 q0 − p0 q1 = (a1 a0 + 1)·1 − a0·a1 = 1 = (−1)^0
    show cfP a 1 * cfQ a 0 - cfP a 0 * cfQ a 1 = powInt (-1) 0
    rw [cfP_one, cfQ_zero, cfP_zero, cfQ_one]
    show ((a 1 : Int) * (a 0 : Int) + 1) * 1 - (a 0 : Int) * (a 1 : Int) = 1
    ring_intZ
  | succ k ih =>
    -- D (k+1) = p(k+2) q(k+1) − p(k+1) q(k+2)
    rw [cfP_rec, cfQ_rec, powNegOne_succ]
    rw [det_step]
    rw [ih]

/-! ## Corollary: coprimality of consecutive convergents

The determinant identity `p(n+1) q n − p n q(n+1) = ±1` is a Bézout
witness, so `gcd(p n, q n) = 1` (over the nonneg `Nat` lifts).  We record
the consequence most directly available over `Int`: any common `Int`
divisor of `p n` and `q n` divides `(−1)^n`, hence divides `1`. -/

/-- `(−1)^n` is a unit: `powInt (-1) n * powInt (-1) n = 1`. -/
theorem powNegOne_sq (n : Nat) : powInt (-1) n * powInt (-1) n = 1 := by
  induction n with
  | zero => rfl
  | succ k ih =>
    rw [powNegOne_succ]
    -- (-x)*(-x) = x*x
    show (- powInt (-1) k) * (- powInt (-1) k) = 1
    rw [neg_mul, mul_neg, Int.neg_neg, ih]

/-- `d ∣ x → d ∣ x * b` (∅-axiom witness, no Mathlib `Dvd` API). -/
private theorem dvd_mul_of_dvd_left {d x : Int} (h : d ∣ x) (b : Int) : d ∣ x * b := by
  obtain ⟨k, hk⟩ := h
  exact ⟨k * b, by rw [hk, mul_assoc]⟩

/-- `d ∣ y → d ∣ a * y` (∅-axiom witness). -/
private theorem dvd_mul_of_dvd_right {d y : Int} (h : d ∣ y) (a : Int) : d ∣ a * y := by
  obtain ⟨k, hk⟩ := h
  refine ⟨a * k, ?_⟩
  rw [hk, ← mul_assoc, mul_comm a d, mul_assoc]

/-- `d ∣ x → d ∣ y → d ∣ x − y` (∅-axiom witness). -/
private theorem dvd_sub' {d x y : Int} (hx : d ∣ x) (hy : d ∣ y) : d ∣ x - y := by
  obtain ⟨j, hj⟩ := hx; obtain ⟨l, hl⟩ := hy
  exact ⟨j - l, by rw [hj, hl, mul_sub]⟩

/-- ★★ **Consecutive convergents are coprime** (Int form): any common
    divisor `d ∣ p n`, `d ∣ q n` divides `1`.  Immediate from the
    determinant Bézout witness `p(n+1)·q n − p n·q(n+1) = (−1)^n` and
    `(−1)^n` a unit. -/
theorem cf_coprime (a : Nat → Nat) (n : Nat) (d : Int)
    (hp : d ∣ cfP a n) (hq : d ∣ cfQ a n) : d ∣ 1 := by
  -- d ∣ (cfP (n+1) * cfQ n) and d ∣ (cfP n * cfQ (n+1)), so d ∣ their diff = (−1)^n
  have hdiff : d ∣ (cfP a (n + 1) * cfQ a n - cfP a n * cfQ a (n + 1)) :=
    dvd_sub' (dvd_mul_of_dvd_right hq _) (dvd_mul_of_dvd_left hp _)
  rw [cf_determinant] at hdiff
  -- d ∣ (−1)^n  and  (−1)^n * (−1)^n = 1  ⇒  d ∣ 1
  have hsq : d ∣ powInt (-1) n * powInt (-1) n := dvd_mul_of_dvd_left hdiff _
  rwa [powNegOne_sq] at hsq

/-! ## Concrete tables -/

/-- All-1s partial quotients `a ≡ 1`: convergents are consecutive Fibonacci
    ratios `1/1, 2/1, 3/2, 5/3, 8/5, …` (the Stern–Brocot path to φ). -/
def ones : Nat → Nat := fun _ => 1

/-- Fibonacci convergent table for `a ≡ 1`:
    `p = 1,2,3,5,8`  and  `q = 1,1,2,3,5`. -/
theorem fib_table :
    cfP ones 0 = 1 ∧ cfQ ones 0 = 1
    ∧ cfP ones 1 = 2 ∧ cfQ ones 1 = 1
    ∧ cfP ones 2 = 3 ∧ cfQ ones 2 = 2
    ∧ cfP ones 3 = 5 ∧ cfQ ones 3 = 3
    ∧ cfP ones 4 = 8 ∧ cfQ ones 4 = 5 := by
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩ <;> decide

/-- Determinant identity holds numerically on the Fibonacci convergents
    at `n = 4`: `p 5 · q 4 − p 4 · q 5 = (−1)^4 = 1`
    (`13·5 − 8·8 = 65 − 64 = 1`). -/
theorem fib_det_smoke :
    cfP ones 5 * cfQ ones 4 - cfP ones 4 * cfQ ones 5 = 1 := by decide

/-- π continued fraction `[3; 7, 15, 1]` ⇒ convergents
    `3/1, 22/7, 333/106, 355/113` (the classic Milü `355/113`). -/
def piCF : Nat → Nat
  | 0 => 3
  | 1 => 7
  | 2 => 15
  | _ => 1

/-- π-convergent table: `3/1, 22/7, 333/106, 355/113`. -/
theorem pi_table :
    cfP piCF 0 = 3 ∧ cfQ piCF 0 = 1
    ∧ cfP piCF 1 = 22 ∧ cfQ piCF 1 = 7
    ∧ cfP piCF 2 = 333 ∧ cfQ piCF 2 = 106
    ∧ cfP piCF 3 = 355 ∧ cfQ piCF 3 = 113 := by
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩ <;> decide

/-- π-convergent determinant smoke at `n = 2`:
    `p 3 · q 2 − p 2 · q 3 = (−1)^2 = 1`  (`355·106 − 333·113 = 37630 − 37629 = 1`). -/
theorem pi_det_smoke :
    cfP piCF 3 * cfQ piCF 2 - cfP piCF 2 * cfQ piCF 3 = 1 := by decide

end E213.Lib.Math.NumberTheory.ContinuedFractionConvergents
