import E213.Lib.Math.Algebra.Icosahedral.CyclotomicFive
import E213.Lib.Math.NumberTheory.DyadicFSM.FibApparitionMod5
import E213.Lib.Math.Analysis.Cauchy.OrbitDimension

/-!
# The shared `ℚ(√5)` morphism — `cp_phase` ⟷ `fibonacci_5adic_valuation`

Two readings of the **single field** `ℚ(√5) = ℚ(φ)` meet at its one ramified
prime `5`:

  * **cp_phase** (`Icosahedral.CyclotomicFive`): `ℚ(√5)` is the golden **real
    subfield** `ℚ(ζ₅)⁺` of the CKM CP-phase tower.  Its generators are the
    Gaussian periods `η₀ = ζ+ζ⁴ = 1/φ`, `η₁ = ζ²+ζ³ = −φ` — the roots of the
    **Gaussian-period polynomial** `gPoly(x) = x² + x − 1`, discriminant `5`
    (`golden_real_subfield`).  The deployment reads this field's value as the
    apex **modulus** `R_u = 1/φ²`.

  * **fibonacci_5adic_valuation** (`DyadicFSM.FibApparitionMod5`): `ℚ(√5)` is
    the **Binet field** of the Fibonacci recurrence, generated by `φ, ψ` — the
    roots of the **Binet polynomial** `bPoly(x) = x² − x − 1`, discriminant `5`.
    The branch reads this field's arithmetic as `ν₅(F_n) = ν₅(n)`, the rank of
    apparition `α(5) = 5` at the ramified place.

The **morphism** that makes these one field object is the involution `x ↦ −x`:

  `bPoly(−x) = (−x)² − (−x) − 1 = x² + x − 1 = gPoly(x)`.

So `gPoly` and `bPoly` are the two `ℚ(√5)`-generators related by negation
(`{φ, ψ}` vs `{−φ, −ψ} = {1/φ−1, …}`); they share discriminant `5`, the same
splitting field `ℚ(√5)`, and the **same ramified prime** `5`, where each
factors as a perfect square mod `5`:

  `bPoly ≡ (x + 2)² mod 5`  (double root `x ≡ 3`),
  `gPoly ≡ (x + 3)² mod 5`  (double root `x ≡ 2`),

and the two double roots are negatives, `3 + 2 ≡ 0 mod 5` — the `x ↦ −x` image.

This is the formalization of the open frontier named in
`research-notes/frontiers/fibonacci_golden_prime_crossdomain.md` (insight 5) and
`theory/essays/synthesis/the_golden_prime.md`: the CP-phase's `ℚ(ζ₅)` reading and
the Fibonacci ramification are **one** `ℚ(√5)` object, with the value `φ` (the
modulus `1/φ²`) and the valuation `ν₅(F_n)` its analytic and `p`-adic faces.

All declarations PURE (the arithmetic skeleton — the polynomial identity over
`ℤ`, the shared discriminant `5`, and the mod-`5` ramification of both faces).
-/

namespace E213.Lib.Math.NumberTheory.GoldenFieldBridge

open E213.Lib.Math.Algebra.Icosahedral.CyclotomicFive (golden_real_subfield)
open E213.Lib.Math.NumberTheory.DyadicFSM.FibApparitionMod5
  (fibMod5 five_dvd_fib_iff rank_apparition_five)

/-! ## §1 — the two golden polynomials and the `x ↦ −x` morphism -/

/-- The **Binet polynomial** `x² − x − 1` (Fibonacci/`ℚ(√5)`, roots `φ, ψ`). -/
def bPoly (x : Int) : Int := x * x - x - 1

/-- The **Gaussian-period polynomial** `x² + x − 1` (`ℚ(ζ₅)⁺`, roots
    `η₀ = 1/φ`, `η₁ = −φ`). -/
def gPoly (x : Int) : Int := x * x + x - 1

/-- ★★★★ **The shared-`ℚ(√5)` morphism `x ↦ −x`.**  The Binet polynomial of the
    Fibonacci field and the Gaussian-period polynomial of `ℚ(ζ₅)⁺` are one
    object under negation:

      `bPoly (−x) = gPoly x`   for all `x : ℤ`.

    The two faces of `ℚ(√5)` — the Fibonacci value `φ` (modulus `1/φ²`) and the
    cyclotomic period `1/φ = ζ+ζ⁴` — are the negation-conjugate generators of
    the same field.  PURE. -/
theorem bPoly_neg_eq_gPoly (x : Int) : bPoly (-x) = gPoly x := by
  show (-x) * (-x) - (-x) - 1 = x * x + x - 1
  ring_intZ

/-- Both golden polynomials have **discriminant `5`** — the golden discriminant,
    the syntactic reason `ℚ(√5)` is the shared field.  `bPoly`: `(−1)² − 4·(−1)
    = 5`; `gPoly`: `1² − 4·(−1) = 5`.  PURE. -/
theorem shared_discriminant_five :
    ((-1 : Int) ^ 2 - 4 * 1 * (-1) = 5)        -- disc(bPoly) = b² − 4ac, b=−1
    ∧ ((1 : Int) ^ 2 - 4 * 1 * (-1) = 5) := by  -- disc(gPoly) = b² − 4ac, b=+1
  decide

/-! ## §2 — both faces ramify at the prime `5` (perfect square mod 5) -/

/-- `bPoly` reduced mod `5`, as a `Nat` residue function: `x² − x − 1 ≡ x² + 4x
    + 4 (mod 5)` (using `−1 ≡ 4`, `−x ≡ 4x`).  Equals `(x + 2)²` identically. -/
def bPolyMod5 (x : Nat) : Nat := (x * x + 4 * x + 4) % 5

/-- `gPoly` reduced mod `5`: `x² + x − 1 ≡ x² + x + 4 (mod 5)`.  Equals
    `(x + 3)²` mod `5`. -/
def gPolyMod5 (x : Nat) : Nat := (x * x + x + 4) % 5

/-- ★★★★ **`5` is ramified in the Fibonacci face.**  `bPoly ≡ (x + 2)² mod 5`
    — a perfect square with the **double root** `x ≡ 3` (`3 + 2 ≡ 0`).  This is
    the `x² − x − 1 ≡ (x − 3)² mod 5` of `FibApparitionMod5`, the collapse of the
    two Binet branches `α ≡ β ≡ 3` that drives `α(5) = 5`.  PURE. -/
theorem bPoly_ramified_mod5 :
    (∀ x, x < 5 → bPolyMod5 x = ((x + 2) * (x + 2)) % 5)   -- perfect square
    ∧ (∀ x, x < 5 → (bPolyMod5 x = 0 ↔ x = 3)) := by        -- double root x ≡ 3
  refine ⟨?_, ?_⟩ <;> decide

/-- ★★★★ **`5` is ramified in the cyclotomic face.**  `gPoly ≡ (x + 3)² mod 5`
    — a perfect square with the **double root** `x ≡ 2`.  The Gaussian periods
    `η₀, η₁` collapse mod `5` exactly as the Binet branches do.  PURE. -/
theorem gPoly_ramified_mod5 :
    (∀ x, x < 5 → gPolyMod5 x = ((x + 3) * (x + 3)) % 5)   -- perfect square
    ∧ (∀ x, x < 5 → (gPolyMod5 x = 0 ↔ x = 2)) := by        -- double root x ≡ 2
  refine ⟨?_, ?_⟩ <;> decide

/-- ★★★★ **The two double roots are negatives mod `5`.**  Fibonacci's `3` and
    the cyclotomic `2` satisfy `3 + 2 ≡ 0 mod 5` — the `x ↦ −x` morphism of §1
    read at the ramified prime: the same single ramification of `ℚ(√5)`, seen
    from the two generators.  PURE. -/
theorem ramified_roots_negate : (3 + 2) % 5 = 0 := by decide

/-! ## §3 — capstone: one field, two faces, one ramified prime -/

/-- ★★★★★★ **The shared-`ℚ(√5)` morphism, assembled.**  The CP-phase reading
    (`cp_phase` / `CyclotomicFive`: golden real subfield `ℚ(ζ₅)⁺ = ℚ(√5)`,
    period polynomial `x²+x−1`, modulus `1/φ²`) and the Fibonacci reading
    (`fibonacci_5adic_valuation` / `FibApparitionMod5`: Binet field `ℚ(√5)`,
    polynomial `x²−x−1`, valuation `ν₅(F_n)`, rank `α(5) = 5`) are **one field
    object**:

      1. **one morphism** `x ↦ −x` identifying the two generators
         (`bPoly (−x) = gPoly x`);
      2. **one discriminant** `5` (both polynomials), hence the one field `ℚ(√5)`;
      3. **one ramified prime** `5` — each face a perfect square mod `5`
         (double roots `3`, `2`), the two roots negatives (`3 + 2 ≡ 0`);
      4. the Fibonacci face's ramified signature at `5`: `α(5) = 5`
         (`rank_apparition_five`), `5 ∣ F_n ⟺ 5 ∣ n` (`five_dvd_fib_iff`);
      5. the cyclotomic face's golden subfield, disc `5` (`golden_real_subfield`).

    The value `φ` (the modulus `R_u = 1/φ²`) and the valuation `ν₅(F_n)` are the
    analytic and `5`-adic faces of this single ramified `ℚ(√5)`.  PURE. -/
theorem shared_golden_field_morphism :
    -- (1) the morphism x ↦ −x ties the two generators
    (∀ x : Int, bPoly (-x) = gPoly x)
    -- (2) one discriminant 5 (both faces)
    ∧ ((-1 : Int) ^ 2 - 4 * 1 * (-1) = 5 ∧ (1 : Int) ^ 2 - 4 * 1 * (-1) = 5)
    -- (3) one ramified prime 5: double roots 3 (Binet), 2 (cyclotomic), negatives
    ∧ ((∀ x, x < 5 → (bPolyMod5 x = 0 ↔ x = 3))
        ∧ (∀ x, x < 5 → (gPolyMod5 x = 0 ↔ x = 2))
        ∧ (3 + 2) % 5 = 0)
    -- (4) the Fibonacci face: α(5) = 5, the rank at the ramified prime
    ∧ (fibMod5 5 = 0 ∧ ∀ m, m < 5 → 0 < m → fibMod5 m ≠ 0)
    -- (5) the cyclotomic face: golden real subfield, disc 5
    ∧ ((1 : Int) ^ 2 + 4 * 1 = 5) :=
  ⟨bPoly_neg_eq_gPoly,
   shared_discriminant_five,
   ⟨(bPoly_ramified_mod5).2, (gPoly_ramified_mod5).2, ramified_roots_negate⟩,
   rank_apparition_five,
   (golden_real_subfield).1⟩

end E213.Lib.Math.NumberTheory.GoldenFieldBridge
