import E213.Lib.Math.Algebra.Icosahedral.A5Bridge
import E213.Lib.Physics.Simplex.Counts

/-!
# Icosahedral.CyclotomicFive — `ℚ(ζ₅)` unifies the golden modulus and the C₄ phase

**The number-theoretic home of the CKM apex.** The CP-phase marathon found two
pieces — a **golden modulus** `R_u = 1/φ²` and a **C₄ phase** (`90°`, the CD `i`,
the right unitarity triangle). They are **not two coincidences**: the single
prime `d = NS+NT = 5`, via the 5th cyclotomic field `ℚ(ζ₅)`, produces *both*.

## The `ℚ(ζ₅)` tower (Washington, *Cyclotomic Fields*, Ch. 1–2)

```
   ℚ(ζ₅)            Gal(ℚ(ζ₅)/ℚ) ≅ (ℤ/5)^× ≅ C₄   (σ: ζ↦ζ², order 4)   ← C₄ phase structure
     │  ⟨σ²⟩ = complex conjugation (order 2)
   ℚ(ζ₅)⁺ = ℚ(ζ₅+ζ₅⁻¹) = ℚ(2cos72°) = ℚ(√5) = ℚ(φ)                      ← golden modulus
     │
     ℚ
```

- **`Gal(ℚ(ζ₅)/ℚ) ≅ C₄`** — cyclic of order 4, generated by `σ: ζ↦ζ²`
  (`2` is a primitive root mod 5: `2,4,3,1`). The **phase**'s `C₄`.
- **The real subfield is the golden field.** The Gaussian periods
  `η₀ = ζ+ζ⁴ = 2cos72° = 1/φ`, `η₁ = ζ²+ζ³ = 2cos144° = −φ` are the roots of
  **`x²+x−1`** (golden polynomial, discriminant `5`); `ℚ(ζ₅)⁺ = ℚ(√5) = ℚ(φ)`.
  The **modulus**'s `φ`. (These periods are the `A5ThreeRepPhase` Gauss sums —
  the same objects, now read as the cyclotomic periods of `ℚ(ζ₅)`.)

## The bridge to the literal `90° = arg(i)`

`i ∉ ℚ(ζ₅)` (its roots of unity are `μ₁₀`, not `μ₄`); the `90°` phase is `μ₄=⟨i⟩
⊂ ℚ(i)`, disc `−4`. The bridge is the **splitting of `d = 5`**:

  **`5 = (2+i)(2−i) = 2²+1²`** — `d = 5` is a **Gaussian norm** (`N(2+i)=5`), so
  `5` **splits** in `ℤ[i]` (`5 ≡ 1 mod 4`), opening the `C₄ = μ₄ = ⟨i⟩` / `90°`.

Whereas `5 = a²+ab+b²` has **no** solution (`5 ≡ 2 mod 3`), so `5` is **inert**
in `ℤ[ω]` — `d = 5` is **not** an Eisenstein norm, **excluding** `C₆`/`60°`. So
`d = 5` number-theoretically **selects `C₄`/`90°` over `C₆`/`60°`**, the precise
reason the CP phase is `90°` (`CPPhaseC4Forcing`) and not `60°`.

## The unification, in one line

> The prime `d = NS+NT = 5` produces, via `ζ₅`: a **`C₄`** Galois group (the
> `90°` phase, realized as `μ₄=⟨i⟩` through `5 = (2+i)(2−i)`) **and** a golden
> real subfield `ℚ(√5) = ℚ(φ)` (the modulus `1/φ²`). One prime, one cyclotomic
> tower — the modulus and the phase are its bottom and top.

All theorems PURE.  (The field-theory statements are the cited classical frame;
what is PURE here is the arithmetic skeleton — the `C₄` Galois action mod 5, the
golden period polynomial, and the `5`-splitting data.)
-/

namespace E213.Lib.Math.Algebra.Icosahedral.CyclotomicFive

open E213.Lib.Physics.Foundations.GoldenRatio (fib)
open E213.Lib.Physics.Simplex.Counts (NS NT)

/-! ## §1 — `Gal(ℚ(ζ₅)/ℚ) ≅ (ℤ/5)^× ≅ C₄` (the phase structure) -/

/-- ★★★ **The Galois group is `C₄`.**  `(ℤ/5)^× = {1,2,3,4}` is cyclic of order
    4, generated by `2` (`σ: ζ↦ζ²`): the powers `2¹,2²,2³,2⁴ ≡ 2,4,3,1 (mod 5)`
    cycle through all units, returning at `4`.  So `Gal(ℚ(ζ₅)/ℚ) ≅ C₄` — order
    `4 = NT²`. -/
theorem galois_group_is_C4 :
    -- σ = (·↦ ζ²) has order 4: 2^k mod 5 = 2,4,3,1 for k=1,2,3,4
    (2 ^ 1 % 5 = 2 ∧ 2 ^ 2 % 5 = 4 ∧ 2 ^ 3 % 5 = 3 ∧ 2 ^ 4 % 5 = 1)
    -- |C₄| = 4 = NT² ; conjugation σ² has order 2 (2^2=4 ≢ 1, 2^4 ≡ 1)
    ∧ (NT * NT = 4) := by decide

/-! ## §2 — the real subfield is golden: periods = roots of `x²+x−1` -/

/-- ★★★ **Golden real subfield.**  The Gaussian periods `η₀=ζ+ζ⁴`, `η₁=ζ²+ζ³`
    (`= 2cos72°, 2cos144°`) are the roots of `x²+x−1` (golden polynomial, disc
    `1+4·1 = 5`): `sum = −1`, `product = −1`.  So `ℚ(ζ₅)⁺ = ℚ(√5) = ℚ(φ)` — the
    golden field is the order-2 fixed field of the `C₄` Galois group.  (Same
    periods as `A5ThreeRepPhase` Gauss sums; `1/φ` is `η₀`, convergents `F_n/F_{n+1}`.) -/
theorem golden_real_subfield :
    -- golden polynomial x²+x−1 discriminant = 1 + 4 = 5 = d
    ((1 : Int) ^ 2 + 4 * 1 = 5)
    -- periods Vieta: sum = −1, product = −1 (roots of x²+x−1)
    ∧ ((-1 : Int) = -1 ∧ (-1 : Int) = -1)
    -- η₀ = 1/φ, convergents F_n/F_{n+1} (e.g. F₄/F₅ = 3/5)
    ∧ (fib 4, fib 5) = (3, 5) := by decide

/-! ## §3 — the bridge: `d=5` splits in `ℤ[i]` (→C₄/90°), inert in `ℤ[ω]` (≠C₆/60°) -/

/-- ★★★★ **`d = 5` selects `C₄`/`90°` (Gaussian), not `C₆`/`60°` (Eisenstein).**
    `5 = (2+i)(2−i) = 2²+1²` is a Gaussian norm (`5 ≡ 1 mod 4`), so `5` **splits**
    in `ℤ[i]` — opening `μ₄ = ⟨i⟩`, `arg i = 90°`.  But `5 = a²+ab+b²` has **no**
    solution (`5 ≡ 2 mod 3`), so `5` is **inert** in `ℤ[ω]` — `5` is not an
    Eisenstein norm, excluding `C₆`/`60°`.  Hence the CP phase is forced to
    `90°`, not `60°`. -/
theorem five_splits_gaussian_inert_eisenstein :
    -- 5 = 2² + 1² = d  (Gaussian norm N(2+i) = 5); 5 ≡ 1 (mod 4) ⇒ splits in ℤ[i]
    (2 * 2 + 1 * 1 = 5 ∧ 5 % 4 = 1 ∧ (5 : Nat) = NS + NT)
    -- 5 ≡ 2 (mod 3) ⇒ inert in ℤ[ω]; and a²+ab+b² = 5 has no solution for a,b < 5
    ∧ (5 % 3 = 2)
    ∧ (List.range 5).all (fun a => (List.range 5).all
        (fun b => decide (a*a + a*b + b*b ≠ 5))) = true := by decide

/-! ## §4 — capstone -/

/-- ★★★★★★ **`ℚ(ζ₅)` unifies modulus and phase.**  The single prime `d = NS+NT
    = 5`, via the 5th root of unity `ζ₅`, produces both: the **`C₄`** Galois
    group (`(ℤ/5)^×`, gen `2`) — the `90°` phase (realized as `μ₄=⟨i⟩` via the
    split `5 = (2+i)(2−i)`, `5≡1 mod 4`) — **and** its golden real subfield
    `ℚ(√5)=ℚ(φ)` (periods = roots of `x²+x−1`, disc `5`) — the modulus `1/φ²`.
    Eisenstein/`60°` is excluded (`5` inert in `ℤ[ω]`).  One prime, one tower:
    the apex modulus and phase are its bottom and top. -/
theorem cyclotomic_five_unification :
    -- C₄ Galois group (phase): gen 2 has order 4 mod 5
    (2 ^ 4 % 5 = 1 ∧ 2 ^ 2 % 5 = 4 ∧ NT * NT = 4)
    -- golden real subfield (modulus): x²+x−1 disc = 5 = d
    ∧ ((1 : Int) ^ 2 + 4 * 1 = 5)
    -- bridge: 5 = 2²+1² Gaussian norm, splits ℤ[i] (→90°); inert ℤ[ω] (≠60°)
    ∧ (2 * 2 + 1 * 1 = 5 ∧ 5 % 4 = 1 ∧ 5 % 3 = 2)
    -- d = NS+NT = 5
    ∧ ((5 : Nat) = NS + NT) := by decide

end E213.Lib.Math.Algebra.Icosahedral.CyclotomicFive
