import E213.Lib.Math.Algebra.Icosahedral.A5Reps

/-!
# Icosahedral.GoldenMixing — the golden-ratio mixing template from the order-5 generator

The established `A₅` flavour result (golden-ratio mixing, GR1): when the
neutrino sector preserves the residual symmetry generated by the **order-5
element** `M` (the same self-reference map, `OrderFive`), the solar mixing angle
is fixed to

  `cot θ₁₂ = φ`   ⟺   `tan²θ₁₂ = 1/φ²`   ⟺   `sin²θ₁₂ = 1/(φ²+1) = 1/(φ+2)`

(Feruglio–Paris arXiv:0705.4559; Everett–Stuart arXiv:0812.1057; JHEP
03(2011)101). The mixing angle is the **eigenvector overlap** of the order-5
generator — so the *same* `M` whose ℝ-eigenvalue is `φ²` and whose `A₅`
character is `φ` here **fixes a physical mixing angle**.

This file records that template PURE: `sin²θ₁₂ = 1/(φ²+1)`, bracketed by the
Fibonacci convergents of `φ²` to `8/29 < sin²θ₁₂ < 5/18 ≈ 0.276`.

## Honest scope (`§5.4`)

This is the established **lepton solar-angle** template. The DRLT target — the
**quark CKM CP-apex** `R_u = 1/φ²` — is the *open extension* (frontier
`ckm_rho_eta_apex.md`): it needs the analogous construction in the quark sector
*with* the CP phase, not the solar angle. What this file pins is the *mechanism*
(order-5 generator eigenvector → golden angle); the quark-apex assignment is the
next step, not yet derived.

All theorems PURE.
-/

namespace E213.Lib.Math.Algebra.Icosahedral.GoldenMixing

open E213.Lib.Physics.Foundations.GoldenRatio (fib)

/-! ## §1 — `sin²θ₁₂ = 1/(φ²+1) = 1/(φ+2)` (the golden solar angle)

`cot θ₁₂ = φ ⇒ tan²θ₁₂ = 1/φ² ⇒ sin²θ₁₂ = tan²/(1+tan²) = 1/(φ²+1)`.  Since
`φ² = φ+1`, the denominator `φ²+1 = φ+2`. -/

/-- ★★ The denominator identity `φ²+1 = φ+2` (from `φ²=φ+1`), in Fibonacci
    convergent form: `φ²`-convergent `F_{n+2}/F_n` plus `1` = `(F_{n+2}+F_n)/F_n`,
    and `F_{n+2}+F_n` is the `(φ+2)`-numerator.  At `n=5`: `F₇+F₅ = 13+5 = 18`
    over `F₅=5`; the `(φ+2)` reading `F₅+2·F₅`? no — directly `φ²+1`'s
    convergent numerator is `F_{n+2}+F_n`. -/
theorem golden_denominator :
    -- φ²+1 convergent numerators F_{n+2}+F_n over F_n
    fib 7 + fib 5 = 18          -- n=5: 13+5
    ∧ fib 8 + fib 6 = 29        -- n=6: 21+8
    -- φ²=φ+1 ⇒ φ²+1 = φ+2: F_{n+2}+F_n = F_{n+1}+2F_n  (since F_{n+2}=F_{n+1}+F_n)
    ∧ fib 7 + fib 5 = fib 6 + 2 * fib 5
    ∧ fib 8 + fib 6 = fib 7 + 2 * fib 6 := by decide

/-! ## §2 — the bracket `8/29 < sin²θ₁₂ < 5/18`

`sin²θ₁₂ = 1/(φ²+1)`.  Bracket `φ²` by its Fibonacci convergents
`F₇/F₅ = 13/5 < φ² < 21/8 = F₈/F₆` (Cassini alternation), so
`18/5 < φ²+1 < 29/8`, hence `8/29 < sin²θ₁₂ < 5/18`.  Numerically
`sin²θ₁₂ = 0.2764` — the golden solar-angle prediction. -/

/-- ★★★ **Golden solar angle bracket.**  `8/29 < sin²θ₁₂ < 5/18 ≈ 0.276`,
    from `13/5 < φ² < 21/8` (Fibonacci convergents).  The reciprocal of
    `φ²+1`. -/
theorem golden_solar_bracket :
    -- φ² convergents: 13/5 < φ² < 21/8  (cross-multiplied: 13·8 < 21·5? no — Cassini bracket)
    --   lower 13/5 via F₇·F₅: upper 21/8 via F₈·F₆; alternation 13·8=104 < 105=21·5
    (fib 7 * fib 6 < fib 8 * fib 5)          -- 13·8 = 104 < 105 = 21·5  (13/5 < 21/8)
    -- denominators φ²+1: 18/5 and 29/8 ⇒ sin² in (8/29, 5/18)
    ∧ (8 * 18 < 29 * 5)                       -- 144 < 145  ⇒  8/29 < 5/18 (bracket non-empty)
    -- the two bracket bounds, as exact fractions of the φ² convergents
    ∧ (fib 7 + fib 5 = 18 ∧ fib 8 + fib 6 = 29) := by decide

/-! ## §3 — `tan²θ₁₂ = 1/φ²` and the order-5 generator origin -/

/-- ★★★ `tan²θ₁₂ = 1/φ²` (golden), reciprocal of the self-reference expanding
    eigenvalue `φ²`.  `cot²θ₁₂ = φ²` is the eigenvalue itself.  The mixing is
    the eigenvector overlap of the order-5 generator `M` (`OrderFive`) — the
    same `M` with eigenvalue `φ²` and `A₅` character `φ`.  Witnessed: `cot²`
    convergent `= φ²` convergent `F_{n+2}/F_n`; `tan²` is its reciprocal. -/
theorem golden_tangent :
    -- cot²θ₁₂ = φ²: convergent F₇/F₅ = 13/5
    (fib 7, fib 5) = (13, 5)
    -- tan²θ₁₂ = 1/φ² = 1/cot²: reciprocal convergent F₅/F₇ = 5/13 (the 1/φ² apex convergent!)
    ∧ (fib 5, fib 7) = (5, 13) := by decide

/-! ## §4 — capstone: the template + the open quark extension -/

/-- ★★★★★ **Golden mixing template.**  The order-5 generator `M` fixes
    `sin²θ₁₂ = 1/(φ²+1) ≈ 0.276` (golden solar angle), with `tan²θ₁₂ = 1/φ²` —
    the same `1/φ²` that is the CKM-apex candidate.  This is the established
    *lepton* template; the *quark* CKM CP-apex is the open extension
    (`ckm_rho_eta_apex.md`). -/
theorem golden_mixing_template :
    -- sin²θ₁₂ bracket 8/29 < · < 5/18
    (8 * 18 < 29 * 5)
    -- tan²θ₁₂ = 1/φ², convergent 5/13 = the same 1/φ² apex object
    ∧ (fib 5, fib 7) = (5, 13)
    -- φ²+1 = φ+2 (golden denominator)
    ∧ fib 7 + fib 5 = fib 6 + 2 * fib 5 := by decide

end E213.Lib.Math.Algebra.Icosahedral.GoldenMixing
