import E213.Meta.SelfRecognising
import E213.Lib.Math.CayleyDickson.ZOmega
import E213.Lib.Math.CayleyDickson.ZOmegaDomain
import E213.Meta.Tactic.DeriveConjugationCodomain

/-!
# `ZOmega` (Eisenstein integers ℤ[ω]) as `ConjugationCodomain`

Third concrete witness — after `ZI = ℤ[i]` and `Z2 = ℤ[√-2]` —
that the three-tier codomain spec (`CommBinaryCodomain` +
`NonVanishingCodomain` + `ConjugationCodomain`, formerly the
"R1–R4" set in the deprecated R1–R5 judgment-game frame) admits
more than one ring up to isomorphism.

ℤ[ω] is the ring of Eisenstein integers, with ω a primitive cube
root of unity.  Its norm `a² - ab + b²` has a cross-term — the
structural feature this witness adds vs. the diagonal `a² + D·b²`
norms of ZI / Z2 / ZSqrt.

Generated by the `derive_conjugation_codomain` elab using bases
`Omega = ω` and `Omega2 = ω²`.
-/

open E213.Tactic
open E213.Lib.Math.CayleyDickson.ZOmega
open E213.Lib.Math.CayleyDickson.ZOmega.ZOmega

derive_conjugation_codomain ZOmega with_bases Omega Omega2
