"""Geometric rendering of the difference-Lens self-pointing.

Mingu Jeong's sketch: every object IS the (directed) relation of two distinct
objects.  Start with a, b; the relation of (a,b) is a new object c; the
relations of (c,a),(c,b) are d,e; and so on.  Each new object pairs with every
existing one, so the population grows hyper-exponentially and its cardinality
is left undetermined ("how infinite, we don't know").

In 213 terms this is the difference-Lens (06_lens_readings.md §6.7): an object
is the count-Lens on a *directed* pair, magnitude Nat-style, sign Bool-style
pair-swap.  Directedness means relation(x,y) != relation(y,x) — the two are
negatives of one another — so the geometric image of a relation sits on one
*side* of the segment, not at its midpoint.

Two panels:
  (1) the labelled relation graph for the first generations (a..q...),
      every node drawn with the two parent-edges that define it;
  (2) the geometric limit: iterate "the relation of (x,y) is a new point off
      the segment, then recurse on (x, p) and (p, y)" — a directed de Rham
      (Levy) curve — coloured by recursion depth.  This is the self-similar
      shape the unbounded self-pointing converges to.

Run:  python3 research-notes/geometric/object_as_relation.py
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.collections import LineCollection


# ----------------------------------------------------------------------------
# Panel 1 — the labelled relation graph (faithful to the sketch)
# ----------------------------------------------------------------------------
# parents[child] = (x, y): the new object `child` IS the directed relation x->y.
# Generated by: process objects in birth order; the object being processed
# spawns relation(self, other) with every object that exists at that moment.
#   process a (others b)            -> c
#   process c (others a,b)          -> d=(c,a), e=(c,b)
#   process d (others a,b,c,e)      -> f,g,h,i
#   process e (others a,b,c,d,f..i) -> j,k,l,m,n,o,p,q
# (b is the second seed; relation(a,b)=relation(b,a)=c at the undirected seed.)

SEEDS = ["a", "b"]
parents = {
    "c": ("a", "b"),
    "d": ("c", "a"), "e": ("c", "b"),
    "f": ("d", "a"), "g": ("d", "b"), "h": ("d", "c"), "i": ("d", "e"),
    "j": ("e", "a"), "k": ("e", "b"), "l": ("e", "c"), "m": ("e", "d"),
    "n": ("e", "f"), "o": ("e", "g"), "p": ("e", "h"), "q": ("e", "i"),
}

# birth generation of every object (seeds = 0)
gen = {"a": 0, "b": 0}
for child, (x, y) in parents.items():
    gen[child] = max(gen[x], gen[y]) + 1
maxgen = max(gen.values())

# radial layout: ring radius = generation, objects spread by angle within a ring
by_gen = {}
for obj, g in gen.items():
    by_gen.setdefault(g, []).append(obj)
# keep a stable, birth-ordered sweep so parent/child stay angularly near
order = SEEDS + list(parents.keys())
for g in by_gen:
    by_gen[g].sort(key=order.index)

# layered DAG: generation = vertical level, birth order spreads horizontally
pos = {}
WIDTH = 12.0
for g, objs in by_gen.items():
    n = len(objs)
    xs = ([0.0] if n == 1 else np.linspace(-WIDTH / 2, WIDTH / 2, n))
    for obj, x in zip(objs, xs):
        pos[obj] = (float(x), float(g) * 1.7)


def draw_graph(ax):
    cmap = plt.get_cmap("viridis")
    # edges: each object -> its two defining parents
    for child, (x, y) in parents.items():
        cx, cy = pos[child]
        col = cmap(gen[child] / maxgen)
        for px, py in (pos[x], pos[y]):
            ax.annotate(
                "", xy=(cx, cy), xytext=(px, py),
                arrowprops=dict(arrowstyle="-", color=col, lw=1.1, alpha=0.55),
            )
    # nodes
    for obj, (x, y) in pos.items():
        g = gen[obj]
        col = "0.15" if g == 0 else cmap(g / maxgen)
        ax.scatter([x], [y], s=620 if g == 0 else 430, color=col,
                   edgecolors="white", linewidths=1.4, zorder=3)
        ax.text(x, y, obj, ha="center", va="center", color="white",
                fontsize=12 if g == 0 else 10, fontweight="bold", zorder=4)
    ax.set_title(
        "object = the directed relation of two objects\n"
        r"$a,b \to c \to d,e \to f..q \to \cdots$  (each node = its two parents)",
        fontsize=12)
    ax.set_aspect("auto")
    ax.margins(0.08)
    ax.axis("off")


# ----------------------------------------------------------------------------
# Panel 2 — the geometric limit (directed de Rham / Levy curve)
# ----------------------------------------------------------------------------
# relation(x, y) = x + (y - x) * w, with complex w = 1/2 + s*i.
# Im(w) != 0 puts the relation off the segment -> relation(x,y) != relation(y,x):
# the directedness / sign of the difference-Lens, made geometric.
# Recurse on (x, p) and (p, y); the birth points trace a self-similar set.

W = 0.5 + 0.5j  # Levy C-curve constant


def levy_points(x, y, depth, births):
    """Return polyline points; record each relation-birth with its depth."""
    if depth == 0:
        return [x, y]
    p = x + (y - x) * W
    births.append((p, depth))
    left = levy_points(x, p, depth - 1, births)
    right = levy_points(p, y, depth - 1, births)
    return left[:-1] + right


def draw_limit(ax, depth=14):
    births = []
    pts = levy_points(0 + 0j, 1 + 0j, depth, births)
    xs = np.array([z.real for z in pts])
    ys = np.array([z.imag for z in pts])

    # the curve, coloured along its length
    seg = np.stack([np.column_stack([xs[:-1], ys[:-1]]),
                    np.column_stack([xs[1:], ys[1:]])], axis=1)
    lc = LineCollection(seg, cmap="magma",
                        array=np.linspace(0, 1, len(seg)), lw=0.5)
    ax.add_collection(lc)

    # scatter early-generation birth points, coloured by birth depth
    early = [(p, d) for p, d in births if d >= depth - 6]
    if early:
        bx = [p.real for p, d in early]
        by = [p.imag for p, d in early]
        bc = [depth - d for p, d in early]
        ax.scatter(bx, by, c=bc, cmap="viridis", s=18,
                   edgecolors="white", linewidths=0.3, zorder=3)
    # the two seeds
    ax.scatter([0, 1], [0, 0], s=90, color="0.1",
               edgecolors="white", linewidths=1.2, zorder=4)
    ax.text(0, 0, "a", ha="right", va="top", fontsize=11, fontweight="bold")
    ax.text(1, 0, "b", ha="left", va="top", fontsize=11, fontweight="bold")

    ax.set_title(
        "the limit shape of unbounded self-pointing\n"
        r"relation$(x,y)=x+(y-x)\,w$, recurse  —  directed (sign) $\Rightarrow$ off-segment",
        fontsize=12)
    ax.set_aspect("equal")
    ax.autoscale()
    ax.margins(0.05)
    ax.axis("off")


def main():
    fig, axes = plt.subplots(1, 2, figsize=(16, 8))
    fig.patch.set_facecolor("white")
    draw_graph(axes[0])
    draw_limit(axes[1])

    # population-explosion annotation (objects born when each node fans out)
    counts = "objects: 2 → +1 → +2 → +4 → +8 → ⋯  (cardinality undetermined)"
    fig.text(0.5, 0.035, counts, ha="center", fontsize=11, color="0.3")

    fig.suptitle("213 difference-Lens: an object IS the relation of two distinct objects",
                 fontsize=14, fontweight="bold")
    fig.tight_layout(rect=[0, 0.06, 1, 0.96])
    out = "research-notes/geometric/object_as_relation.png"
    fig.savefig(out, dpi=150, facecolor="white")
    print("wrote", out)


if __name__ == "__main__":
    main()
