import E213.Lib.Math.Analysis.Cauchy.DepthCeilingResidue
import E213.Lib.Math.NumberSystems.Real213.RateStratification

/-!
# DepthOverflowDuality — the diagonalisation residue and the completeness-break are one operation

Two facts about the resolution tower sit on opposite sides of the usual
analysis / logic division:

  * **Logical (`DepthCeilingResidue`).**  Naming "the whole tower of reference
    levels" produces the diagonal `diag f i = f i i + 1`, which is *not* any level
    `f i` of the family it summarises (`diag_not_in_seq`) — the Cantor residue,
    `cantor_general` one scale up.
  * **Analytic (`RateStratification`).**  A convergent presentation completes when its
    cross-determinant `W` stays below the denominator quantum at every layer; where
    `W` overflows that quantum, `(i+1)·d_{i+1} < W_i`, domination breaks
    (`overtake_breaks_layer`) — the coordinate mismatch where completeness fails.

This file shows the two are **readings of one finite operation**: at the index built
to contain it, a constructed value strictly exceeds the closing bound — it **overflows
by the irreducible unit `1`**.  `Overflow bound val i := bound i < val i` is, by `Nat`,
exactly `bound i + 1 ≤ val i` (`overflow_is_unit_surplus`): the surplus is the unit,
the count-Lens residue of one distinguishing.  Then:

  * `overflow_escapes` — overflow ⟹ the value is no level of the family (the diagonal
    reading; recovers `diag_not_in_seq` as `diag_escapes_via_overflow`);
  * `overflow_breaks` — overflow ⟹ domination breaks at that layer (the divergence
    reading; this is `overtake_breaks_layer`);
  * ★★★ `overflow_dual_reading` — both at once.  Neither reading is privileged; the
    overflow is the same surplus read at two scales.  The tie to the pointing residue
    is `DepthCeilingResidue.ceiling_residue_is_pointing_residue`: the unit-surplus that
    escapes/breaks here is the surplus that `Object1` leaves outside its image.

The structural content is a **unit generator**, not a hidden adjunction:
`minOverflow bound = bound + 1` is the pointwise-least overflow (`least_overflow`),
generated by `Nat.succ`.  The two readings are *not* symmetric — the diagonal
*achieves* this floor unconditionally (`diag_is_minOverflow`), the completeness-break
only *exceeds* it and only when `W` overflows `d`.  The shared stability is honest:
overflow is monotone in the value (`overflow_mono_val`) and shift-invariant
(`overflow_shift`), so these deformations preserve both readings at once.

So the limit of constructive completeness (where `Htel` breaks) and the surplus of
pointing (the diagonalisation residue) are not two phenomena to be reconciled across a
logic/analysis divide — they are one overflow, read once as "escapes the family" and
once as "breaks the bound".  The tower has no top because the unit surplus is always
available to overflow the next bound; that top-lessness is the residue
(`seed/AXIOM/05_no_exterior.md`: pointing has no exterior).

All zero-axiom.
-/

namespace E213.Lib.Math.Analysis.Cauchy.DepthOverflowDuality

open E213.Lib.Math.Analysis.Cauchy.DepthCeilingResidue (diag diag_exceeds)
open E213.Lib.Math.NumberSystems.Real213.RateStratification (Dominates overtake_breaks_layer)

/-! ## §1 — the shared operation: strict overflow at the diagonal index -/

/-- **Diagonal overflow.**  At index `i`, the constructed value `val i` strictly
    exceeds the closing bound `bound i`.  This is the single finite operation under
    both the diagonalisation residue and the completeness-break. -/
def Overflow (bound val : Nat → Nat) (i : Nat) : Prop := bound i < val i

/-- **Overflow is a unit surplus.**  `Overflow bound val i` is, by `Nat`'s definition
    of `<`, exactly `bound i + 1 ≤ val i` — the bound exceeded by *at least the
    irreducible unit `1`* (the count-Lens residue of one distinguishing). -/
theorem overflow_is_unit_surplus (bound val : Nat → Nat) (i : Nat) :
    Overflow bound val i ↔ bound i + 1 ≤ val i := Iff.rfl

/-! ## §2 — the logical reading: overflow escapes the family (the residue) -/

/-- ★★★ **Overflow escapes the family.**  A value that overflows the diagonal bound
    `i ↦ f i i` at every index cannot equal any level `f i` of the family — it escapes
    the enumeration.  This is the diagonal/residue reading of overflow. -/
theorem overflow_escapes (f : Nat → Nat → Nat) (val : Nat → Nat)
    (hov : ∀ i, Overflow (fun i => f i i) val i) (i : Nat) : val ≠ f i := by
  intro hi
  have he : val i = f i i := congrFun hi i
  have hlt : f i i < val i := hov i
  rw [he] at hlt
  exact Nat.lt_irrefl _ hlt

/-- The Cantor diagonal `diag f` overflows the bound `i ↦ f i i` with surplus exactly
    the unit `1` (`diag f i = f i i + 1`). -/
theorem diag_is_overflow (f : Nat → Nat → Nat) (i : Nat) :
    Overflow (fun i => f i i) (diag f) i :=
  diag_exceeds f i

/-- `diag_not_in_seq` recovered as a pure instance of `overflow_escapes`: the
    canonical (unit-surplus) overflow escapes the family. -/
theorem diag_escapes_via_overflow (f : Nat → Nat → Nat) (i : Nat) : diag f ≠ f i :=
  overflow_escapes f (diag f) (diag_is_overflow f) i

/-! ## §3 — the analytic reading: overflow breaks domination (¬Htel) -/

/-- ★★★ **Overflow breaks the bound.**  A cross-determinant `W` that overflows the
    denominator quantum `(i+1)·d_{i+1}` at layer `i ≥ 1` breaks domination there:
    `¬ Dominates W d i`.  This is `overtake_breaks_layer` — the completeness/divergence
    reading of the *same* overflow. -/
theorem overflow_breaks (d W : Nat → Nat) (i : Nat) (hi : 1 ≤ i)
    (hov : Overflow (fun i => (i+1) * d (i+1)) W i) : ¬ Dominates W d i :=
  overtake_breaks_layer W i hi hov

/-! ## §4 — the duality -/

/-- ★★★ **The shared engine.**  The diagonalisation residue (logical) and the
    completeness-break (analytic) are two readings of one finite operation — a value
    overflowing, by the irreducible unit `1`, the bound built to contain it:

      1. logical: overflow ⟹ the value escapes every level of the family (residue);
      2. analytic: overflow ⟹ domination breaks at that layer (¬Htel).

    Neither reading is privileged.  The overflow `bound i + 1 ≤ val i` is the
    count-Lens surplus of one distinguishing, read at two scales; the tie to the
    pointing residue is `DepthCeilingResidue.ceiling_residue_is_pointing_residue`. -/
theorem overflow_dual_reading :
    (∀ (f : Nat → Nat → Nat) (val : Nat → Nat),
        (∀ i, Overflow (fun i => f i i) val i) → ∀ i, val ≠ f i)
    ∧ (∀ (d W : Nat → Nat) (i : Nat), 1 ≤ i →
        Overflow (fun i => (i+1) * d (i+1)) W i → ¬ Dominates W d i) :=
  ⟨fun f val hov i => overflow_escapes f val hov i,
   fun d W i hi hov => overflow_breaks d W i hi hov⟩

/-! ## §5 — the unit generator: the diagonal is the *minimal* overflow

The duality is one inequality `bound + 1 ≤ val`, the surplus pinned at the unit — so
there is no hidden adjunction between two independent operators to discover; the
structural content is a **generator**.  The pointwise-least value overflowing a bound
everywhere is `bound + 1` — the bound with one unit (`Nat.succ`) added.  The two
readings are *not* symmetric: the logical diagonal **achieves** this floor exactly
(surplus = unit, unconditional), while the analytic completeness-break only **exceeds**
it and only when `W` actually overflows `d` (contingent).  The honest relationship is
therefore minimality / specialisation, not a symmetric deformation: the residue is the
unit-generated floor of overflow; the break is a larger-surplus instance above it. -/

/-- The canonical minimal overflow of a bound: the bound raised by the unit `1`
    (`Nat.succ`, the count-Lens residue of one distinguishing). -/
def minOverflow (bound : Nat → Nat) : Nat → Nat := fun i => bound i + 1

/-- The minimal overflow overflows, at every index. -/
theorem minOverflow_overflows (bound : Nat → Nat) (i : Nat) :
    Overflow bound (minOverflow bound) i :=
  Nat.lt_succ_self (bound i)

/-- ★★★ **The minimal overflow is least.**  Any value overflowing `bound` everywhere
    dominates `minOverflow bound = bound + 1` pointwise: the unit surplus is the floor
    of *every* overflow.  Both readings live above this floor. -/
theorem least_overflow (bound val : Nat → Nat)
    (hov : ∀ i, Overflow bound val i) (i : Nat) : minOverflow bound i ≤ val i :=
  hov i

/-- The Cantor diagonal **is** the minimal overflow of its diagonal bound (pointwise,
    by `rfl`): `diag f i = f i i + 1 = minOverflow (i ↦ f i i) i`.  The logical residue
    is exactly the unit-generated floor — it achieves the minimum, unconditionally. -/
theorem diag_is_minOverflow (f : Nat → Nat → Nat) (i : Nat) :
    diag f i = minOverflow (fun i => f i i) i := rfl

/-! ## §6 — stability: the overflow (hence both readings) survives deformation

The "dynamic" content Gemini asks for, stated honestly: the overflow relation is
monotone in the value and invariant under a common additive shift.  So a deformation
that does not shrink the value, or that shifts bound and value together, preserves the
overflow — and therefore preserves *both* readings simultaneously.  This is the shared
stability of the single inequality, not a claim that a polynomial-degree deformation of
`d` moves the two facets by one parametric function (the logical facet has no `d`). -/

/-- Overflow is monotone in the value: a value at least as large still overflows. -/
theorem overflow_mono_val (bound val val' : Nat → Nat) (i : Nat)
    (hov : Overflow bound val i) (hle : val i ≤ val' i) : Overflow bound val' i :=
  Nat.lt_of_lt_of_le hov hle

/-- Overflow is invariant under a common additive shift of bound and value: the unit
    surplus is shift-stable. -/
theorem overflow_shift (bound val : Nat → Nat) (c i : Nat)
    (hov : Overflow bound val i) :
    Overflow (fun i => bound i + c) (fun i => val i + c) i :=
  Nat.add_lt_add_right hov c

/-! ## §7 — the least overflow is unique, and the surplus is the conserved quantity

Two sharpenings.  First, the unit-generated floor is not merely *a* least overflow but
*the* one: any sequence that overflows `bound` everywhere and lies below every overflow
**equals** `minOverflow bound` pointwise (`minOverflow_unique`).  This is the universal
property — poset-initiality of `minOverflow` among the overflows of a bound — stated as
the honest uniqueness it is (in a `Prop`-ordered poset there is no further factorisation
content beyond `≤`).  Second, the genuinely conserved quantity under the additive
deformation of `overflow_shift` is the **surplus** itself: shifting bound and value by a
common `c` leaves `val − bound` exactly fixed (`gap_shift_invariant`).  The surplus — the
unit on the diagonal, the excess on the break — is the conserved charge of the
operation, not a topological invariant of a critical edge. -/

/-- ★★★ **The least overflow is unique.**  Any `g` that overflows `bound` everywhere and
    is a lower bound of every overflow equals `minOverflow bound` pointwise.  So
    `minOverflow` is *the* canonical minimal witness of overflow — the universal object
    both readings are mediated by (the diagonal achieves it, the break exceeds it). -/
theorem minOverflow_unique (bound g : Nat → Nat)
    (hg : ∀ i, Overflow bound g i)
    (hlb : ∀ val, (∀ i, Overflow bound val i) → ∀ i, g i ≤ val i)
    (i : Nat) : g i = minOverflow bound i :=
  Nat.le_antisymm (hlb (minOverflow bound) (minOverflow_overflows bound) i)
    (least_overflow bound g hg i)

/-- ★★ **The surplus is conserved under shift.**  A common additive deformation of bound
    and value leaves the surplus `val − bound` exactly fixed: `(val i + c) − (bound i + c)
    = val i − bound i`.  The conserved quantity of `overflow_shift` is the surplus itself
    — the unit on the diagonal side, the excess on the break side. -/
theorem gap_shift_invariant (bound val : Nat → Nat) (c i : Nat) :
    (val i + c) - (bound i + c) = val i - bound i :=
  E213.Tactic.NatHelper.add_sub_add_right (val i) c (bound i)

/-! ## §8 — gap-free expansion: nothing lies inside the unit step -/

/-- ★★★ **The unit step is gapless.**  Between a bound `b` and its minimal overflow
    `b + 1` there is **nothing**: no `x` with `b < x < b + 1`.  The minimal overflow
    (`minOverflow`, the unit surplus) is the *immediate* next — every overflow is at
    least `b + 1` (`least_overflow`) and the unit gap is empty.  So the expansion
    proceeds by the irreducible unit with no blank to fill: each next is the previous
    plus the residue `1`, and nothing sits between.  This is the discreteness that makes
    the residue cascade gap-free — the surplus of one act is, immediately and with no
    interior, the operand of the next. -/
theorem gapless_unit_step (b : Nat) : ¬ ∃ x, b < x ∧ x < b + 1 := by
  rintro ⟨x, h1, h2⟩
  exact Nat.lt_irrefl b (Nat.lt_of_lt_of_le h1 (Nat.le_of_lt_succ h2))

end E213.Lib.Math.Analysis.Cauchy.DepthOverflowDuality
