import E213.Lib.Math.Analysis.Cauchy.Euler
import E213.Meta.Nat.PureNat

/-!
# EulerDivergenceForm — the *form* of e's divergence is the factorial

`ProbeTwistConic` showed every cut wobbles along a hyperbola `Q = m²−mk−k²`, and a
transcendental's convergents **escape** every such conic (`Q` diverges).  The
natural next question: the divergence is not formless — *what is its form?*

The answer is the **cross-determinant** (the discrete Wronskian / symplectic area)
of the convergent pair `(aₙ, dₙ)`:

    W_n := aₙ·d_{n+1} − a_{n+1}·dₙ.

This single quantity *is* the form of the orbit's spreading:

  - **algebraic (φ)** — `W_n = ±1` constant: the convergents are a `Pstep`-orbit,
    `det P = 1`, area preserved, so the orbit stays on one conic.  (This is the
    Fibonacci–Cassini identity, `Mobius213/Px/ConvergentDet`.)
  - **e (transcendental)** — `W_n = −dₙ = −n!`: the area grows **exactly
    factorially**.  e's convergents are generated by the *non-autonomous* transfer
    `(a,d) ↦ ((n+1)a + 1, (n+1)d)`, whose step-determinant is `(n+1)²`, so the
    accumulated area is `∏(n+1)…` — the factorial.  e's divergence has a closed
    form, and that form is `n!`.

So the infinite divergence is captured by a *finite description* — the recurrence
of `W_n`, here the one-line identity `euler_cross_det`.  The transcendence of e is
not "no form"; it is the form `W_n = −n!` (an algebraic *function of n*, not an
algebraic *number*), exactly as the user's framing predicts: the infinite is
handled by a finite pointer, and the divergence of that is handled by another
finite pointer (the factorial).

This file proves the e side ∅-axiom; the φ side (`W_n = 1`) is
`Mobius213/Px/ConvergentDet`; the π side is the Wallis analogue (`W_n` a product
of the Wallis factors, a different closed form — that is *how e and π differ*: same
question "what is `W_n`?", different closed answers, factorial vs Wallis-product).

All ∅-axiom.
-/

namespace E213.Lib.Math.Analysis.Cauchy.EulerDivergenceForm

open E213.Lib.Math.Analysis.Cauchy.EulerSeq (eulerNum eulerDen)
open E213.Meta.Nat.PureNat (add_mul mul_assoc)

/-- The factorial, for stating the divergence form. -/
def fact : Nat → Nat
  | 0 => 1
  | n+1 => (n+1) * fact n

/-- ★ `eulerDen n = n!` — the convergent denominators are the factorials. -/
theorem eulerDen_eq_fact (n : Nat) : eulerDen n = fact n := by
  induction n with
  | zero => rfl
  | succ k ih => show (k+1) * eulerDen k = (k+1) * fact k; rw [ih]

/-- ★★★ **e's cross-determinant is `−dₙ` (sign-free form).**  The discrete
    Wronskian `W_n = aₙ·d_{n+1} − a_{n+1}·dₙ` equals `−dₙ`, stated over ℕ as

        a_{n+1}·dₙ = aₙ·d_{n+1} + dₙ.

    Both sides expand to `(n+1)·aₙ·dₙ + dₙ` once the recurrences `a_{n+1} =
    (n+1)aₙ + 1`, `d_{n+1} = (n+1)dₙ` are substituted — the `+1` in the numerator
    recurrence is exactly what makes the area leak by `dₙ` each step. -/
theorem euler_cross_det (n : Nat) :
    eulerNum (n+1) * eulerDen n = eulerNum n * eulerDen (n+1) + eulerDen n := by
  show ((n+1)*eulerNum n + 1) * eulerDen n = eulerNum n * ((n+1)*eulerDen n) + eulerDen n
  rw [add_mul, Nat.one_mul, mul_assoc (n+1) (eulerNum n) (eulerDen n),
      show eulerNum n * ((n+1)*eulerDen n) = (n+1)*(eulerNum n * eulerDen n) from by
        rw [Nat.mul_comm (eulerNum n) ((n+1)*eulerDen n),
            mul_assoc (n+1) (eulerDen n) (eulerNum n), Nat.mul_comm (eulerDen n) (eulerNum n)]]

/-- ★★★ **The divergence form, named**: e's cross-determinant magnitude is exactly
    the factorial.  `|W_n| = dₙ = n!`.  The area between consecutive convergents
    spreads factorially — that is the closed form of e's escape from every conic. -/
theorem euler_cross_det_is_factorial (n : Nat) :
    eulerNum (n+1) * eulerDen n = eulerNum n * eulerDen (n+1) + fact n := by
  rw [euler_cross_det, eulerDen_eq_fact n]

end E213.Lib.Math.Analysis.Cauchy.EulerDivergenceForm
