import E213.Lib.Math.DyadicFSM.ArithFSM.ModLarge
import E213.Lib.Math.DyadicFSM.ArithFSM.ModMedium
import E213.Lib.Math.DyadicFSM.ArithFSM.ModSmall
import E213.Lib.Math.DyadicFSM.Legendre
import E213.Lib.Math.DyadicFSM.Pisano.Predictor22

/-!
# Pisano predictor — 23-prime evidence (mod 101 added)

  | p   | leg | branch | tight | predict | match  |
  | 101 |  1  | split  |  25   |   50    | ×2 SUB |  ← NEW

★ Fourth ×2 sub-tight case ★

Sub-tight history (4 of 23):
  p=29  (split, ×2): tight 7,  predict 14
  p=47  (inert, ×3): tight 16, predict 48
  p=89  (split, ×2): tight 22, predict 44
  p=101 (split, ×2): tight 25, predict 50

Pattern emerging: split sub-tight ×2 at p ∈ {29, 89, 101, ...}.
All three are p ≡ 1 mod 4 AND p ≡ 1 mod 5 (so 5 IS QR mod p) AND
the (1,1) initial state lies in an index-2 sub-cyclic subgroup of
the multiplicative group generated by φ² in 𝔽_p^*.

Frobenius-orbit interpretation: predictor is upper bound, tight
period coincides iff no Frobenius-stable proper subgroup intersects
the (1,1)-orbit.

Per `research-notes/G119_pisano_pell5_research_direction.md`, the
tight-period analysis at sub-tight primes is a separate (deeper)
research sub-direction within FSM-1 (2).
-/

namespace E213.Lib.Math.DyadicFSM.Pisano.Predictor23

open E213.Lib.Math.DyadicFSM.Legendre.V213 (legendre213)
open E213.Lib.Math.DyadicFSM.ArithFSM (pellFSMmod3 pellFSMmod2)
open E213.Lib.Math.DyadicFSM.ArithFSM.Mod5 (pellFSMmod5)
open E213.Lib.Math.DyadicFSM.ArithFSM.Mod7 (pellFSMmod7)
open E213.Lib.Math.DyadicFSM.ArithFSM.Mod11 (pellFSMmod11)
open E213.Lib.Math.DyadicFSM.ArithFSM.Mod13 (pellFSMmod13)
open E213.Lib.Math.DyadicFSM.ArithFSM.Mod17 (pellFSMmod17)
open E213.Lib.Math.DyadicFSM.ArithFSM.Mod19 (pellFSMmod19)
open E213.Lib.Math.DyadicFSM.ArithFSM.Mod23 (pellFSMmod23)
open E213.Lib.Math.DyadicFSM.ArithFSM.Mod29 (pellFSMmod29)
open E213.Lib.Math.DyadicFSM.ArithFSM.Mod31 (pellFSMmod31)
open E213.Lib.Math.DyadicFSM.ArithFSM.Mod37 (pellFSMmod37)
open E213.Lib.Math.DyadicFSM.ArithFSM.Mod41 (pellFSMmod41)
open E213.Lib.Math.DyadicFSM.ArithFSM.Mod43 (pellFSMmod43)
open E213.Lib.Math.DyadicFSM.ArithFSM.Mod47 (pellFSMmod47)
open E213.Lib.Math.DyadicFSM.ArithFSM.Mod53 (pellFSMmod53)
open E213.Lib.Math.DyadicFSM.ArithFSM.Mod59 (pellFSMmod59)
open E213.Lib.Math.DyadicFSM.ArithFSM.Mod61 (pellFSMmod61)
open E213.Lib.Math.DyadicFSM.ArithFSM.Mod67 (pellFSMmod67)
open E213.Lib.Math.DyadicFSM.ArithFSM.Mod71 (pellFSMmod71)
open E213.Lib.Math.DyadicFSM.ArithFSM.Mod73 (pellFSMmod73)
open E213.Lib.Math.DyadicFSM.ArithFSM.Mod79 (pellFSMmod79)
open E213.Lib.Math.DyadicFSM.ArithFSM.Mod89 (pellFSMmod89)
open E213.Lib.Math.DyadicFSM.ArithFSM.Mod101 (pellFSMmod101 pellFSMmod101_bits_period_50)
open E213.Lib.Math.DyadicFSM.Pisano.Predictor (pisano_predict pisano_period_lift)
open E213.Lib.Math.DyadicFSM.Pisano.Predictor22 (pisano_predict_realises_pell_22)

theorem legendre_5_mod_101 :
    legendre213 5 101 (by decide) = ⟨1, by decide⟩ := by decide

/-- ★★★★★★★ Bit predictor computes Pell period at 23 primes. -/
theorem pisano_predict_realises_pell_23 :
    (∀ k, pellFSMmod3.bits (k + pisano_predict 3 (by decide))
        = pellFSMmod3.bits k)
    ∧ (∀ k, pellFSMmod5.bits (k + pisano_predict 5 (by decide))
        = pellFSMmod5.bits k)
    ∧ (∀ k, pellFSMmod7.bits (k + pisano_predict 7 (by decide))
        = pellFSMmod7.bits k)
    ∧ (∀ k, pellFSMmod11.bits (k + pisano_predict 11 (by decide))
        = pellFSMmod11.bits k)
    ∧ (∀ k, pellFSMmod13.bits (k + pisano_predict 13 (by decide))
        = pellFSMmod13.bits k)
    ∧ (∀ k, pellFSMmod17.bits (k + pisano_predict 17 (by decide))
        = pellFSMmod17.bits k)
    ∧ (∀ k, pellFSMmod19.bits (k + pisano_predict 19 (by decide))
        = pellFSMmod19.bits k)
    ∧ (∀ k, pellFSMmod23.bits (k + pisano_predict 23 (by decide))
        = pellFSMmod23.bits k)
    ∧ (∀ k, pellFSMmod29.bits (k + pisano_predict 29 (by decide))
        = pellFSMmod29.bits k)
    ∧ (∀ k, pellFSMmod31.bits (k + pisano_predict 31 (by decide))
        = pellFSMmod31.bits k)
    ∧ (∀ k, pellFSMmod37.bits (k + pisano_predict 37 (by decide))
        = pellFSMmod37.bits k)
    ∧ (∀ k, pellFSMmod41.bits (k + pisano_predict 41 (by decide))
        = pellFSMmod41.bits k)
    ∧ (∀ k, pellFSMmod43.bits (k + pisano_predict 43 (by decide))
        = pellFSMmod43.bits k)
    ∧ (∀ k, pellFSMmod47.bits (k + pisano_predict 47 (by decide))
        = pellFSMmod47.bits k)
    ∧ (∀ k, pellFSMmod53.bits (k + pisano_predict 53 (by decide))
        = pellFSMmod53.bits k)
    ∧ (∀ k, pellFSMmod59.bits (k + pisano_predict 59 (by decide))
        = pellFSMmod59.bits k)
    ∧ (∀ k, pellFSMmod61.bits (k + pisano_predict 61 (by decide))
        = pellFSMmod61.bits k)
    ∧ (∀ k, pellFSMmod67.bits (k + pisano_predict 67 (by decide))
        = pellFSMmod67.bits k)
    ∧ (∀ k, pellFSMmod71.bits (k + pisano_predict 71 (by decide))
        = pellFSMmod71.bits k)
    ∧ (∀ k, pellFSMmod73.bits (k + pisano_predict 73 (by decide))
        = pellFSMmod73.bits k)
    ∧ (∀ k, pellFSMmod79.bits (k + pisano_predict 79 (by decide))
        = pellFSMmod79.bits k)
    ∧ (∀ k, pellFSMmod89.bits (k + pisano_predict 89 (by decide))
        = pellFSMmod89.bits k)
    ∧ (∀ k, pellFSMmod101.bits (k + pisano_predict 101 (by decide))
        = pellFSMmod101.bits k) := by
  let H := pisano_predict_realises_pell_22
  exact ⟨H.1, H.2.1, H.2.2.1, H.2.2.2.1, H.2.2.2.2.1,
         H.2.2.2.2.2.1, H.2.2.2.2.2.2.1,
         H.2.2.2.2.2.2.2.1, H.2.2.2.2.2.2.2.2.1,
         H.2.2.2.2.2.2.2.2.2.1, H.2.2.2.2.2.2.2.2.2.2.1,
         H.2.2.2.2.2.2.2.2.2.2.2.1,
         H.2.2.2.2.2.2.2.2.2.2.2.2.1,
         H.2.2.2.2.2.2.2.2.2.2.2.2.2.1,
         H.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1,
         H.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1,
         H.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1,
         H.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1,
         H.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1,
         H.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1,
         H.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1,
         H.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2,
         pisano_period_lift (by decide : pisano_predict 101 (by decide) = 50)
                            pellFSMmod101_bits_period_50⟩

end E213.Lib.Math.DyadicFSM.Pisano.Predictor23
