import E213.Lib.Math.DyadicFSM.Legendre.Legendre
import E213.Lib.Math.DyadicFSM.ArithFSM.Hierarchy

import E213.Lib.Math.DyadicFSM.ArithFSM
import E213.Lib.Math.DyadicFSM.ArithFSM.V1
import E213.Lib.Math.DyadicFSM.ArithFSM.V3
/-!
# 213-native algebraic degree

Defines the algebraic degree of a bit stream as the *minimum*
ArithFSM_d in which it appears.  Operationally:

  HasDegree₁(bs) := ∃ n hn (m : ArithFSM₁ n), bs = m.bits
  HasDegree₂(bs) := ∃ n hn (m : ArithFSM₂ n), bs = m.bits
  HasDegree₃(bs) := ∃ n hn (m : ArithFSM₃ n), bs = m.bits

By the hierarchy capstone, HasDegree₁ ⊂ HasDegree₂ ⊂ HasDegree₃.
The 213-native algebraic degree is the *minimum* d such that
HasDegree_d(bs) holds.

This is **structurally** the algebraic degree of the underlying
algebraic number (when bs comes from one), but defined entirely
in terms of trajectory state-space dimension.
-/

namespace E213.Lib.Math.DyadicFSM.Tier.AlgebraicDegree

open E213.Lib.Math.DyadicFSM.ArithFSM.V1 (ArithFSM1)
open E213.Lib.Math.DyadicFSM.ArithFSM (ArithFSM2)
open E213.Lib.Math.DyadicFSM.ArithFSM.V3 (ArithFSM3 tribFSMmod2)
open E213.Lib.Math.DyadicFSM.Legendre.V213 (legendreFSM)
open E213.Lib.Math.DyadicFSM.ArithFSM (pellFSMmod3)
open E213.Lib.Math.DyadicFSM.ArithFSM.V1to2 (padTo2_bits_eq)
open E213.Lib.Math.DyadicFSM.ArithFSM (padTo3_bits_eq)


/-- bs is generated by some ArithFSM₁. -/
def HasDegree1 (bs : Nat → Bool) : Prop :=
  ∃ (n : Nat) (hn : 0 < n) (m : ArithFSM1 n), ∀ k, m.bits k = bs k

/-- bs is generated by some ArithFSM₂. -/
def HasDegree2 (bs : Nat → Bool) : Prop :=
  ∃ (n : Nat) (hn : 0 < n) (m : ArithFSM2 n), ∀ k, m.bits k = bs k

/-- bs is generated by some ArithFSM₃. -/
def HasDegree3 (bs : Nat → Bool) : Prop :=
  ∃ (n : Nat) (hn : 0 < n) (m : ArithFSM3 n), ∀ k, m.bits k = bs k

/-- ★★★★ Degree containment: HasDegree₁ ⊂ HasDegree₂. -/
theorem degree1_imp_degree2 (bs : Nat → Bool) :
    HasDegree1 bs → HasDegree2 bs := by
  rintro ⟨n, hn, m, hm⟩
  refine ⟨n, hn, m.padTo2 hn, ?_⟩
  intro k
  rw [padTo2_bits_eq hn m k]
  exact hm k

/-- ★★★★ Degree containment: HasDegree₂ ⊂ HasDegree₃. -/
theorem degree2_imp_degree3 (bs : Nat → Bool) :
    HasDegree2 bs → HasDegree3 bs := by
  rintro ⟨n, hn, m, hm⟩
  refine ⟨n, hn, m.padTo3 hn, ?_⟩
  intro k
  rw [padTo3_bits_eq hn m k]
  exact hm k

/-- ★★★★★ Transitive containment: HasDegree₁ ⊂ HasDegree₃. -/
theorem degree1_imp_degree3 (bs : Nat → Bool) :
    HasDegree1 bs → HasDegree3 bs :=
  fun h => degree2_imp_degree3 bs (degree1_imp_degree2 bs h)

/-- ★★★★★★ legendreFSM has degree ≤ 1 (multiplicative trajectory). -/
theorem legendreFSM_has_degree1 (D p : Nat) (hp : 0 < p) :
    HasDegree1 (legendreFSM D p hp).bits :=
  ⟨p, hp, legendreFSM D p hp, fun _ => rfl⟩

/-- ★★★★★★ pellFSMmod_p has degree ≤ 2 (quadratic algebraic). -/
theorem pellFSMmod3_has_degree2 :
    HasDegree2 pellFSMmod3.bits :=
  ⟨3, by decide, pellFSMmod3, fun _ => rfl⟩

/-- ★★★★★★ tribFSMmod2 has degree ≤ 3 (cubic algebraic). -/
theorem tribFSMmod2_has_degree3 :
    HasDegree3 tribFSMmod2.bits :=
  ⟨2, by decide, tribFSMmod2, fun _ => rfl⟩

end E213.Lib.Math.DyadicFSM.Tier.AlgebraicDegree
