import E213.Lib.Math.Foundations.PatternCatalog.Core

/-!
# Pattern Catalog — Operator Algebra (free monoid on {A, F})

C5 observation made formal: the operator words generated by
{Aggregate, Forced} compose into a **free monoid** on the 2-letter
alphabet.  This file types the alphabet, the words, the
concatenation, and the free-monoid laws (associativity + identity)
all ∅-axiom.

We do NOT prove non-idempotence at the type level (that requires
fighting Type-equality).  Instead, we record `aggCount` and
`forCount` on OpWord and show that distinct words have distinct
counts — which forces distinct types under the `apply`
interpretation.
-/

namespace E213.Lib.Math.Foundations.PatternCatalog.Algebra

open E213.Lib.Math.Foundations.PatternCatalog.Core (Aggregate Forced)

/-- Words over the 2-letter alphabet {A (Aggregate), F (Forced)}.
    Stored prepend-style: `A w` means "apply A first, then w". -/
inductive OpWord where
  | nil : OpWord
  | A   : OpWord → OpWord
  | F   : OpWord → OpWord
  deriving DecidableEq, Repr

/-- Word length. -/
def OpWord.length : OpWord → Nat
  | .nil => 0
  | .A w => 1 + w.length
  | .F w => 1 + w.length

/-- Concatenation. -/
def OpWord.append : OpWord → OpWord → OpWord
  | .nil,   v => v
  | .A u,   v => .A (u.append v)
  | .F u,   v => .F (u.append v)

/-- Identity (left): `nil ++ v = v` definitionally. -/
theorem OpWord.nil_append (v : OpWord) :
    OpWord.append .nil v = v := rfl

/-- Identity (right): `u ++ nil = u` by induction. -/
theorem OpWord.append_nil : ∀ u : OpWord, u.append .nil = u
  | .nil   => rfl
  | .A u   => by
      show OpWord.A (u.append .nil) = OpWord.A u
      rw [OpWord.append_nil u]
  | .F u   => by
      show OpWord.F (u.append .nil) = OpWord.F u
      rw [OpWord.append_nil u]

/-- Associativity: `(u ++ v) ++ w = u ++ (v ++ w)`. -/
theorem OpWord.append_assoc :
    ∀ u v w : OpWord, (u.append v).append w = u.append (v.append w)
  | .nil,   _, _ => rfl
  | .A u,   v, w => by
      show OpWord.A ((u.append v).append w) = OpWord.A (u.append (v.append w))
      rw [OpWord.append_assoc u v w]
  | .F u,   v, w => by
      show OpWord.F ((u.append v).append w) = OpWord.F (u.append (v.append w))
      rw [OpWord.append_assoc u v w]

/-- Per-letter counts.  `aggCount` counts A's, `forCount` counts F's. -/
def OpWord.aggCount : OpWord → Nat
  | .nil => 0
  | .A w => 1 + w.aggCount
  | .F w => w.aggCount

def OpWord.forCount : OpWord → Nat
  | .nil => 0
  | .A w => w.forCount
  | .F w => 1 + w.forCount

/-- Counts are additive under append. -/
theorem OpWord.aggCount_append :
    ∀ u v : OpWord, (u.append v).aggCount = u.aggCount + v.aggCount
  | .nil,   v => by
      show v.aggCount = 0 + v.aggCount
      rw [Nat.zero_add]
  | .A u,   v => by
      show 1 + (u.append v).aggCount = (1 + u.aggCount) + v.aggCount
      rw [OpWord.aggCount_append u v, Nat.add_assoc]
  | .F u,   v => by
      show (u.append v).aggCount = u.aggCount + v.aggCount
      exact OpWord.aggCount_append u v

/-- **Apply an operator word as a type constructor**.  `nil` is the
    identity, `A w` prepends `Aggregate`, `F w` prepends `Forced`. -/
def OpWord.apply : OpWord → Type → Type
  | .nil,   T => T
  | .A w,   T => Aggregate (w.apply T)
  | .F w,   T => Forced    (w.apply T)

/-! ## 213-foundational Anchors

Every game in the catalog is a **signature on type slots** built
from a small set of type-theoretic primitives admitted by 213's
kernel.  This section enumerates those primitives and tags each
atomic game / operator with its anchor set.

The catalog is anchored on:

  · `Type`     — the universe of types
  · `→`        — function space (Lean's `Pi`-type, non-dependent)
  · `∀`        — dependent product (the `forced` field of `Forced`)
  · `Nat`      — Peano natural numbers (indices, time, arity)
  · `Prop`     — proposition universe (the `cond` of `Forced`)
  · `Iff`      — propositional biconditional (the `forced` ↔)
  · `Eq`       — propositional equality (Locality's `agrees`,
                 Cata's coherence equations)
  · `Pair`     — product types (Dynamical's `period_witness : Nat × Nat`)
  · `Raw`      — 213's primitive 2-atom + slash structure

No game requires anything beyond this set.  In particular: NO
quotient types, NO `propext`, NO `Quot.sound`, NO `Classical`.  This
is what makes the catalog ∅-axiom verifiable. -/

inductive Primitive where
  | type
  | arrow
  | pi
  | nat
  | prop
  | iff
  | eq
  | pair
  | raw
  deriving DecidableEq, Repr

/-- Anchor record for a game: name + which primitives its signature
    references.  We use a `Primitive → Bool` characteristic function
    instead of `List Primitive` to stay ∅-axiom (no `List.Mem` on
    propext-bearing equality). -/
structure GameAnchor where
  name      : String
  uses      : Primitive → Bool

/-- Convenient builder: anchor from a checklist. -/
def GameAnchor.mk' (name : String)
    (type arrow pi nat prop iff eq pair raw : Bool) : GameAnchor :=
  { name := name
    uses := fun
      | .type  => type
      | .arrow => arrow
      | .pi    => pi
      | .nat   => nat
      | .prop  => prop
      | .iff   => iff
      | .eq    => eq
      | .pair  => pair
      | .raw   => raw }

/-! ### Anchor records for the 4 atomic games + 2 operators -/

def Locality.anchor : GameAnchor :=
  GameAnchor.mk' "Locality"
    (type := true)  (arrow := true)  (pi := true)
    (nat := false)  (prop := false)  (iff := false)
    (eq := true)    (pair := false)  (raw := false)

def Typeclass.anchor : GameAnchor :=
  GameAnchor.mk' "Typeclass"
    (type := true)  (arrow := true)  (pi := false)
    (nat := false)  (prop := false)  (iff := false)
    (eq := false)   (pair := false)  (raw := false)

def Catamorphism.anchor : GameAnchor :=
  GameAnchor.mk' "Catamorphism"
    (type := true)  (arrow := true)  (pi := false)
    (nat := true)   (prop := false)  (iff := false)
    (eq := false)   (pair := false)  (raw := false)

def Dynamical.anchor : GameAnchor :=
  GameAnchor.mk' "Dynamical"
    (type := true)  (arrow := true)  (pi := false)
    (nat := true)   (prop := false)  (iff := false)
    (eq := false)   (pair := true)   (raw := false)

def AggregateOp.anchor : GameAnchor :=
  GameAnchor.mk' "Aggregate (operator)"
    (type := true)  (arrow := true)  (pi := false)
    (nat := true)   (prop := false)  (iff := false)
    (eq := false)   (pair := false)  (raw := false)

def ForcedOp.anchor : GameAnchor :=
  GameAnchor.mk' "Forced (operator)"
    (type := true)  (arrow := true)  (pi := true)
    (nat := false)  (prop := true)   (iff := true)
    (eq := false)   (pair := false)  (raw := false)

/-! ### Anchor coverage

Union of all 6 anchor sets: {type, arrow, pi, nat, prop, iff, eq,
pair} — 8 of the 9 primitives.  `raw` is NOT used by any catalog
signature; it surfaces only in concrete instances (e.g.,
`peanoLensWitness` references `Lens.leaves`, which folds over Raw).

The **catalog floor** is the 8-primitive subset.  Removing any one
loses at least one atomic game / operator. -/

/-- The catalog floor: a primitive belongs to the floor iff at least
    one of the 6 game anchors uses it. -/
def Primitive.inFloor (p : Primitive) : Bool :=
  Locality.anchor.uses p
    || Typeclass.anchor.uses p
    || Catamorphism.anchor.uses p
    || Dynamical.anchor.uses p
    || AggregateOp.anchor.uses p
    || ForcedOp.anchor.uses p

example : Primitive.inFloor .type  = true  := rfl
example : Primitive.inFloor .arrow = true  := rfl
example : Primitive.inFloor .pi    = true  := rfl
example : Primitive.inFloor .nat   = true  := rfl
example : Primitive.inFloor .prop  = true  := rfl
example : Primitive.inFloor .iff   = true  := rfl
example : Primitive.inFloor .eq    = true  := rfl
example : Primitive.inFloor .pair  = true  := rfl
example : Primitive.inFloor .raw   = false := rfl

end E213.Lib.Math.Foundations.PatternCatalog.Algebra
