import E213.Lib.Math.NumberSystems.Real213.GoldenFormMarkov
import E213.Lib.Physics.Simplex.Counts
import E213.Lib.Math.Mobius213.Px.FibonacciAtomicLock

/-!
# MarkovTree — the Markov equation `x²+y²+z² = 3xyz`, the Vieta tree, and `3 = NS`

The Lagrange/Markov spectrum below `3` is `{√(9m²−4)/m : m a Markov number}`, the Markov
numbers `1, 2, 5, 13, 29, …` being the largest entries of the **Markov triples** — solutions
of `x² + y² + z² = 3xyz`.  `GoldenFormMarkov` pinned the first two values `√5` (golden, `m=1`)
and `√8` (silver, `m=2`); the whole spectrum is generated by the **Markov tree**, the binary
tree of triples under Vieta jumping.

Two `213`-native facts here, both ∅-axiom:

  * the Markov coefficient is **`NS = 3`** (`markov_coefficient_is_NS`): the equation is
    `x² + y² + z² = NS·xyz`, the atomic `3` of the simplex counts — the same `3` that is the
    trace of the golden matrix `P = [[2,1],[1,1]]`;
  * **Vieta jumping** (`markov_vieta`): the two roots `z, z'` of the quadratic `t² − 3xy·t +
    (x²+y²) = 0` satisfy `z + z' = 3xy`, and if `(x,y,z)` is a triple so is `(x,y,z')`.  The
    clean engine is the involution invariant `x² + y² = z·z'` (`markov_xy`) — proved with no
    subtraction (cancel `z²` via `3xyz = z² + z·z'`), so the jump is pure `ℕ` arithmetic.

The tree from the root `(1,1,1)` (`markov_tree_branch`): `(1,1,1) → (1,1,2) → (1,2,5) →
(1,5,13) → (2,5,29)` — each a verified solution, the Markov numbers `1,2,5,13,29` whose
Lagrange values `√5, √8, √(221)/5, …` build the bottom of the approximation spectrum off the
single atomic coefficient `NS = 3`.
-/

namespace E213.Lib.Math.NumberSystems.Real213.MarkovTree

open E213.Lib.Math.NumberSystems.Real213.GoldenFormMarkov (add_left_cancel_pure)
open E213.Lib.Physics.Simplex.Counts (NS)
open E213.Lib.Math.Mobius213.Px.FibonacciAtomicLock (fib)

/-- The Markov equation `x² + y² + z² = 3·x·y·z`. -/
abbrev markovEq (x y z : Nat) : Prop := x * x + y * y + z * z = 3 * x * y * z

/-! ## §1 — the Vieta involution invariant `x² + y² = z·z'` -/

/-- ★★★ **The Vieta invariant.**  If `(x,y,z)` is a Markov triple and `z + z' = 3xy` (the two
    roots of `t² − 3xy·t + (x²+y²)`), then `x² + y² = z·z'`.  Pure `ℕ`: cancel `z²` from
    `3xyz = z² + z·z'`. -/
theorem markov_xy (x y z z' : Nat) (hz : z + z' = 3 * x * y) (h : markovEq x y z) :
    x * x + y * y = z * z' := by
  have h3z : 3 * x * y * z = z * z + z * z' := by
    rw [← hz, E213.Tactic.NatHelper.add_mul, Nat.mul_comm z' z]
  rw [markovEq, h3z, Nat.add_comm (x * x + y * y) (z * z)] at h
  exact add_left_cancel_pure _ _ _ h

/-- ★★★ **Vieta jumping preserves the Markov equation.**  With `z + z' = 3xy`, if `(x,y,z)`
    is a triple then `(x,y,z')` is — `x²+y²+z'² = z·z' + z'² = z'(z+z') = z'·3xy`.  Pure `ℕ`,
    no subtraction.  This is the edge relation of the Markov tree. -/
theorem markov_vieta (x y z z' : Nat) (hz : z + z' = 3 * x * y) (h : markovEq x y z) :
    markovEq x y z' := by
  have hxy : x * x + y * y = z * z' := markov_xy x y z z' hz h
  show x * x + y * y + z' * z' = 3 * x * y * z'
  rw [hxy, Nat.mul_comm z z', ← Nat.mul_add, hz, Nat.mul_comm z' (3 * x * y)]

/-! ## §2 — the coefficient is `NS`, and the tree from `(1,1,1)` -/

/-- The Markov coefficient `3` is the atomic count `NS` (trace of `P = [[2,1],[1,1]]`). -/
theorem markov_coefficient_is_NS : (3 : Nat) = NS := rfl

/-- ★★★ **The Markov tree branch `(1,1,1) → (1,1,2) → (1,2,5) → (1,5,13) → (2,5,29)`.**  Each
    is a verified solution of `x²+y²+z² = 3xyz`; the Markov numbers `1,2,5,13,29` carry the
    Lagrange values `√5, √8, √221/5, √1517/13, √7565/29` — the bottom of the spectrum. -/
theorem markov_tree_branch :
    markovEq 1 1 1 ∧ markovEq 1 1 2 ∧ markovEq 1 2 5 ∧ markovEq 1 5 13 ∧ markovEq 2 5 29 := by
  refine ⟨?_, ?_, ?_, ?_, ?_⟩ <;> decide

/-- The first Vieta jump `(1,1,1) → (1,1,2)` via `markov_vieta` (`z=1, z'=2`, `z+z' = 3 =
    3·1·1`), tying the tree engine to the `√5 → √8` step (golden → silver Markov form). -/
theorem markov_first_jump : markovEq 1 1 2 :=
  markov_vieta 1 1 1 2 (by decide) (by decide)

/-! ## §3 — symmetry, and the Fibonacci branch of the tree -/

/-- The Markov equation is symmetric in its last two arguments. -/
theorem markov_symm (x y z : Nat) (h : markovEq x y z) : markovEq x z y := by
  show x * x + z * z + y * y = 3 * x * z * y
  have hmul : 3 * x * z * y = 3 * x * y * z := by
    rw [E213.Tactic.NatHelper.mul_assoc (3 * x) z y, Nat.mul_comm z y,
        ← E213.Tactic.NatHelper.mul_assoc (3 * x) y z]
  rw [Nat.add_right_comm (x * x) (z * z) (y * y), hmul]
  exact h

/-- ★★★ **The Fibonacci branch of the Markov tree.**  The odd-index Fibonacci numbers
    `fib 1, fib 3, fib 5, fib 7, fib 9 = 1, 2, 5, 13, 34` are exactly the Markov numbers along
    the `(1, F_{2n−1}, F_{2n+1})` branch: each consecutive pair forms a triple
    `markovEq 1 (fib(2n+1)) (fib(2n+3))`.  (The Vieta step `F_{2n−1} + F_{2n+3} = 3·F_{2n+1}`
    sends one odd-index Fibonacci to the next — the golden recurrence *is* the tree's
    left spine.)  Verified concretely; the general `∀ n` pattern follows by that identity. -/
theorem markov_fibonacci_branch :
    fib 1 = 1 ∧ fib 3 = 2 ∧ fib 5 = 5 ∧ fib 7 = 13 ∧ fib 9 = 34
    ∧ markovEq 1 (fib 1) (fib 3) ∧ markovEq 1 (fib 3) (fib 5)
    ∧ markovEq 1 (fib 5) (fib 7) ∧ markovEq 1 (fib 7) (fib 9) := by
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩ <;> decide

/-! ## §4 — the Pell branch (the `√2`/silver spine) -/

/-- Pell numbers `P(n+2) = 2·P(n+1) + P(n)`: `0, 1, 2, 5, 12, 29, 70, 169, …`. -/
def pell : Nat → Nat
  | 0 => 0
  | 1 => 1
  | (n + 2) => 2 * pell (n + 1) + pell n

/-- ★★★ **The Pell branch of the Markov tree.**  The odd-index Pell numbers
    `pell 1, pell 3, pell 5, pell 7 = 1, 5, 29, 169` are the Markov numbers on the
    `(2, P_{2n−1}, P_{2n+1})` branch: each consecutive pair forms a triple
    `markovEq 2 (pell(2n−1)) (pell(2n+1))`.  The Vieta step `P_{2n−1} + P_{2n+3} = 6·P_{2n+1}
    = 3·2·P_{2n+1}` is the Pell recurrence — the `√2`/silver-form spine, parallel to the
    Fibonacci/golden spine, the two principal branches descending from `(1,1,2)`. -/
theorem markov_pell_branch :
    pell 1 = 1 ∧ pell 3 = 5 ∧ pell 5 = 29 ∧ pell 7 = 169
    ∧ markovEq 2 (pell 1) (pell 3) ∧ markovEq 2 (pell 3) (pell 5)
    ∧ markovEq 2 (pell 5) (pell 7) := by
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_⟩ <;> decide

/-- A Vieta jump along the Pell spine `(2, 5, 29) → (2, 29, 169)` via `markov_vieta`
    (`pell 3 + pell 7 = 5 + 169 = 174 = 3·2·29 = 3·2·pell 5`). -/
theorem markov_pell_jump : markovEq 2 (pell 5) (pell 7) :=
  markov_vieta 2 (pell 5) (pell 3) (pell 7) (by decide) (by decide)

/-! ## §5 — the binary fork: where the Fibonacci and Pell spines diverge (Stern-Brocot node) -/

/-- The Fibonacci child of `(1,2,5)`: jump the `2` (keep `1,5`), `2 + 13 = 15 = 3·1·5`,
    landing on `(1,5,13)` — the `√5`/golden branch (`fib 7 = 13`). -/
theorem markov_fork_fibonacci : markovEq 1 5 13 :=
  markov_vieta 1 5 2 13 (by decide) (markov_symm 1 2 5 (by decide))

/-- The Pell child of `(1,2,5)`: jump the `1` (keep `2,5`), `1 + 29 = 30 = 3·2·5`, landing on
    `(2,5,29)` — the `√8`/silver branch (`pell 5 = 29`). -/
theorem markov_fork_pell : markovEq 2 5 29 :=
  markov_vieta 2 5 1 29 (by decide) (by decide)

/-- ★★★ **The first binary fork `(1,2,5) → {(1,5,13), (2,5,29)}`.**  The Markov tree is the
    Stern-Brocot binary tree on `SL(2,ℤ)` data: each triple has two Vieta children.  At
    `(1,2,5)` the two children are the **Fibonacci spine** (`13`, the `√5` side) and the
    **Pell spine** (`29`, the `√8` side) — the node where the two principal branches of the
    Lagrange spectrum diverge.  (Whether this indexing is injective — every Markov number on
    a unique node — is the classical **Markov uniqueness conjecture**, open.) -/
theorem markov_first_fork : markovEq 1 5 13 ∧ markovEq 2 5 29 :=
  ⟨markov_fork_fibonacci, markov_fork_pell⟩

end E213.Lib.Math.NumberSystems.Real213.MarkovTree
