import E213.Math.Cohomology.DyadicForwardClosure

/-!
# BitFSM — finite-state-machine generated bit streams

A BitFSM with `n` states generates a Bool stream via state
transitions: `run k = step^k init`, `bits k = out (run k)`.

By pigeonhole, the run is eventually periodic with period ≤ n,
hence the bits are eventually periodic, hence (by Tier 0 forward
closure) the K_{3,2}^{(2)} signature is also eventually periodic.

Implication: Tier 0 ∪ Tier 1 ⊂ {bit streams generable by some
BitFSM}.  Tier 2 (e, π, etc.) is conjecturally OUTSIDE this class.
-/

namespace E213.Math.Cohomology.DyadicConjecture

/-- A BitFSM with `n` states. -/
structure BitFSM (n : Nat) where
  init : Fin n
  step : Fin n → Fin n
  out  : Fin n → Bool

/-- Run the FSM for k steps. -/
def BitFSM.run {n : Nat} (m : BitFSM n) : Nat → Fin n
  | 0 => m.init
  | k + 1 => m.step (m.run k)

/-- Bit stream generated by the FSM. -/
def BitFSM.bits {n : Nat} (m : BitFSM n) (k : Nat) : Bool :=
  m.out (m.run k)

/-- ★ FSM run collision via pigeonhole. -/
theorem fsm_run_collision {n : Nat} (m : BitFSM n) :
    ∃ i, i ≤ n ∧ ∃ j, j ≤ n ∧ i < j ∧ m.run i = m.run j := by
  have hlt : n < n + 1 := Nat.lt_succ_self _
  let g : Fin (n+1) → Fin n := fun k => m.run k.val
  obtain ⟨i, hi, j, hj, hij, hcoll⟩ := pigeonhole_collision hlt g
  refine ⟨i, by omega, j, by omega, hij, ?_⟩
  unfold collisionTest at hcoll
  simp [hi, hj] at hcoll
  exact Fin.ext hcoll

/-- ★★★ BitFSM run is eventually periodic. -/
theorem fsm_run_eventually_periodic {n : Nat} (m : BitFSM n) :
    ∃ N P, 0 < P ∧ ∀ k, k ≥ N → m.run (k + P) = m.run k := by
  obtain ⟨i, _, j, _, hij, heq⟩ := fsm_run_collision m
  refine ⟨i, j - i, by omega, ?_⟩
  intro k hk
  obtain ⟨d, rfl⟩ : ∃ d, k = i + d := ⟨k - i, (Nat.add_sub_cancel' hk).symm⟩
  clear hk
  induction d with
  | zero =>
    show m.run (i + 0 + (j - i)) = m.run (i + 0)
    rw [Nat.add_zero, Nat.add_comm i (j - i),
        Nat.sub_add_cancel (Nat.le_of_lt hij)]
    exact heq.symm
  | succ d' ih =>
    have h1 : i + (d' + 1) + (j - i) = (i + d' + (j - i)) + 1 := by omega
    have h2 : i + (d' + 1) = (i + d') + 1 := by omega
    rw [h1, h2]
    show m.step (m.run (i + d' + (j - i))) = m.step (m.run (i + d'))
    rw [ih]

/-- ★★★★★ BitFSM bit stream is eventually periodic. -/
theorem fsm_bits_eventually_periodic {n : Nat} (m : BitFSM n) :
    ∃ N P, 0 < P ∧ ∀ k, k ≥ N → m.bits (k + P) = m.bits k := by
  obtain ⟨N, P, hP, h⟩ := fsm_run_eventually_periodic m
  refine ⟨N, P, hP, ?_⟩
  intro k hk
  show m.out (m.run (k + P)) = m.out (m.run k)
  rw [h k hk]

end E213.Math.Cohomology.DyadicConjecture
