import E213.Math.Cohomology.Dyadic.BitFSM.Converse

/-!
# Tier 2 hardness: aperiodic bit streams are NOT BitFSM-generable

Negative result: any bit stream that is not eventually periodic
(in the strong sense — fails to be periodic with ANY pre-period
N and period P) cannot be generated by any BitFSM, regardless
of state count.

Combined with `aperiodic_bits_imp_aperiodic_sig`, gives the
full negative characterisation: aperiodic ⇒ no FSM AND aperiodic
signature.

For genuine transcendentals (e, π), conjecturally their binary
expansions are aperiodic, so they're not BitFSM-generable.
-/

namespace E213.Math.Cohomology.Dyadic.Conjecture

/-- ★★★★★ Aperiodic bs ⇒ no BitFSM generates it. -/
theorem aperiodic_bits_imp_not_BitFSM (bs : Nat → Bool)
    (h_aperiodic : ∀ N P, 0 < P → ∃ k, k ≥ N ∧ bs (k + P) ≠ bs k) :
    ∀ (n : Nat) (m : BitFSM n), ¬ (∀ k, m.bits k = bs k) := by
  intro n m h_match
  obtain ⟨N, P, hP, h_per⟩ := fsm_bits_eventually_periodic m
  have h_bs_per : ∀ k, k ≥ N → bs (k + P) = bs k := by
    intro k hk
    rw [← h_match (k + P), ← h_match k]
    exact h_per k hk
  obtain ⟨k, hk, hne⟩ := h_aperiodic N P hP
  exact hne (h_bs_per k hk)

/-- Convenience: aperiodic ⇒ ∀ n, no BitFSM(n). -/
theorem aperiodic_bits_imp_no_BitFSM (bs : Nat → Bool)
    (h_aperiodic : ∀ N P, 0 < P → ∃ k, k ≥ N ∧ bs (k + P) ≠ bs k) :
    ¬ ∃ (n : Nat) (m : BitFSM n), ∀ k, m.bits k = bs k := by
  rintro ⟨n, m, hmatch⟩
  exact aperiodic_bits_imp_not_BitFSM bs h_aperiodic n m hmatch

/-- ★★★★★★ BitFSM-generable ⇒ eventually periodic.  The forward
    direction of the BitFSM-class characterisation.  (The
    converse for genuinely eventually-periodic-with-pre-period
    requires a pre-period BitFSM construction; for purely
    periodic case see `tier0_equiv_bitfsm`.) -/
theorem BitFSM_generable_imp_eventually_periodic (bs : Nat → Bool) :
    (∃ (n : Nat) (m : BitFSM n), ∀ k, m.bits k = bs k)
    → ∃ N P, 0 < P ∧ ∀ k, k ≥ N → bs (k + P) = bs k := by
  rintro ⟨n, m, hmatch⟩
  obtain ⟨N, P, hP, h_per⟩ := fsm_bits_eventually_periodic m
  refine ⟨N, P, hP, ?_⟩
  intro k hk
  rw [← hmatch (k + P), ← hmatch k]
  exact h_per k hk

end E213.Math.Cohomology.Dyadic.Conjecture
