import E213.Lib.Math.CayleyDickson.Integer.ZOmegaUnits
import E213.Lib.Math.CayleyDickson.Integer.ZOmegaDouble
import E213.Lib.Math.CayleyDickson.Lipschitz.LipschitzOrder4Monopoly

/-!
# The `A` and `D` McKay families as closed groups

The exceptional `E` rungs (`2T,2O,2I`) are witnessed by explicit
order-5/8/10 elements.  This file refines the *infinite* `A` (cyclic) and
`D` (binary dihedral) families from order-distribution signatures to
**actual closed group structure**:

  * `A` — the Eisenstein units `C₆ = ⟨ζ₆⟩`: the six powers `ζ₆⁰…ζ₆⁵` are
    distinct and enumerate `units6` exactly, so `units6` is the cyclic
    group `C₆` generated by `ζ₆` (the `A₅`-type McKay node `C₆`).
  * `D` — the binary dihedral loops closed under multiplication:
    `Q₈ = Dic₂` (the 8 `Lipschitz` units) and `Dic₃` (the 12
    `ZOmegaDouble` units) are each closed under `*`, hence finite
    subgroups (the `Dₙ` McKay nodes).
-/

namespace E213.Lib.Math.CayleyDickson.Tower.McKayADClosure

open E213.Lib.Math.CayleyDickson.Integer.ZOmega
open E213.Lib.Math.CayleyDickson.Integer.ZOmegaDouble
open E213.Lib.Math.CayleyDickson.Tower.CDDouble.Lipschitz

/-- The six powers `ζ₆⁰, ζ₆¹, …, ζ₆⁵`. -/
def zeta6_powers : List ZOmega :=
  [⟨1, 0⟩, Zeta6, Zeta6 * Zeta6, Zeta6 * Zeta6 * Zeta6,
   Zeta6 * Zeta6 * Zeta6 * Zeta6, Zeta6 * Zeta6 * Zeta6 * Zeta6 * Zeta6]

/-- ★ **`A` family: the Eisenstein units are the cyclic group `C₆ = ⟨ζ₆⟩`.**
    The six powers of `ζ₆ = ⟨1,1⟩` are distinct (`Nodup`) and enumerate
    `units6` in both directions, so `units6 = ⟨ζ₆⟩ ≅ C₆` — the cyclic
    McKay node. -/
theorem eisenstein_C6_cyclic :
    zeta6_powers.length = 6
    ∧ zeta6_powers.Nodup
    ∧ (∀ p ∈ zeta6_powers, units6.contains p = true)
    ∧ (∀ u ∈ units6, zeta6_powers.contains u = true) := by
  refine ⟨rfl, ?_, ?_, ?_⟩ <;> decide

/-- ★ **`D` family (`Q₈ = Dic₂`): the 8 `Lipschitz` units form a group.**
    `lip_units` has 8 elements and is closed under multiplication — the
    quaternion group `Q₈`, the smallest binary dihedral / `D₄` McKay
    node. -/
theorem lipschitz_Q8_closed :
    lip_units.length = 8
    ∧ (∀ u ∈ lip_units, ∀ v ∈ lip_units, lip_units.contains (u * v) = true) := by
  refine ⟨rfl, ?_⟩
  decide

/-- ★ **`D` family (`Dic₃`): the 12 `ZOmegaDouble` units form a group.**
    `zod_units` has 12 elements and is closed under multiplication — the
    binary dihedral group `Dic₃` (`D₅` McKay node), the doubled Eisenstein
    loop carrying the `3,6`-torsion. -/
theorem eisenstein_double_Dic3_closed :
    zod_units.length = 12
    ∧ (∀ u ∈ zod_units, ∀ v ∈ zod_units, zod_units.contains (u * v) = true) := by
  refine ⟨rfl, ?_⟩
  decide

end E213.Lib.Math.CayleyDickson.Tower.McKayADClosure
