import E213.Meta.Int213
import E213.Meta.Int213.Bound
import E213.Meta.Int213.PolyIntMTactic
import E213.Lib.Math.Combinatorics.IntGridSum

/-!
# Weighted integration by parts — the `∇𝓕 ↔ flow` identity (∅-axiom)

The **weighted integration-by-parts identity** that connects the gradient of Perelman's
`𝓕`-functional to the flow — "Ricci flow IS the gradient flow of `𝓕`".  This file
establishes its discrete core on an arbitrary **weighted** finite graph, the weight playing
Perelman's `e^{−f}dV` measure, all over `ℤ` (`gridSumZ`), `∅`-axiom.

**Setup.**  Vertices `{0,…,n−1}`, symmetric edge weight `w : Nat → Nat → Int`
(`w x y = w y x`; `w x y = 0` encodes a non-edge, so the *graph* is arbitrary; an
`e^{−(f x + f y)/2}`-discretized Perelman weight is one instance):

  * weighted Laplacian `L_w f(x) = Σ_y w(x,y)·(f(y) − f(x))` (`wLap`) — the flow generator;
  * weighted pairing `⟨f,g⟩_w = Σ_xΣ_y w(x,y)·(f(y)−f(x))(g(y)−g(x))` (`wPair`) — the
    carré-du-champ integral;
  * weighted Dirichlet energy `𝓕_w(f) = ⟨f,f⟩_w` (`wDirichlet`) — the discrete
    `𝓕 = ∫|∇f|² e^{−f}dV`.

**The chain delivered** (each ∅-axiom):

  1. `weighted_green` — **the weighted IBP**: `⟨f,g⟩_w = −2·Σ_x g(x)·L_w f(x)`.  With
     `g := μ` the measure this is exactly `∫⟨∇f,∇μ⟩ = −∫Δf·μ`, the identity that converts
     the first variation of `𝓕` into the gradient-flow form `∇𝓕 = −(Ric + Hess f)`.
  2. `dirichlet_first_variation` — the exact (not infinitesimal) variation
     `𝓕(f+h) = 𝓕(f) + 2⟨f,h⟩_w + 𝓕(h)`.
  3. `dirichlet_gradient_identity` — 1 + 2 combined: the linear response of `𝓕` along *any*
     direction `h` is `−4·Σ h·L_w f`, i.e. **`∇𝓕_w = −4·L_w f` — the flow generated by the
     weighted Laplacian IS the gradient flow of the weighted Dirichlet energy**.  This is
     the discrete form of the IBP connecting `∇𝓕` to the flow, proven.
  4. `gradient_flow_descent` — along the flow direction `h := L_w f` the linear term is
     `−4·Σ(L_w f)²`, a manifest SOS rate (`flow_rate_sos`): the discrete
     `d/dt 𝓕 = −‖∇𝓕‖² ≤ 0`, the companion of `perelman_rate_nonneg` (`TensorCalculus` §7).
  5. `wlap_mass_conservation` — `Σ_x L_w f(x) = 0`: the conjugate-measure mass invariance
     (the `∫(4πτ)^{−n/2}e^{−f} = 1` constraint propagates).

The engine is `gridSumZ_antisym_zero` (Fubini reflects an antisymmetric kernel onto its own
negation; doubling cancellation closes — division-free).  **Honest boundary**: this is the
weighted IBP and gradient-flow identity in the discrete weighted-graph category; the smooth
statement on a manifold (with `dV` and diffeomorphism gauge) remains open.
-/

namespace E213.Lib.Math.Geometry.DiscreteCurvature.WeightedGreen

open E213.Meta.Int213
open E213.Lib.Math.Combinatorics.IntGridSum (gridSumZ
  gridSumZ_congr gridSumZ_add gridSumZ_sub gridSumZ_mul_left gridSumZ_nonneg
  gridSumZ_antisym_zero)

/-! ## §1 — the weighted operators -/

/-- Weighted graph Laplacian: `L_w f(x) = Σ_y w(x,y)·(f(y) − f(x))` — the flow generator
    (heat flow in the weighted measure; `w x y = 0` for non-edges). -/
def wLap (n : Nat) (w : Nat → Nat → Int) (f : Nat → Int) (x : Nat) : Int :=
  gridSumZ n (fun y => w x y * (f y - f x))

/-- Weighted pairing (carré-du-champ integral):
    `⟨f,g⟩_w = Σ_xΣ_y w(x,y)·(f(y)−f(x))·(g(y)−g(x))`. -/
def wPair (n : Nat) (w : Nat → Nat → Int) (f g : Nat → Int) : Int :=
  gridSumZ n (fun x => gridSumZ n (fun y => w x y * ((f y - f x) * (g y - g x))))

/-- Weighted Dirichlet energy `𝓕_w(f) = ⟨f,f⟩_w` — the discrete Perelman
    `𝓕 = ∫|∇f|²e^{−f}dV` (weight as measure). -/
def wDirichlet (n : Nat) (w : Nat → Nat → Int) (f : Nat → Int) : Int := wPair n w f f

/-! ## §2 — the weighted Green / integration-by-parts identity -/

/-- Push the test function inside the Laplacian's sum: `Σ_x g(x)·L_w f(x)` as a double sum. -/
theorem glap_double (n : Nat) (w : Nat → Nat → Int) (f g : Nat → Int) :
    gridSumZ n (fun x => g x * wLap n w f x)
      = gridSumZ n (fun x => gridSumZ n (fun y => w x y * (g x * (f y - f x)))) :=
  gridSumZ_congr n _ _ (fun x _ => by
    show g x * gridSumZ n (fun y => w x y * (f y - f x)) = _
    rw [← gridSumZ_mul_left n (g x) (fun y => w x y * (f y - f x))]
    exact gridSumZ_congr n _ _ (fun y _ => by ring_intZ))

/-- ★★★★★ **The weighted integration-by-parts (Green) identity**:

      `⟨f,g⟩_w = −2·Σ_x g(x)·L_w f(x)`    (symmetric `w`).

    With `g := μ` the vertex measure this is the discrete
    `∫⟨∇f,∇μ⟩ = −∫(Δf)·μ` — for `μ = e^{−f}` exactly Perelman's
    `∫Δf·e^{−f} = ∫|∇f|²e^{−f}`, the identity that turns the first variation of
    `𝓕(g,f) = ∫(R+|∇f|²)e^{−f}dV` into the gradient-flow form `∇𝓕 = −(Ric+Hess f)`.
    Engine: the symmetrized kernel `w·(f y−f x)(g y+g x)` is antisymmetric, so its double
    sum vanishes (`gridSumZ_antisym_zero`); what is left is the pairing against `−2·L_w`. -/
theorem weighted_green (n : Nat) (w : Nat → Nat → Int)
    (hw : ∀ x y, w x y = w y x) (f g : Nat → Int) :
    wPair n w f g = -(2 * gridSumZ n (fun x => g x * wLap n w f x)) := by
  have hU := glap_double n w f g
  have hV : gridSumZ n (fun x => gridSumZ n (fun y =>
      w x y * ((f y - f x) * (g y + g x)))) = 0 :=
    gridSumZ_antisym_zero n (fun x y => w x y * ((f y - f x) * (g y + g x)))
      (fun x y => by
        show w x y * ((f y - f x) * (g y + g x))
            = -(w y x * ((f x - f y) * (g x + g y)))
        rw [hw x y]; ring_intZ)
  have hsplit : wPair n w f g
      = gridSumZ n (fun x => gridSumZ n (fun y => w x y * ((f y - f x) * (g y + g x))))
        - 2 * gridSumZ n (fun x => gridSumZ n (fun y => w x y * (g x * (f y - f x)))) := by
    show gridSumZ n (fun x => gridSumZ n (fun y => w x y * ((f y - f x) * (g y - g x)))) = _
    rw [← gridSumZ_mul_left n 2
          (fun x => gridSumZ n (fun y => w x y * (g x * (f y - f x)))),
        ← gridSumZ_sub n
          (fun x => gridSumZ n (fun y => w x y * ((f y - f x) * (g y + g x))))
          (fun x => 2 * gridSumZ n (fun y => w x y * (g x * (f y - f x))))]
    apply gridSumZ_congr
    intro x _
    dsimp only
    rw [← gridSumZ_mul_left n 2 (fun y => w x y * (g x * (f y - f x))),
        ← gridSumZ_sub n
          (fun y => w x y * ((f y - f x) * (g y + g x)))
          (fun y => 2 * (w x y * (g x * (f y - f x))))]
    exact gridSumZ_congr n _ _ (fun y _ => by ring_intZ)
  rw [hsplit, hV, ← hU]
  exact Order.zero_sub _

/-- ★★★ **Weighted mass conservation**: `Σ_x L_w f(x) = 0` — the weighted flow
    redistributes without creating mass (the discrete conjugate-heat-measure invariance,
    the constraint the `(4πτ)^{−n/2}e^{−f}` normalization enforces in the continuum). -/
theorem wlap_mass_conservation (n : Nat) (w : Nat → Nat → Int)
    (hw : ∀ x y, w x y = w y x) (f : Nat → Int) :
    gridSumZ n (fun x => wLap n w f x) = 0 := by
  show gridSumZ n (fun x => gridSumZ n (fun y => w x y * (f y - f x))) = 0
  exact gridSumZ_antisym_zero n (fun x y => w x y * (f y - f x))
    (fun x y => by
      show w x y * (f y - f x) = -(w y x * (f x - f y))
      rw [hw x y]; ring_intZ)

/-! ## §3 — the first variation: `∇𝓕_w = −4·L_w` (the flow IS the gradient flow) -/

/-- The exact (not just infinitesimal) first variation of the weighted Dirichlet energy:
    `𝓕_w(f+h) = 𝓕_w(f) + 2⟨f,h⟩_w + 𝓕_w(h)` — pure bilinearity of the pairing. -/
theorem dirichlet_first_variation (n : Nat) (w : Nat → Nat → Int) (f h : Nat → Int) :
    wDirichlet n w (fun x => f x + h x)
      = wDirichlet n w f + 2 * wPair n w f h + wDirichlet n w h := by
  have hpoint : ∀ x, x < n →
      gridSumZ n (fun y => w x y *
          ((f y + h y - (f x + h x)) * (f y + h y - (f x + h x))))
        = gridSumZ n (fun y => w x y * ((f y - f x) * (f y - f x)))
          + (2 * gridSumZ n (fun y => w x y * ((f y - f x) * (h y - h x)))
             + gridSumZ n (fun y => w x y * ((h y - h x) * (h y - h x)))) := by
    intro x _
    rw [← gridSumZ_mul_left n 2 (fun y => w x y * ((f y - f x) * (h y - h x))),
        ← gridSumZ_add n
          (fun y => 2 * (w x y * ((f y - f x) * (h y - h x))))
          (fun y => w x y * ((h y - h x) * (h y - h x))),
        ← gridSumZ_add n
          (fun y => w x y * ((f y - f x) * (f y - f x)))
          (fun y => 2 * (w x y * ((f y - f x) * (h y - h x)))
                    + w x y * ((h y - h x) * (h y - h x)))]
    exact gridSumZ_congr n _ _ (fun y _ => by ring_intZ)
  have houter := gridSumZ_congr n _ _ hpoint
  have hsum1 := gridSumZ_add n
    (fun x => gridSumZ n (fun y => w x y * ((f y - f x) * (f y - f x))))
    (fun x => 2 * gridSumZ n (fun y => w x y * ((f y - f x) * (h y - h x)))
              + gridSumZ n (fun y => w x y * ((h y - h x) * (h y - h x))))
  have hsum2 := gridSumZ_add n
    (fun x => 2 * gridSumZ n (fun y => w x y * ((f y - f x) * (h y - h x))))
    (fun x => gridSumZ n (fun y => w x y * ((h y - h x) * (h y - h x))))
  have hsum3 := gridSumZ_mul_left n 2
    (fun x => gridSumZ n (fun y => w x y * ((f y - f x) * (h y - h x))))
  show gridSumZ n (fun x => gridSumZ n (fun y =>
      w x y * ((f y + h y - (f x + h x)) * (f y + h y - (f x + h x))))) = _
  rw [houter, hsum1, hsum2, hsum3]
  show gridSumZ n (fun x => gridSumZ n (fun y => w x y * ((f y - f x) * (f y - f x))))
        + (2 * gridSumZ n (fun x => gridSumZ n (fun y =>
              w x y * ((f y - f x) * (h y - h x))))
           + gridSumZ n (fun x => gridSumZ n (fun y =>
              w x y * ((h y - h x) * (h y - h x)))))
      = gridSumZ n (fun x => gridSumZ n (fun y => w x y * ((f y - f x) * (f y - f x))))
        + 2 * gridSumZ n (fun x => gridSumZ n (fun y =>
            w x y * ((f y - f x) * (h y - h x))))
        + gridSumZ n (fun x => gridSumZ n (fun y =>
            w x y * ((h y - h x) * (h y - h x))))
  ring_intZ

/-- ★★★★★ **The gradient identity — the flow IS the gradient flow of `𝓕_w`** (discrete):

      `𝓕_w(f + h) = 𝓕_w(f) − 4·Σ_x h(x)·L_w f(x) + 𝓕_w(h)`.

    The linear response of the weighted Dirichlet energy along *any* direction `h` is the
    pairing against `−4·L_w f`: the gradient of `𝓕_w` is (a positive multiple of) the
    weighted Laplacian, so the flow `∂_t f = L_w f` descends `𝓕_w` at rate `‖∇𝓕_w‖²` —
    the discrete form of "`∇𝓕 = −(Ric + Hess f)`, Ricci flow is the gradient flow of `𝓕`".
    First variation + the weighted IBP (`weighted_green`). -/
theorem dirichlet_gradient_identity (n : Nat) (w : Nat → Nat → Int)
    (hw : ∀ x y, w x y = w y x) (f h : Nat → Int) :
    wDirichlet n w (fun x => f x + h x)
      = wDirichlet n w f
        - 4 * gridSumZ n (fun x => h x * wLap n w f x)
        + wDirichlet n w h := by
  rw [dirichlet_first_variation n w f h, weighted_green n w hw f h]
  ring_intZ

/-- The descent rate is a manifest SOS: `0 ≤ Σ_x (L_w f(x))²` — the discrete
    `‖∇𝓕‖² ≥ 0`, companion of `perelman_rate_nonneg` (`TensorCalculus` §7). -/
theorem flow_rate_sos (n : Nat) (w : Nat → Nat → Int) (f : Nat → Int) :
    0 ≤ gridSumZ n (fun x => wLap n w f x * wLap n w f x) :=
  gridSumZ_nonneg n _ (fun _ _ => int_sq_nonneg _)

/-- ★★★★ **Gradient-flow descent**: along the flow direction `h := L_w f` the energy's
    exact variation is `−4·Σ(L_w f)²` plus the (second-order) energy of the step —
    the discrete `d/dt 𝓕 = −‖∇𝓕‖²`, with the rate a non-negative SOS (`flow_rate_sos`). -/
theorem gradient_flow_descent (n : Nat) (w : Nat → Nat → Int)
    (hw : ∀ x y, w x y = w y x) (f : Nat → Int) :
    wDirichlet n w (fun x => f x + wLap n w f x)
      = wDirichlet n w f
        - 4 * gridSumZ n (fun x => wLap n w f x * wLap n w f x)
        + wDirichlet n w (wLap n w f)
    ∧ 0 ≤ gridSumZ n (fun x => wLap n w f x * wLap n w f x) :=
  ⟨dirichlet_gradient_identity n w hw f (wLap n w f), flow_rate_sos n w f⟩

/-- The energy is bounded below by `0` for a non-negative weight — with
    `gradient_flow_descent` the monovariant + bounded-below pair (the completeness-LOOP
    input of `CompletenessLoop`). -/
theorem wdirichlet_nonneg (n : Nat) (w : Nat → Nat → Int)
    (hpos : ∀ x y, 0 ≤ w x y) (f : Nat → Int) :
    0 ≤ wDirichlet n w f := by
  show 0 ≤ gridSumZ n (fun x => gridSumZ n (fun y =>
      w x y * ((f y - f x) * (f y - f x))))
  apply gridSumZ_nonneg
  intro x _
  apply gridSumZ_nonneg
  intro y _
  have h := OrderMul.mul_le_mul_left_nonneg (int_sq_nonneg (f y - f x)) (w x y) (hpos x y)
  rwa [Int.mul_zero] at h

end E213.Lib.Math.Geometry.DiscreteCurvature.WeightedGreen
