import E213.Lib.Math.Algebra.CayleyDickson.Integer.EisensteinResidue
import E213.Lib.Math.Algebra.CayleyDickson.Integer.EisensteinConverse

/-!
# The residue prime exists unconditionally for `p ≡ 1 (mod 3)` (rung 2c, ∅-axiom)

★★★★★ `exists_residue_prime` : for a prime `p ≡ 1 (mod 3)`, there is a **norm-`p` Eisenstein prime**
`d` (`‖d‖² = p`) and a rational integer `x` with `ω ≡ x (mod d)`, so that **every** `α ∈ ℤ[ω]` reduces
mod `d` to the rational integer `α.re + α.im·x`:

  `∃ d x, ‖d‖² = p  ∧  ∀ α, α ≡ ↑(α.re + α.im·x)  (mod d)`.

This discharges the hypothesis of `EisensteinResidue.reduce_to_int` from primality alone: the cube root
`x` comes from `EisensteinConverse.cube_root_exists` (`p ∣ x²+x+1`), the norm-`p` prime `d ∣ (x − ω)`
from `EisensteinSplit.split_dvd`.  So `ℤ[ω]/(d)` is generated by the image of `ℤ` — a quotient of
`ℤ/p` — completing rung 2 toward the cubic character `(·/d)₃` (the residue ring is `𝔽_p`, where the
character becomes the rational cubic power-residue of `ModArith/CubicResidue`).  ∅-axiom (the Nat→ℤ
cube-root cast reuses the pure pattern of `eisenstein_split_converse`).
-/

namespace E213.Lib.Math.Algebra.CayleyDickson.Integer.EisensteinResiduePrime

open E213.Lib.Math.Algebra.CayleyDickson.Integer.ZOmega (ZOmega)
open E213.Lib.Math.Algebra.CayleyDickson.Integer.ZOmega.ZOmega
open E213.Lib.Math.Algebra.CayleyDickson.Integer.EisensteinCongruence (ModEq)
open E213.Lib.Math.Algebra.CayleyDickson.Integer.EisensteinResidue (exists_residue_prime_int)
open E213.Lib.Math.Algebra.CayleyDickson.Integer.EisensteinConverse (cube_root_exists three_mul_eq_of_mod)
open E213.Lib.Math.NumberTheory.PolyRoot (nat_dvd_to_int int_dvd_to_nat)
open E213.Tactic.Pow213 (le_of_dvd_pos)

/-- ★★★★★ **The residue prime exists for every prime `p ≡ 1 (mod 3)`.**  There is a norm-`p`
    Eisenstein prime `d` and a rational integer `x` with `ω ≡ x (mod d)`, so every `α ≡ ↑(α.re +
    α.im·x) (mod d)` — the residue ring `ℤ[ω]/(d)` is generated by `ℤ` (a quotient of `ℤ/p`), the
    home `𝔽_p` of the cubic character.  Cube root from `cube_root_exists`, norm-`p` prime from
    `split_dvd`, propagation from `reduce_to_int`.  ∅-axiom. -/
theorem exists_residue_prime (p : Nat) (hp : 1 < p) (hpr : ∀ d, d ∣ p → d = 1 ∨ d = p)
    (hmod : p % 3 = 1) :
    ∃ (d : ZOmega) (x : Int),
      d.normSq = (p : Int) ∧ ∀ α, ModEq d α (ofInt (α.re + α.im * x)) := by
  obtain ⟨m, hm⟩ := three_mul_eq_of_mod p hmod
  obtain ⟨x, hx⟩ := cube_root_exists p m hp hpr hm
  have hxcast : ((x * x + x + 1 : Nat) : Int) = (x : Int) * (x : Int) + (x : Int) + 1 := rfl
  have hxint : (p : Int) ∣ ((x : Int) * (x : Int) + (x : Int) + 1) := by
    rw [← hxcast]; exact nat_dvd_to_int p _ (by rw [Int.natAbs_ofNat]; exact hx)
  have hp1 : ¬ ((p : Int) ∣ (1 : Int)) := by
    intro hd
    have hle := le_of_dvd_pos p (Int.natAbs (1 : Int)) (by decide) (int_dvd_to_nat p 1 hd)
    rw [show Int.natAbs (1 : Int) = 1 from rfl] at hle
    exact absurd hle (Nat.not_le.mpr hp)
  obtain ⟨d, hdn, hd_red⟩ := exists_residue_prime_int p hp hpr hp1 (x : Int) hxint
  exact ⟨d, x, hdn, hd_red⟩

end E213.Lib.Math.Algebra.CayleyDickson.Integer.EisensteinResiduePrime
