import E213.Lib.Math.Algebra.CayleyDickson.Integer.EisensteinSplit
import E213.Lib.Math.Algebra.CayleyDickson.Integer.EisensteinCongruence

/-!
# `ℤ[ω]/(π)` is generated by `ℤ` — reduction to rational integers (rung 2b, ∅-axiom)

★★★★ `reduce_to_int` : if `ω ≡ r (mod π)` for a rational integer `r`, then **every** `α ∈ ℤ[ω]`
is congruent mod `π` to the rational integer `α.re + α.im·r`:

  `α ≡ ↑(α.re + α.im·r)  (mod π)`.

This is the algebraic heart of the residue-field isomorphism `ℤ[ω]/(π) ≅ 𝔽_p` (rung 2 toward cubic
reciprocity): once `ω` is congruent to an integer mod `π` (which holds when `N(π) = p ≡ 1 mod 3`,
since then `x² + x + 1 ≡ 0 (mod p)` has a root `r ≡ ω` — `ModArith/EisensteinCubeRoot`), the residue
ring is generated by the image of `ℤ`, hence is a quotient of `ℤ/p`.  The cubic character `(α/π)₃`
thereby reduces to a rational power-residue computation — the weld to
`ModArith/CubicResidue.cube_iff_three_dvd_dlog`.

The proof is the `ℤ[ω] = ℤ ⊕ ℤω` decomposition (`decomp`) pushed through the congruence: replace the
`ω` factor by `r` (`EisensteinCongruence.mul_left`), then collapse the rational part with the `ofInt`
ring-hom laws (`ofInt_add`, `ofInt_mul`).  ∅-axiom throughout.
-/

namespace E213.Lib.Math.Algebra.CayleyDickson.Integer.EisensteinResidue

open E213.Lib.Math.Algebra.CayleyDickson.Integer.ZOmega (ZOmega)
open E213.Lib.Math.Algebra.CayleyDickson.Integer.ZOmega.ZOmega
open E213.Lib.Math.Algebra.CayleyDickson.Integer.EisensteinSplit (ofInt_mul)
open E213.Lib.Math.Algebra.CayleyDickson.Integer.EisensteinCongruence (ModEq refl add_compat mul_left)
open E213.Meta.Int213 (zero_mul mul_one)
open E213.Meta.Int213 renaming zero_add → int_zero_add
open E213.Meta.Int213.Order (sub_zero)

/-- **The `ℤ[ω] = ℤ ⊕ ℤω` decomposition** — `α = ↑α.re + ↑α.im · ω`.  Componentwise: `↑α.im · ω =
    ⟨0, α.im⟩`, so the sum recovers `⟨α.re, α.im⟩`. -/
theorem decomp (a : ZOmega) : a = ofInt a.re + ofInt a.im * Omega := by
  apply ZOmega.ext
  · show a.re = a.re + (a.im * 0 - 0 * 1)
    rw [Int.mul_zero, zero_mul, sub_zero, Int.add_zero]
  · show a.im = 0 + (a.im * 1 + 0 * 0 - 0 * 1)
    rw [mul_one, zero_mul, zero_mul, Int.add_zero, sub_zero, int_zero_add]

/-- `↑a + ↑b = ↑(a + b)` — the `ofInt : ℤ → ℤ[ω]` embedding is additive (componentwise). -/
theorem ofInt_add (a b : Int) : ofInt a + ofInt b = ofInt (a + b) := by
  apply ZOmega.ext <;> rfl

/-- ★★★★ **Reduction to rational integers in `ℤ[ω]/(π)`** — if `ω ≡ r (mod π)`, every `α` is
    congruent to the rational integer `α.re + α.im·r`: `α ≡ ↑(α.re + α.im·r) (mod π)`.  So the residue
    ring `ℤ[ω]/(π)` is generated by the image of `ℤ` — the structural core of `ℤ[ω]/(π) ≅ 𝔽_p`.
    Decomposition `α = ↑α.re + ↑α.im·ω`, then replace `ω` by `r` through the congruence and collapse
    with `ofInt_mul`/`ofInt_add`.  ∅-axiom. -/
theorem reduce_to_int {π : ZOmega} {r : Int} (h : ModEq π Omega (ofInt r)) (α : ZOmega) :
    ModEq π α (ofInt (α.re + α.im * r)) := by
  have hd := decomp α
  have h1 : ModEq π (ofInt α.im * Omega) (ofInt α.im * ofInt r) := mul_left h (ofInt α.im)
  have h2 := add_compat (refl π (ofInt α.re)) h1
  rw [← ofInt_mul, ofInt_add] at h2
  rw [← hd] at h2
  exact h2

end E213.Lib.Math.Algebra.CayleyDickson.Integer.EisensteinResidue
