import E213.Lib.Math.Algebra.CayleyDickson.Integer.EisensteinSplit
import E213.Lib.Math.Algebra.CayleyDickson.Integer.EisensteinCongruence
import E213.Lib.Math.Algebra.CayleyDickson.Integer.EisensteinDivStep

/-!
# `ℤ[ω]/(π)` is generated by `ℤ` — reduction to rational integers (rung 2b, ∅-axiom)

★★★★ `reduce_to_int` : if `ω ≡ r (mod π)` for a rational integer `r`, then **every** `α ∈ ℤ[ω]`
is congruent mod `π` to the rational integer `α.re + α.im·r`:

  `α ≡ ↑(α.re + α.im·r)  (mod π)`.

This is the algebraic heart of the residue-field isomorphism `ℤ[ω]/(π) ≅ 𝔽_p` (rung 2 toward cubic
reciprocity): once `ω` is congruent to an integer mod `π` (which holds when `N(π) = p ≡ 1 mod 3`,
since then `x² + x + 1 ≡ 0 (mod p)` has a root `r ≡ ω` — `ModArith/EisensteinCubeRoot`), the residue
ring is generated by the image of `ℤ`, hence is a quotient of `ℤ/p`.  The cubic character `(α/π)₃`
thereby reduces to a rational power-residue computation — the weld to
`ModArith/CubicResidue.cube_iff_three_dvd_dlog`.

The proof is the `ℤ[ω] = ℤ ⊕ ℤω` decomposition (`decomp`) pushed through the congruence: replace the
`ω` factor by `r` (`EisensteinCongruence.mul_left`), then collapse the rational part with the `ofInt`
ring-hom laws (`ofInt_add`, `ofInt_mul`).  ∅-axiom throughout.
-/

namespace E213.Lib.Math.Algebra.CayleyDickson.Integer.EisensteinResidue

open E213.Lib.Math.Algebra.CayleyDickson.Integer.ZOmega (ZOmega)
open E213.Lib.Math.Algebra.CayleyDickson.Integer.ZOmega.ZOmega
open E213.Lib.Math.Algebra.CayleyDickson.Integer.EisensteinSplit (ofInt_mul split_dvd)
open E213.Lib.Math.Algebra.CayleyDickson.Integer.EisensteinCongruence (ModEq refl symm add_compat mul_left)
open E213.Lib.Math.Algebra.CayleyDickson.Integer.EisensteinDivStep (mul_conj_self)
open E213.Meta.Algebra213.Ring213 (mul_assoc)
open E213.Meta.Int213 (zero_mul mul_one)
open E213.Meta.Int213 renaming zero_add → int_zero_add
open E213.Meta.Int213.Order (sub_zero)

/-- **The `ℤ[ω] = ℤ ⊕ ℤω` decomposition** — `α = ↑α.re + ↑α.im · ω`.  Componentwise: `↑α.im · ω =
    ⟨0, α.im⟩`, so the sum recovers `⟨α.re, α.im⟩`. -/
theorem decomp (a : ZOmega) : a = ofInt a.re + ofInt a.im * Omega := by
  apply ZOmega.ext
  · show a.re = a.re + (a.im * 0 - 0 * 1)
    rw [Int.mul_zero, zero_mul, sub_zero, Int.add_zero]
  · show a.im = 0 + (a.im * 1 + 0 * 0 - 0 * 1)
    rw [mul_one, zero_mul, zero_mul, Int.add_zero, sub_zero, int_zero_add]

/-- `↑a + ↑b = ↑(a + b)` — the `ofInt : ℤ → ℤ[ω]` embedding is additive (componentwise). -/
theorem ofInt_add (a b : Int) : ofInt a + ofInt b = ofInt (a + b) := by
  apply ZOmega.ext <;> rfl

/-- ★★★★ **Reduction to rational integers in `ℤ[ω]/(π)`** — if `ω ≡ r (mod π)`, every `α` is
    congruent to the rational integer `α.re + α.im·r`: `α ≡ ↑(α.re + α.im·r) (mod π)`.  So the residue
    ring `ℤ[ω]/(π)` is generated by the image of `ℤ` — the structural core of `ℤ[ω]/(π) ≅ 𝔽_p`.
    Decomposition `α = ↑α.re + ↑α.im·ω`, then replace `ω` by `r` through the congruence and collapse
    with `ofInt_mul`/`ofInt_add`.  ∅-axiom. -/
theorem reduce_to_int {π : ZOmega} {r : Int} (h : ModEq π Omega (ofInt r)) (α : ZOmega) :
    ModEq π α (ofInt (α.re + α.im * r)) := by
  have hd := decomp α
  have h1 : ModEq π (ofInt α.im * Omega) (ofInt α.im * ofInt r) := mul_left h (ofInt α.im)
  have h2 := add_compat (refl π (ofInt α.re)) h1
  rw [← ofInt_mul, ofInt_add] at h2
  rw [← hd] at h2
  exact h2

/-- The split's divisibility `d ∣ (x − ω) = ⟨x, −1⟩` says `ω ≡ x (mod d)`: `ModEq d ω ↑x`.  (`x − ω =
    ↑x + −ω`, so `d ∣ (x − ω)` is `ModEq d ↑x ω`; symmetry flips it.)  ∅-axiom. -/
theorem omega_cong_of_dvd {d : ZOmega} {x : Int} (h : d ∣ (⟨x, -1⟩ : ZOmega)) :
    ModEq d Omega (ofInt x) := by
  have key : (⟨x, -1⟩ : ZOmega) = ofInt x + -Omega := by
    apply ZOmega.ext
    · show x = x + -(0 : Int)
      rw [Int.neg_zero, Int.add_zero]
    · show (-1 : Int) = 0 + -(1 : Int)
      rw [int_zero_add]
  have h2 : d ∣ (ofInt x + -Omega) := key ▸ h
  exact symm h2

/-- ★★★★ **The residue prime, given a cube root** — for a prime `p` with `p ∣ x²+x+1` (`x ≡ ω`), there
    is a norm-`p` Eisenstein prime `d` with `ω ≡ x (mod d)`, hence (by `reduce_to_int`) **every** `α ∈
    ℤ[ω]` reduces mod `d` to the rational integer `α.re + α.im·x`.  `split_dvd` gives `d ∣ (x − ω)`,
    `omega_cong_of_dvd` reads it as `ω ≡ x`, and `reduce_to_int` propagates it.  ∅-axiom. -/
theorem exists_residue_prime_int (p : Nat) (hp2 : 2 ≤ p) (hpr : ∀ m, m ∣ p → m = 1 ∨ m = p)
    (hp1 : ¬ ((p : Int) ∣ (1 : Int))) (x : Int) (hx : (p : Int) ∣ (x * x + x + 1)) :
    ∃ d : ZOmega, d.normSq = (p : Int) ∧ ∀ α, ModEq d α (ofInt (α.re + α.im * x)) := by
  obtain ⟨d, hdn, hdω⟩ := split_dvd p hp2 hpr hp1 x hx
  exact ⟨d, hdn, fun α => reduce_to_int (omega_cong_of_dvd hdω) α⟩

/-! ## The rational weld — `ℤ/(‖d‖²) → ℤ[ω]/(d)`

`reduce_to_int` sends every `α` to a rational integer mod `d`; these lemmas send rational
congruences *into* `ℤ[ω]` mod `d`, so the residue ring is a quotient of `ℤ/(‖d‖²) = ℤ/p`.  Together
they weld the cubic character on `ℤ[ω]/(d)` to the rational cubic power-residue. -/

/-- `↑(-a) = -↑a`. -/
theorem ofInt_neg (a : Int) : ofInt (-a) = -ofInt a := by
  apply ZOmega.ext
  · rfl
  · show (0 : Int) = -0; rw [Int.neg_zero]

/-- `d ∣ ↑‖d‖²` — `d` divides (the embedding of) its own norm, since `d · conj d = ↑‖d‖²`.  For a
    norm-`p` prime this is `d ∣ ↑p`, the reason congruences mod `p` descend to mod `d`. -/
theorem dvd_ofInt_norm (d : ZOmega) : d ∣ ofInt d.normSq :=
  ⟨d.conj, (mul_conj_self d).symm⟩

/-- The `ofInt` embedding respects divisibility: `m ∣ n` in `ℤ` ⟹ `↑m ∣ ↑n` in `ℤ[ω]`. -/
theorem ofInt_dvd {m n : Int} (h : m ∣ n) : ofInt m ∣ ofInt n := by
  obtain ⟨c, rfl⟩ := h; exact ⟨ofInt c, ofInt_mul m c⟩

/-- Transitivity of `ℤ[ω]`-divisibility. -/
theorem zdvd_trans {a b c : ZOmega} (h1 : a ∣ b) (h2 : b ∣ c) : a ∣ c := by
  obtain ⟨s, rfl⟩ := h1; obtain ⟨t, rfl⟩ := h2; exact ⟨s * t, mul_assoc a s t⟩

/-- ★★★ **Rational congruences descend** — if `‖d‖²` divides `a − b` in `ℤ`, then `↑a ≡ ↑b (mod d)`
    in `ℤ[ω]`.  Since `‖d‖² = p` for a residue prime, congruence mod `p` of rational integers becomes
    congruence mod `d`: the ring map `ℤ/p → ℤ[ω]/(d)`.  Via `d ∣ ↑‖d‖² ∣ ↑(a−b) = ↑a + -↑b`.
    ∅-axiom. -/
theorem modEq_ofInt_of_dvd {d : ZOmega} {a b : Int} (h : d.normSq ∣ (a - b)) :
    ModEq d (ofInt a) (ofInt b) := by
  show d ∣ (ofInt a + -ofInt b)
  have e1 : ofInt a + -ofInt b = ofInt (a - b) := by
    rw [← ofInt_neg, ofInt_add, Int.sub_eq_add_neg]
  rw [e1]
  exact zdvd_trans (dvd_ofInt_norm d) (ofInt_dvd h)

end E213.Lib.Math.Algebra.CayleyDickson.Integer.EisensteinResidue
