#!/usr/bin/env python3
"""Full Expr-level call-graph extractor for E213.

Walks every `E213.*` constant's elaborated proof body and counts
every `Expr.const` reference.  Unlike G92's surface-syntax citation
graph (which only captures `rw [..]`, `apply <name>`, `exact <name>`),
this captures the COMPLETE dependency graph including:

  · all lemmas used (via rw/apply/exact AND term-mode parts),
  · all definitions referenced (inductives, recursors, projectors),
  · all type-level references (the proof body's elaborated form
    interleaves type info with term computation).

Pipeline:
  1. Write probe `lean/E213/_AstCallGraphProbe.lean` (cached .olean
     module imports + the canonical scanner body).
  2. Build with `lake build`; the probe's `#eval` dumps TSV rows of
     form  E<TAB>caller<TAB>callee<TAB>count.
  3. Parse the build log, aggregate.

Usage:
    tools/ast_callgraph_scan.py
    tools/ast_callgraph_scan.py --no-build
    tools/ast_callgraph_scan.py --report-only
"""
from __future__ import annotations
import re, sys, subprocess, pathlib, collections, argparse

ROOT       = pathlib.Path(__file__).resolve().parent.parent
LEAN_DIR   = ROOT / "lean"
PROBE      = LEAN_DIR / "E213" / "_AstCallGraphProbe.lean"
BODY_TMPL  = ROOT / "tools" / "ast_callgraph_body.lean"
LOG_PATH   = ROOT / "tools" / "_ast_callgraph_last.log"
ROWS_PATH  = ROOT / "tools" / "_ast_callgraph_edges.tsv"

PROBE_HEADER = """\
/-
Ephemeral AST call-graph extractor.  Auto-generated by
tools/ast_callgraph_scan.py from tools/ast_callgraph_body.lean.
For every `E213.*` constant with a `value?`, walks the elaborated
Expr and emits one row per (caller, callee, count) triple.
-/
import Lean
"""


def cached_modules() -> list[str]:
    base = LEAN_DIR / ".lake" / "build" / "lib" / "E213"
    if not base.exists():
        sys.exit("error: no cached .olean tree; run `lake build` first")
    mods = []
    for p in base.rglob("*.olean"):
        rel = p.relative_to(LEAN_DIR / ".lake" / "build" / "lib")
        name = ".".join(rel.with_suffix("").parts)
        if name.endswith(("_AstFoldScanProbe", "_AxiomScanProbe",
                          "_AstCallGraphProbe", "_DepPurityProbe")):
            continue
        mods.append(name)
    return sorted(mods)


def write_probe() -> None:
    if not BODY_TMPL.exists():
        sys.exit(f"error: missing scanner body at {BODY_TMPL}")
    imports = "\n".join(f"import {m}" for m in cached_modules())
    body = BODY_TMPL.read_text()
    PROBE.write_text(PROBE_HEADER + imports + "\n\n" + body)


def build() -> str:
    r = subprocess.run(
        ["lake", "build", "E213._AstCallGraphProbe"],
        cwd=LEAN_DIR, capture_output=True, text=True,
    )
    log = r.stdout + r.stderr
    LOG_PATH.write_text(log)
    if "AST-CALLGRAPH-END" not in log:
        sys.stderr.write(log[-4000:])
        sys.exit("error: probe did not finish; see " + str(LOG_PATH))
    return log


def extract_edges(log: str):
    edges = []
    inside = False
    for line in log.splitlines():
        if "AST-CALLGRAPH-BEGIN" in line:
            inside = True; continue
        if "AST-CALLGRAPH-END" in line:
            inside = False; continue
        if not inside or not line.startswith("E\t"):
            continue
        parts = line.split("\t", 3)
        if len(parts) < 4:
            continue
        _, caller, callee, count = parts
        try:
            edges.append((caller, callee, int(count)))
        except ValueError:
            continue
    return edges


def report(edges):
    callees = collections.Counter()       # total invocations
    callee_callers = collections.defaultdict(set)
    caller_outdeg = collections.Counter()
    caller_outdistinct = collections.defaultdict(set)
    for caller, callee, count in edges:
        callees[callee] += count
        callee_callers[callee].add(caller)
        caller_outdeg[caller] += count
        caller_outdistinct[caller].add(callee)

    print(f"# Total edges: {len(edges)}")
    print(f"# Distinct callers (E213.*): {len(caller_outdeg)}")
    print(f"# Distinct callees: {len(callees)}")
    total_inv = sum(callees.values())
    print(f"# Total const-invocations: {total_inv}\n")

    # E213-internal vs external callees
    e213_internal = sum(c for n, c in callees.items() if n.startswith('E213.'))
    external = total_inv - e213_internal
    print(f"# E213-internal callee invocations:  {e213_internal:>8}  ({100*e213_internal/total_inv:.1f}%)")
    print(f"# External callee invocations:        {external:>8}  ({100*external/total_inv:.1f}%)")
    print()

    print("## Top 30 callees by total invocation (all)")
    for n, c in callees.most_common(30):
        nc = len(callee_callers[n])
        print(f"  {c:>7}  ({nc:>5} callers)  {n}")
    print()

    print("## Top 20 callees by distinct-caller count (= breadth)")
    rank_br = sorted(callee_callers.items(), key=lambda kv: -len(kv[1]))[:20]
    for n, cs in rank_br:
        print(f"  {len(cs):>5} callers  ({callees[n]:>7} total)  {n}")
    print()

    print("## Top 20 E213-internal callees by distinct-caller count")
    int_rank = sorted(
        ((n, cs) for n, cs in callee_callers.items() if n.startswith('E213.')),
        key=lambda kv: -len(kv[1]))[:20]
    for n, cs in int_rank:
        print(f"  {len(cs):>4} callers  ({callees[n]:>6} total)  {n}")
    print()

    # Caller-side analysis
    print("## Top 20 callers by total const-invocations (proof-term mass)")
    for caller, n in caller_outdeg.most_common(20):
        ndistinct = len(caller_outdistinct[caller])
        # shorten the name
        short = caller.split('.', 4)
        sn = '.'.join(short[-3:]) if len(short) > 3 else caller
        print(f"  invocations={n:>6}  distinct={ndistinct:>4}  ...{sn}")
    print()

    # Compare to surface-cite (G92) — how much hidden dependency?
    # Lean-core ratio bands
    print("## Callee namespace distribution (where const definitions live)")
    ns_count = collections.Counter()
    for n, c in callees.items():
        root = n.split('.')[0]
        ns_count[root] += c
    for ns, c in ns_count.most_common(15):
        print(f"  {c:>9}  {ns}")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--no-build", action="store_true")
    ap.add_argument("--report-only", action="store_true")
    args = ap.parse_args()
    if args.report_only:
        edges = []
        for line in ROWS_PATH.read_text().splitlines():
            parts = line.split("\t", 2)
            if len(parts) == 3:
                edges.append((parts[0], parts[1], int(parts[2])))
    else:
        if not args.no_build:
            write_probe()
            log = build()
            PROBE.unlink(missing_ok=True)
        else:
            log = LOG_PATH.read_text()
        edges = extract_edges(log)
        ROWS_PATH.write_text(
            "\n".join("\t".join((c1, c2, str(n)))
                      for c1, c2, n in edges) + "\n")
    report(edges)
    return 0


if __name__ == "__main__":
    sys.exit(main())
