#!/usr/bin/env python3
"""AST fold/recursor scanner driver + motif clusterer for E213.

Pipeline
--------
1.  Generate `lean/E213/_AstFoldScanProbe.lean` by concatenating
    `import Lean` + cached `.olean` module imports +
    `tools/ast_fold_scan_body.lean` (the canonical scanner body).
2.  Run `lake build E213._AstFoldScanProbe`; the probe's `#eval`
    dumps tab-separated arg rows of every fold / recursor call
    site found in E213 proof terms.
3.  Parse the build log, cluster step-function (argIdx=2) rows by
    canonical-skeleton hash (strict) and by operator multiset
    (loose).  Print top motifs.

Usage
-----
    tools/ast_fold_scan.py                # full pipeline
    tools/ast_fold_scan.py --no-build     # reuse last log
    tools/ast_fold_scan.py --report-only  # reuse cached rows file
    tools/ast_fold_scan.py --loose        # operator-multiset clustering
"""
from __future__ import annotations
import re, sys, subprocess, pathlib, hashlib, collections, argparse

ROOT       = pathlib.Path(__file__).resolve().parent.parent
LEAN_DIR   = ROOT / "lean"
PROBE      = LEAN_DIR / "E213" / "_AstFoldScanProbe.lean"
BODY_TMPL  = ROOT / "tools" / "ast_fold_scan_body.lean"
LOG_PATH   = ROOT / "tools" / "_ast_fold_scan_last.log"
ROWS_PATH  = ROOT / "tools" / "_ast_fold_scan_rows.tsv"

PROBE_HEADER = """\
/-
Ephemeral AST fold/recursor scanner.  Auto-generated by
tools/ast_fold_scan.py from tools/ast_fold_scan_body.lean.
Dumps every fold/recursor application site in `E213.*`
constants' proof terms; one row per arg, grouped by uid.
-/
import Lean
"""


def cached_modules() -> list[str]:
    base = LEAN_DIR / ".lake" / "build" / "lib" / "E213"
    if not base.exists():
        sys.exit("error: no cached .olean tree; run `lake build` first")
    mods = []
    for p in base.rglob("*.olean"):
        rel = p.relative_to(LEAN_DIR / ".lake" / "build" / "lib")
        name = ".".join(rel.with_suffix("").parts)
        if name.endswith(("_AstFoldScanProbe", "_AxiomScanProbe")):
            continue
        mods.append(name)
    return sorted(mods)


def write_probe() -> None:
    if not BODY_TMPL.exists():
        sys.exit(f"error: missing scanner body at {BODY_TMPL}")
    imports = "\n".join(f"import {m}" for m in cached_modules())
    body = BODY_TMPL.read_text()
    PROBE.write_text(PROBE_HEADER + imports + "\n\n" + body)


def build() -> str:
    r = subprocess.run(
        ["lake", "build", "E213._AstFoldScanProbe"],
        cwd=LEAN_DIR, capture_output=True, text=True,
    )
    log = r.stdout + r.stderr
    LOG_PATH.write_text(log)
    if "AST-FOLD-SCAN-END" not in log:
        sys.stderr.write(log[-4000:])
        sys.exit("error: probe did not finish; see " + str(LOG_PATH))
    return log


def extract_rows(log: str):
    rows = []
    inside = False
    for line in log.splitlines():
        if "AST-FOLD-SCAN-BEGIN" in line:
            inside = True; continue
        if "AST-FOLD-SCAN-END" in line:
            inside = False; continue
        if not inside or not line.startswith("R\t"):
            continue
        parts = line.split("\t", 5)
        if len(parts) < 6:
            continue
        _, decl, uid, tag, argIdx, skel = parts
        rows.append((decl, int(uid), tag, int(argIdx), skel))
    return rows


def canon_skel(s: str) -> str:
    s = re.sub(r'\s+', ' ', s).strip()
    return s


def skel_hash(s: str) -> str:
    return hashlib.sha1(canon_skel(s).encode()).hexdigest()[:10]


CONST_RE = re.compile(
    r'(?:E213\.)[A-Za-z_][\w.]*'
    r'|\b(?:Bool|Nat|Int|List|Eq|Ne|HAdd|HMul|HSub|HDiv|HMod'
    r'|GE|LT|LE|GT|Prod|Sigma|Sum|Option|Decidable|Or|And|Not'
    r'|Fin|Array|Char|String)\.[A-Za-z_]\w*'
)


def extract_ops(skel: str) -> tuple[str, ...]:
    ops = CONST_RE.findall(skel)
    ops = [o for o in ops if not o.split('.')[-1].startswith(('inst', 'ofNat'))]
    return tuple(sorted(set(ops)))


def report_strict(rows):
    by_uid = {}
    for r in rows:
        by_uid.setdefault(r[1], []).append(r)
    sites_by_tag = collections.Counter(rs[0][2] for rs in by_uid.values())
    print(f"# Total rows: {len(rows)}")
    print(f"# Total sites: {len(by_uid)}\n")
    print("## Sites per recursor/fold tag")
    for t, n in sites_by_tag.most_common():
        print(f"  {t:<14} {n}")
    print()
    step = [(d, u, t, s) for d, u, t, i, s in rows if i == 2]
    motifs = collections.defaultdict(list)
    for d, u, t, s in step:
        motifs[(t, skel_hash(s))].append((d, u, s))
    print("## Top step-function motifs (strict hash, argIdx=2)")
    ranked = sorted(motifs.items(), key=lambda kv: -len(kv[1]))
    for (tag, h), occs in ranked[:20]:
        skel = canon_skel(occs[0][2])
        snippet = (skel[:140] + "...") if len(skel) > 140 else skel
        decls = sorted({d for d, _, _ in occs})
        print(f"  [{tag} {h}] x{len(occs)}  ({len(decls)} distinct decls)")
        print(f"    op = {snippet}")
        for d in decls[:3]:
            print(f"    · {d}")
        if len(decls) > 3:
            print(f"    · ... +{len(decls)-3}")
        print()


def report_loose(rows):
    step = [(d, u, t, s) for d, u, t, i, s in rows if i == 2]
    buckets = collections.defaultdict(list)
    for d, u, t, s in step:
        buckets[(t, extract_ops(s))].append((d, s))
    print(f"# step-fn sites: {len(step)}")
    print(f"# loose buckets: {len(buckets)}\n")
    print("## Operator-multiset clusters (>=2 distinct decls)")
    ranked = sorted(buckets.items(),
                    key=lambda kv: -len({d for d, _ in kv[1]}))
    n_shown = 0
    for (tag, ops), occs in ranked:
        decls = sorted({d for d, _ in occs})
        if len(decls) < 2:
            continue
        n_shown += 1
        if n_shown > 30:
            break
        print(f"[{tag}] {len(decls)} decls, {len(occs)} sites")
        print(f"  ops: {{{', '.join(ops) if ops else '(empty)'}}}")
        for d in decls[:6]:
            print(f"    · {d}")
        if len(decls) > 6:
            print(f"    · ... +{len(decls)-6}")
        print()


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--no-build", action="store_true",
                    help="reuse previous build log")
    ap.add_argument("--report-only", action="store_true",
                    help="reuse cached rows file")
    ap.add_argument("--loose", action="store_true",
                    help="operator-multiset clustering instead of strict hash")
    args = ap.parse_args()
    if not args.report_only:
        if not args.no_build:
            write_probe()
            log = build()
            PROBE.unlink(missing_ok=True)
        else:
            log = LOG_PATH.read_text()
        rows = extract_rows(log)
        ROWS_PATH.write_text(
            "\n".join("\t".join(map(str, r)) for r in rows) + "\n")
    else:
        rows = []
        for line in ROWS_PATH.read_text().splitlines():
            parts = line.split("\t", 4)
            if len(parts) == 5:
                rows.append((parts[0], int(parts[1]), parts[2],
                             int(parts[3]), parts[4]))
    if args.loose:
        report_loose(rows)
    else:
        report_strict(rows)
    return 0


if __name__ == "__main__":
    sys.exit(main())
