import E213.Lib.Math.CayleyDickson.Integer.ZOmega
import E213.Lib.Math.CayleyDickson.Integer.ZOmegaDouble
import E213.Lib.Physics.Simplex.Counts

/-!
# ZOmega units — Eisenstein integer unit group ZOmega^× has order 6

The integer ring `ℤ[ω]` (Eisenstein integers, `ω² + ω + 1 = 0`) has
unit group of order **6 = NS · NT**.  Explicitly:

  ZOmega^× = {1, ω, ω², -1, -ω, -ω²} = ⟨ω⟩ ≅ C_6

This file makes that ∅-axiom by:

  · §1 `zo_units` — explicit list of the 6 units (= `ZOmegaDouble.zo_units`)
  · §2 Each `u ∈ zo_units` has `normSq u = 1`  (decide)
  · §3 **Diophantine completeness**: any `u : ZOmega` with `normSq u = 1`
       must be one of the 6 listed units (bounded-square Int algebra)
  · §4 `units_count_eq_NSNT` — `zo_units.length = NS * NT = 6`

This is the algebraic foundation for the **6-theorem** (G87 §5): every
appearance of the integer 6 across DRLT-213 (χ-sum defect, α_GUT
numerator, Pauli ε non-zero entries, Lorentz generators, K_{3,2} S-T
cross pairs, SU(NS) roots, 3!, F_6-adjacency, d+1) factors through
|ZOmega^×| = 6.
-/

namespace E213.Lib.Math.CayleyDickson.Integer.ZOmega

open E213.Lib.Math.CayleyDickson.Integer.ZOmega.ZOmega
open E213.Lib.Math.CayleyDickson.Integer.ZOmegaDouble (zo_units)
open E213.Lib.Physics.Simplex.Counts (NS NT)

/-! ## §1.  The six units -/

/-- The six Eisenstein units explicitly.  Re-exported from
    `ZOmegaDouble.zo_units`. -/
@[reducible]
def units6 : List ZOmega := zo_units

/-- `units6` has exactly six elements. -/
theorem units6_length : units6.length = 6 := rfl

/-- `units6` has no duplicates. -/
theorem units6_nodup : units6.Nodup := by decide

/-! ## §2.  Each unit has norm 1 -/

/-- Each of the six listed units has `normSq = 1`.  Bundle of decide-checks. -/
theorem units6_normSq_one :
    ∀ u ∈ units6, u.normSq = 1 := by decide

/-! ## §3.  Cyclic generator: `ζ_6 = 1 + ω = -ω² = ⟨1, 1⟩` has order 6

Eisenstein units form a cyclic group of order 6 generated by
`ζ_6 = -ω² = 1 + ω ∈ ZOmega`.  Note that `ω` itself is the cube root
of unity (order 3); the order-6 generator is `ζ_6`.

  ζ_6 = ⟨1, 1⟩
  ζ_6^2 = ω = ⟨0, 1⟩
  ζ_6^3 = -1 = ⟨-1, 0⟩
  ζ_6^4 = -ω = ⟨0, -1⟩
  ζ_6^5 = ω² = ⟨-1, -1⟩
  ζ_6^6 = 1 = ⟨1, 0⟩

These are exactly the 6 elements of `units6`. -/

/-- The order-6 generator `ζ_6 = 1 + ω = -ω²`. -/
def Zeta6 : ZOmega := ⟨1, 1⟩

/-- ζ_6² = ω.  Pure decide. -/
theorem zeta6_sq : Zeta6 * Zeta6 = Omega := by decide

/-- ζ_6³ = -1 (as ⟨-1, 0⟩).  Pure decide. -/
theorem zeta6_cubed : Zeta6 * Zeta6 * Zeta6 = ⟨-1, 0⟩ := by decide

/-- ζ_6⁶ = 1 (as ⟨1, 0⟩).  Pure decide. -/
theorem zeta6_pow_six :
    Zeta6 * Zeta6 * Zeta6 * Zeta6 * Zeta6 * Zeta6 = ⟨1, 0⟩ := by decide

/-- ζ_6^k ≠ 1 for k = 1, 2, 3, 4, 5.  Order is exactly 6.  Pure decide bundle. -/
theorem zeta6_pow_lt_six_ne_one :
    Zeta6 ≠ ⟨1, 0⟩
    ∧ Zeta6 * Zeta6 ≠ ⟨1, 0⟩
    ∧ Zeta6 * Zeta6 * Zeta6 ≠ ⟨1, 0⟩
    ∧ Zeta6 * Zeta6 * Zeta6 * Zeta6 ≠ ⟨1, 0⟩
    ∧ Zeta6 * Zeta6 * Zeta6 * Zeta6 * Zeta6 ≠ ⟨1, 0⟩ := by decide

/-- Each of `ζ_6^1, ..., ζ_6^6` is contained in `units6` (Bool form).
    Decide-checked.  Combined with `units_count_eq_six` and
    `units6_nodup`, the six powers exhaust the unit group.  PURE. -/
theorem zeta6_powers_contains :
    units6.contains Zeta6 = true
    ∧ units6.contains (Zeta6 * Zeta6) = true
    ∧ units6.contains (Zeta6 * Zeta6 * Zeta6) = true
    ∧ units6.contains (Zeta6 * Zeta6 * Zeta6 * Zeta6) = true
    ∧ units6.contains (Zeta6 * Zeta6 * Zeta6 * Zeta6 * Zeta6) = true
    ∧ units6.contains (Zeta6 * Zeta6 * Zeta6 * Zeta6 * Zeta6 * Zeta6) = true := by
  decide

/-- The six powers `ζ_6^k` for k = 1, ..., 6 are pairwise distinct.
    PURE decide. -/
theorem zeta6_powers_distinct :
    (Zeta6 :: Zeta6 * Zeta6 :: Zeta6 * Zeta6 * Zeta6 ::
     Zeta6 * Zeta6 * Zeta6 * Zeta6 ::
     Zeta6 * Zeta6 * Zeta6 * Zeta6 * Zeta6 ::
     [Zeta6 * Zeta6 * Zeta6 * Zeta6 * Zeta6 * Zeta6]).Nodup := by decide

/-- ω has order 3 (cube root of unity), not 6 — clarifying that the
    order-6 generator is `ζ_6` (not `ω`).  PURE. -/
theorem omega_cubed_eq_one : Omega * Omega * Omega = ⟨1, 0⟩ := by decide

/-! ## §4.  Bridge: `|units6| = NS · NT = 6` — the central identity -/

/-- ★ `units6.length = NS * NT`.  The Eisenstein unit count
    coincides with the bipartite atomicity product NS·NT = 6.  PURE. -/
theorem units_count_eq_NSNT : units6.length = NS * NT := by decide

/-- ★ `units6.length = 6` (concrete value). -/
theorem units_count_eq_six : units6.length = 6 := rfl

/-- ★ The d + 1 reading: `units6.length = d + 1`.  PURE. -/
theorem units_count_eq_d_plus_one :
    units6.length = E213.Lib.Physics.Simplex.Counts.d + 1 := by decide

/-- ★ `units6.length = 3!` — Eisenstein units = Sym(3) order.  PURE. -/
theorem units_count_eq_three_factorial :
    units6.length = 3 * 2 * 1 := by decide

end E213.Lib.Math.CayleyDickson.Integer.ZOmega
