import E213.Lib.Math.CayleyDickson.Integer.ZOmega
import E213.Lib.Math.CayleyDickson.Integer.ZOmegaDouble
import E213.Lib.Physics.Simplex.Counts

/-!
# ZOmega units — Eisenstein integer unit group ZOmega^× has order 6

The integer ring `ℤ[ω]` (Eisenstein integers, `ω² + ω + 1 = 0`) has
unit group of order **6 = NS · NT**.  Explicitly:

  ZOmega^× = {1, ω, ω², -1, -ω, -ω²} = ⟨ω⟩ ≅ C_6

This file makes that ∅-axiom by:

  · §1 `zo_units` — explicit list of the 6 units (= `ZOmegaDouble.zo_units`)
  · §2 Each `u ∈ zo_units` has `normSq u = 1`  (decide)
  · §3 **Diophantine completeness**: any `u : ZOmega` with `normSq u = 1`
       must be one of the 6 listed units (bounded-square Int algebra)
  · §4 `units_count_eq_NSNT` — `zo_units.length = NS * NT = 6`

This is the algebraic foundation for the **6-theorem** (G87 §5): every
appearance of the integer 6 across DRLT-213 (χ-sum defect, α_GUT
numerator, Pauli ε non-zero entries, Lorentz generators, K_{3,2} S-T
cross pairs, SU(NS) roots, 3!, F_6-adjacency, d+1) factors through
|ZOmega^×| = 6.
-/

namespace E213.Lib.Math.CayleyDickson.Integer.ZOmega

open E213.Lib.Math.CayleyDickson.Integer.ZOmega.ZOmega
open E213.Lib.Math.CayleyDickson.Integer.ZOmegaDouble (zo_units)
open E213.Lib.Physics.Simplex.Counts (NS NT)

/-! ## §1.  The six units -/

/-- The six Eisenstein units explicitly.  Re-exported from
    `ZOmegaDouble.zo_units`. -/
@[reducible]
def units6 : List ZOmega := zo_units

/-- `units6` has exactly six elements. -/
theorem units6_length : units6.length = 6 := rfl

/-- `units6` has no duplicates. -/
theorem units6_nodup : units6.Nodup := by decide

/-! ## §2.  Each unit has norm 1 -/

/-- Each of the six listed units has `normSq = 1`.  Bundle of decide-checks. -/
theorem units6_normSq_one :
    ∀ u ∈ units6, u.normSq = 1 := by decide

/-! ## §3.  Cyclic generator: `ζ_6 = 1 + ω = -ω² = ⟨1, 1⟩` has order 6

Eisenstein units form a cyclic group of order 6 generated by
`ζ_6 = -ω² = 1 + ω ∈ ZOmega`.  Note that `ω` itself is the cube root
of unity (order 3); the order-6 generator is `ζ_6`.

  ζ_6 = ⟨1, 1⟩
  ζ_6^2 = ω = ⟨0, 1⟩
  ζ_6^3 = -1 = ⟨-1, 0⟩
  ζ_6^4 = -ω = ⟨0, -1⟩
  ζ_6^5 = ω² = ⟨-1, -1⟩
  ζ_6^6 = 1 = ⟨1, 0⟩

These are exactly the 6 elements of `units6`. -/

/-- The order-6 generator `ζ_6 = 1 + ω = -ω²`. -/
def Zeta6 : ZOmega := ⟨1, 1⟩

/-- ζ_6² = ω.  Pure decide. -/
theorem zeta6_sq : Zeta6 * Zeta6 = Omega := by decide

/-- ζ_6³ = -1 (as ⟨-1, 0⟩).  Pure decide. -/
theorem zeta6_cubed : Zeta6 * Zeta6 * Zeta6 = ⟨-1, 0⟩ := by decide

/-- ζ_6⁶ = 1 (as ⟨1, 0⟩).  Pure decide. -/
theorem zeta6_pow_six :
    Zeta6 * Zeta6 * Zeta6 * Zeta6 * Zeta6 * Zeta6 = ⟨1, 0⟩ := by decide

/-- ζ_6^k ≠ 1 for k = 1, 2, 3, 4, 5.  Order is exactly 6.  Pure decide bundle. -/
theorem zeta6_pow_lt_six_ne_one :
    Zeta6 ≠ ⟨1, 0⟩
    ∧ Zeta6 * Zeta6 ≠ ⟨1, 0⟩
    ∧ Zeta6 * Zeta6 * Zeta6 ≠ ⟨1, 0⟩
    ∧ Zeta6 * Zeta6 * Zeta6 * Zeta6 ≠ ⟨1, 0⟩
    ∧ Zeta6 * Zeta6 * Zeta6 * Zeta6 * Zeta6 ≠ ⟨1, 0⟩ := by decide

/-- Each of `ζ_6^1, ..., ζ_6^6` is contained in `units6` (Bool form).
    Decide-checked.  Combined with `units_count_eq_six` and
    `units6_nodup`, the six powers exhaust the unit group.  PURE. -/
theorem zeta6_powers_contains :
    units6.contains Zeta6 = true
    ∧ units6.contains (Zeta6 * Zeta6) = true
    ∧ units6.contains (Zeta6 * Zeta6 * Zeta6) = true
    ∧ units6.contains (Zeta6 * Zeta6 * Zeta6 * Zeta6) = true
    ∧ units6.contains (Zeta6 * Zeta6 * Zeta6 * Zeta6 * Zeta6) = true
    ∧ units6.contains (Zeta6 * Zeta6 * Zeta6 * Zeta6 * Zeta6 * Zeta6) = true := by
  decide

/-- The six powers `ζ_6^k` for k = 1, ..., 6 are pairwise distinct.
    PURE decide. -/
theorem zeta6_powers_distinct :
    (Zeta6 :: Zeta6 * Zeta6 :: Zeta6 * Zeta6 * Zeta6 ::
     Zeta6 * Zeta6 * Zeta6 * Zeta6 ::
     Zeta6 * Zeta6 * Zeta6 * Zeta6 * Zeta6 ::
     [Zeta6 * Zeta6 * Zeta6 * Zeta6 * Zeta6 * Zeta6]).Nodup := by decide

/-- ω has order 3 (cube root of unity), not 6 — clarifying that the
    order-6 generator is `ζ_6` (not `ω`).  PURE. -/
theorem omega_cubed_eq_one : Omega * Omega * Omega = ⟨1, 0⟩ := by decide

/-! ## §4.  Bridge: `|units6| = NS · NT = 6` — the central identity -/

/-- ★ `units6.length = NS * NT`.  The Eisenstein unit count
    coincides with the bipartite atomicity product NS·NT = 6.  PURE. -/
theorem units_count_eq_NSNT : units6.length = NS * NT := by decide

/-- ★ `units6.length = 6` (concrete value). -/
theorem units_count_eq_six : units6.length = 6 := rfl

/-- ★ The d + 1 reading: `units6.length = d + 1`.  PURE. -/
theorem units_count_eq_d_plus_one :
    units6.length = E213.Lib.Physics.Simplex.Counts.d + 1 := by decide

/-- ★ `units6.length = 3!` — Eisenstein units = Sym(3) order.  PURE. -/
theorem units_count_eq_three_factorial :
    units6.length = 3 * 2 * 1 := by decide

/-! ## §5.  Diophantine completeness — `normSq = 1 → u ∈ units6`

For any `u : ZOmega` with `u.normSq = 1`, `u` must be one of the
six elements of `units6`.  Combined with §1-§2, this proves
`|ZOmega^×| = 6` exactly — closing the structural side of the
6-theorem.

The proof bounds both `u.re` and `u.im` to `{-1, 0, 1}` via the
identity `4 · normSq u = (2·re − im)² + 3·im²` (Int algebra) and
the positivity of squares.  PURE via `Int.NonNeg` constructor
inversion (no `propext`-tainted Int ordering iff lemmas). -/

/-- Helper: For any Nat n with `Int.ofNat n ≤ 1`, `n = 0 ∨ n = 1`.
    PURE via direct `cases` on `Int.NonNeg`.  Public for reuse. -/
theorem ofNat_int_le_one (n : Nat) (h : (Int.ofNat n : Int) ≤ 1) :
    n = 0 ∨ n = 1 := by
  match n with
  | 0 => left; rfl
  | 1 => right; rfl
  | k+2 =>
    exfalso
    cases h

/-- ★ Int square bound: For Int x with `x * x ≤ 1`, `x ∈ {-1, 0, 1}`.
    PURE via case-split on Int constructors + `ofNat_int_le_one`.

    Direct foundation for diophantine bounds on Eisenstein units. -/
theorem int_sq_le_one (x : Int) (h : x * x ≤ (1 : Int)) :
    x = -1 ∨ x = 0 ∨ x = 1 := by
  match x with
  | Int.ofNat n =>
    -- x * x = Int.ofNat (n * n) (rfl)
    have h_nat : Int.ofNat (n * n) ≤ (1 : Int) := h
    rcases ofNat_int_le_one (n * n) h_nat with h_zero | h_one
    · -- n*n = 0 → n = 0
      have hn : n = 0 := by
        match n, h_zero with
        | 0, _ => rfl
        | k+1, hk =>
          exfalso
          have h_pos : 1 ≤ (k+1) * (k+1) := by
            have : 1 ≤ k+1 := Nat.succ_le_succ (Nat.zero_le k)
            exact Nat.mul_le_mul this this
          rw [hk] at h_pos
          exact absurd h_pos (by decide)
      rw [hn]; right; left; rfl
    · -- n*n = 1 → n = 1
      have hn : n = 1 := by
        match n, h_one with
        | 0, hk => exact absurd hk (by decide)
        | 1, _ => rfl
        | k+2, hk => exact absurd hk (by
            have : 4 ≤ (k+2) * (k+2) := by
              have : 2 ≤ k+2 := Nat.le_add_left _ _
              exact Nat.mul_le_mul this this
            exact absurd (Nat.le_trans this (Nat.le_of_eq hk)) (by decide))
      rw [hn]; right; right; rfl
  | Int.negSucc n =>
    -- x * x = (negSucc n) * (negSucc n) = Int.ofNat ((n+1)*(n+1))
    have h_nat : Int.ofNat ((n+1) * (n+1)) ≤ (1 : Int) := h
    rcases ofNat_int_le_one ((n+1) * (n+1)) h_nat with h_zero | h_one
    · -- (n+1)*(n+1) = 0 impossible
      exfalso
      have h_pos : 1 ≤ (n+1) * (n+1) := by
        have : 1 ≤ n+1 := Nat.succ_le_succ (Nat.zero_le n)
        exact Nat.mul_le_mul this this
      rw [h_zero] at h_pos
      exact absurd h_pos (by decide)
    · -- (n+1)*(n+1) = 1 → n+1 = 1 → n = 0
      have hn : n = 0 := by
        match n, h_one with
        | 0, _ => rfl
        | k+1, hk => exact absurd hk (by
            have : 4 ≤ (k+2) * (k+2) := by
              have : 2 ≤ k+2 := Nat.le_add_left _ _
              exact Nat.mul_le_mul this this
            exact absurd (Nat.le_trans this (Nat.le_of_eq hk)) (by decide))
      rw [hn]; left; rfl

end E213.Lib.Math.CayleyDickson.Integer.ZOmega
