import E213.Meta.SelfRecognising
import E213.Math.CayleyDickson.ZOmega
import E213.Math.CayleyDickson.ZOmegaDomain
import E213.Meta.Tactic.DeriveConjugationCodomain

/-!
# Research: `ZOmega` (Eisenstein integers ℤ[ω]) as `ConjugationCodomain`

Third confirmed counterexample to Paper 1's claim that the
historical R1–R4 axiom set forces ℂ.  ℤ[ω] is the ring of
Eisenstein integers, where ω is a primitive cube root of unity.
Its norm `a² - ab + b²` has a cross-term, demonstrating that
the infrastructure handles more than diagonal `a² + D·b²`
norms.

Generated by the `derive_conjugation_codomain` elab using bases
`Omega = ω` and `Omega2 = ω²`.
-/

open E213.Tactic E213.Research

derive_conjugation_codomain ZOmega with_bases Omega Omega2
