import E213.Lib.Math.DyadicFSM.ForwardEventual
import E213.Meta.Tactic.Nat213

import E213.Lib.Math.DyadicFSM.ForwardPeriodicity
import E213.Lib.Math.DyadicFSM.Signature
/-!
# BitFSM — finite-state-machine generated bit streams

A BitFSM with `n` states generates a Bool stream via state
transitions: `run k = step^k init`, `bits k = out (run k)`.

By pigeonhole, the run is eventually periodic with period ≤ n,
hence the bits are eventually periodic, hence (by Tier 0 forward
closure) the K_{3,2}^{(2)} signature is also eventually periodic.

Implication: Tier 0 ∪ Tier 1 ⊂ {bit streams generable by some
BitFSM}.  Tier 2 (e, π, etc.) is conjecturally OUTSIDE this class.
-/

namespace E213.Lib.Math.DyadicFSM.BitFSM

open E213.Lib.Math.DyadicFSM.ForwardPeriodicity
  (pigeonhole_collision collisionTest collTest_imp_val_eq)
open E213.Lib.Math.DyadicFSM.Signature (signature nextVertex)
open E213.Lib.Math.DyadicFSM.ForwardEventual (signature_eventually_periodic_of_eventually_periodic_bits)

/-- A BitFSM with `n` states. -/
structure BitFSM (n : Nat) where
  init : Fin n
  step : Fin n → Fin n
  out  : Fin n → Bool

/-- Run the FSM for k steps. -/
def BitFSM.run {n : Nat} (m : BitFSM n) : Nat → Fin n
  | 0 => m.init
  | k + 1 => m.step (m.run k)

/-- Bit stream generated by the FSM. -/
def BitFSM.bits {n : Nat} (m : BitFSM n) (k : Nat) : Bool :=
  m.out (m.run k)

/-- ★ FSM run collision via pigeonhole.  STRICT ∅-AXIOM. -/
theorem fsm_run_collision {n : Nat} (m : BitFSM n) :
    ∃ i, i ≤ n ∧ ∃ j, j ≤ n ∧ i < j ∧ m.run i = m.run j := by
  have hlt : n < n + 1 := Nat.lt_succ_self _
  let g : Fin (n+1) → Fin n := fun k => m.run k.val
  obtain ⟨i, hi, j, hj, hij, hcoll⟩ := pigeonhole_collision hlt g
  refine ⟨i, Nat.lt_succ_iff.mp hi, j, Nat.lt_succ_iff.mp hj, hij, ?_⟩
  exact Fin.ext (collTest_imp_val_eq g i j hi hj hcoll)

/-- ∅-axiom replacement for `Nat.sub_pos_of_lt` (which leaks propext). -/
private theorem sub_pos_of_lt_213 : ∀ {a b : Nat}, a < b → 0 < b - a
  | 0, _, h => by rw [Nat.sub_zero]; exact h
  | _+1, 0, h => absurd h (Nat.not_succ_le_zero _)
  | _+1, _+1, h => by
    rw [Nat.succ_sub_succ_eq_sub]
    exact sub_pos_of_lt_213 (Nat.lt_of_succ_lt_succ h)

/-- ★★★ BitFSM run is eventually periodic.  STRICT ∅-AXIOM. -/
theorem fsm_run_eventually_periodic {n : Nat} (m : BitFSM n) :
    ∃ N P, 0 < P ∧ ∀ k, k ≥ N → m.run (k + P) = m.run k := by
  obtain ⟨i, _, j, _, hij, heq⟩ := fsm_run_collision m
  refine ⟨i, j - i, sub_pos_of_lt_213 hij, ?_⟩
  intro k hk
  obtain ⟨d, rfl⟩ : ∃ d, k = i + d :=
    ⟨k - i, (E213.Tactic.Nat213.add_sub_of_le hk).symm⟩
  clear hk
  have hij_eq : i + (j - i) = j :=
    E213.Tactic.Nat213.add_sub_of_le (Nat.le_of_lt hij)
  induction d with
  | zero =>
    show m.run (i + 0 + (j - i)) = m.run (i + 0)
    rw [Nat.add_zero, hij_eq]
    exact heq.symm
  | succ d' ih =>
    have h1 : i + (d' + 1) + (j - i) = (i + d' + (j - i)) + 1 :=
      Nat.succ_add (i + d') (j - i)
    have h2 : i + (d' + 1) = (i + d') + 1 := rfl
    rw [h1, h2]
    show m.step (m.run (i + d' + (j - i))) = m.step (m.run (i + d'))
    rw [ih]

/-- ★★★★★ BitFSM bit stream is eventually periodic. -/
theorem fsm_bits_eventually_periodic {n : Nat} (m : BitFSM n) :
    ∃ N P, 0 < P ∧ ∀ k, k ≥ N → m.bits (k + P) = m.bits k := by
  obtain ⟨N, P, hP, h⟩ := fsm_run_eventually_periodic m
  refine ⟨N, P, hP, ?_⟩
  intro k hk
  show m.out (m.run (k + P)) = m.out (m.run k)
  rw [h k hk]

/-- ★★★★★★ BitFSM-generated signature is eventually periodic. -/
theorem fsm_signature_eventually_periodic {n : Nat} (m : BitFSM n) :
    ∃ N P, 0 < P ∧ ∀ k, k ≥ N →
      signature m.bits (k + P) = signature m.bits k := by
  obtain ⟨N₀, P, hP, hbits⟩ := fsm_bits_eventually_periodic m
  exact signature_eventually_periodic_of_eventually_periodic_bits
    m.bits P N₀ hP (fun n hn => hbits n hn)

end E213.Lib.Math.DyadicFSM.BitFSM
