import E213.Lens.Number.Nat213.LegendreReadout
import E213.Lens.Number.Nat213.MulOrderReadout
import E213.Lib.Math.NumberTheory.ModArith.DiscreteLogParity

/-!
# Lens.Number.Nat213.DiscreteLogReadout — the quadratic character is the discrete-log parity (∅-axiom)

The **descent leg**, leg-2 — the capstone tying the order corpus (`MulOrderReadout`,
`PrimitiveRootReadout`) to the quadratic-residue corpus (`LegendreReadout`): the **quadratic character
is the parity of the discrete logarithm**.

Over a prime `p`, the unit group is cyclic — generated by a primitive root `g` (full order `p − 1`,
`PrimitiveRootReadout.exists_primitive_root`).  So every unit `a` is a power `a ≡ g^k`, and `a` is a
quadratic residue **iff the exponent `k` is even**: the squares are exactly the even positions of the
orbit `⟨g⟩`.  No residue/non-residue predicate is imported from outside the units — the character is
read off the orbit position, internally.

`qr_iff_even_dlog` transports the native fully-internal form (`qr_iff_even_dlog_exists`): the
primitive root `g` is lifted to a carrier (`toNat_surj`), the relation `a = g^k % p` becomes the
carrier congruence `a ≡ g^k` (`modeq_of_toNat_mod` + `mod_mod`), and `QR p a` is matched to the
native bounded existential through `LegendreReadout.QR_iff_native`.  ∅-axiom throughout.
-/

namespace E213.Lens.Number.Nat213.DiscreteLogReadout

open E213.Lens.Number.Nat213.Peano (Nat213)
open E213.Lens.Number.Nat213.Peano.Nat213 (powNat toNat toNat_ge_one)
open E213.Lens.Number.Nat213.ToNatReadout (toNat_surj toNat_powNat)
open E213.Lens.Number.Nat213.Congruence (ModEq)
open E213.Lens.Number.Nat213.ModArithReadout (modeq_of_toNat_mod)
open E213.Lens.Number.Nat213.LegendreReadout (QR QR_iff_native)
open E213.Lens.Number.Nat213.MulOrderReadout (mulOrd)
open E213.Lib.Math.NumberTheory.ModArith.MulOrder (ordModP)
open E213.Lib.Math.NumberTheory.ModArith.DiscreteLogParity (qr_iff_even_dlog_exists)
open E213.Meta.Nat.AddMod213 (mod_mod)
open E213.Tactic.Pow213 (le_of_dvd_pos)

/-- ★★★★★ **The quadratic character is the discrete-log parity over `Nat213`** — for a prime `p`
    (`2m = p − 1`) and any unit `a < p`, there is a primitive root `g` (full order `mulOrd g p =
    p − 1`) and a discrete log `k` with `a ≡ g^k (mod p)`, such that **`a` is a quadratic residue iff
    `k` is even**: `QR p a ⟺ 2 ∣ k`.  The squares are the even positions of the cyclic orbit `⟨g⟩` —
    the character read internally off the orbit, no external residue predicate.  Native
    `qr_iff_even_dlog_exists` inherited: `g` lifted by `toNat_surj`, `a = g^k % p` welded to the
    carrier congruence (`mod_mod`), `QR p a` matched through `QR_iff_native`.  ∅-axiom. -/
theorem qr_iff_even_dlog {p a : Nat213} (m : Nat) (hp : 1 < p.toNat)
    (hpr : ∀ d, d ∣ p.toNat → d = 1 ∨ d = p.toNat) (h2m : 2 * m = p.toNat - 1) (hm1 : 1 ≤ m)
    (halt : a.toNat < p.toNat) :
    ∃ (g : Nat213) (k : Nat),
      mulOrd g p = p.toNat - 1 ∧ ModEq p a (powNat g k) ∧ (QR p a ↔ 2 ∣ k) := by
  obtain ⟨g, k, ⟨hg1, _, hord⟩, hak, hiff⟩ :=
    qr_iff_even_dlog_exists p.toNat m a.toNat hp hpr h2m hm1 (toNat_ge_one a) halt
  obtain ⟨g', hg'⟩ := toNat_surj g hg1
  refine ⟨g', k, ?_, ?_, ?_⟩
  · show ordModP g'.toNat p.toNat = p.toNat - 1
    rw [hg']; exact hord
  · apply modeq_of_toNat_mod
    rw [toNat_powNat, hg', hak, mod_mod]
  · have hua : ¬ p.toNat ∣ a.toNat :=
      fun h => absurd (le_of_dvd_pos p.toNat a.toNat (toNat_ge_one a) h) (Nat.not_le.mpr halt)
    have b := QR_iff_native hp hua
    rw [Nat.mod_eq_of_lt halt] at b
    exact b.trans hiff

end E213.Lens.Number.Nat213.DiscreteLogReadout
