import E213.Lens.Number.Nat213.Raw
import E213.Lens.LensCore
import E213.Lens.Initiality

/-!
# Lens.Number.Nat213.Generation — ℕ₊ is the leaves-Lens reading of iterated distinguishing (∅-axiom)

The **descent leg**'s generation headline (`research-notes/frontiers/the_descent_leg.md`): the
positive naturals are not posited and not merely an "ergonomic parallel" to a Lens form — they are
*generated by the act of distinguishing* and *read off by the canonical leaves-Lens*:

  - the start is the atom: `one := Raw.a`;
  - the successor **is** the distinguishing operation — `succ n := slashOrSelf n Raw.b`
    (`succ_is_distinguishing`), wrapping `n` by a `slash` against the other atom `b`;
  - the count **is** the canonical Lens — `value = Lens.leaves.view` (`value_eq_leaves`), the
    `⟨1,1,(·+·)⟩` catamorphism, *not* a bespoke projection (this turns `Raw.lean`'s comment into a
    theorem).

So `Lens.leaves.view (numeral n) = n + 1` (`leaves_numeral`): the positive natural `n+1` is exactly
the canonical leaves-Lens reading of the Raw built by `n`-fold `slash`-against-`b` from the atom `a`.
**ℕ₊ = the count-Lens reading of iterated self-distinguishing** — generation, not parallel.  This is
the corrected thesis at the foundation of arithmetic: number is the distinguishing's unfolding, read
by a Lens.  ∅-axiom.
-/

namespace E213.Lens.Number.Nat213.Generation

open E213.Theory (Raw)
open E213.Theory.Raw.Endomorphic (slashOrSelf)
open E213.Lens.Number.Nat213.Raw (one succ numeral value value_numeral)
open E213.Lens.Initiality

/-- The local leaf-count `value` **is** the canonical leaves-Lens reading
    `Lens.leaves.view` (`Lens.leaves = ⟨1,1,(·+·)⟩`, the catamorphism).  `Raw.lean`'s comment as a
    theorem: the count is the canonical Lens, not a bespoke projection. -/
theorem value_eq_leaves (r : Raw) : value r = Lens.leaves.view r := rfl

/-- The successor on the Raw chain **is** the act of distinguishing: `succ n` wraps `n` by a `slash`
    against the other atom `b`.  Number's `+1` is a distinguishing event. -/
theorem succ_is_distinguishing (n : Raw) : succ n = slashOrSelf n Raw.b := rfl

/-- The canonical leaves-Lens reading of the `n`-fold iterated distinguishing is `n + 1`. -/
theorem leaves_numeral (n : Nat) : Lens.leaves.view (numeral n) = n + 1 := by
  rw [← value_eq_leaves]; exact value_numeral n

/-- ★★★ **The count is the *forced* reading** — initiality (`Lens.view_unique`) at the arithmetic
    level.  *Any* `g : Raw → Nat` that interprets each atom as `1` and a distinguishing (`slash`) as
    addition is **identically** the leaf-count `value`.  So ℕ-counting is not one choice among
    readings of the distinguishing — fixing "atom ↦ 1, distinguishing ↦ +" *forces* the whole
    reading (uniqueness with teeth).  The "forced unfolding" of the corrected thesis, made literal
    for arithmetic. -/
theorem count_reading_forced (g : Raw → Nat)
    (ha : g Raw.a = 1) (hb : g Raw.b = 1)
    (hslash : ∀ (x y : Raw) (h : x ≠ y), g (Raw.slash x y h) = g x + g y) :
    ∀ r : Raw, g r = value r := by
  intro r
  rw [value_eq_leaves]
  exact Lens.view_unique Lens.leaves (fun u v => Nat.add_comm u v) g ha hb hslash r

/-- ★★★ **Generation capstone.**  The positive natural `n + 1` is the canonical leaves-Lens reading
    (`Lens.leaves.view`) of the Raw obtained by `n`-fold `slash`-against-`b` (the distinguishing op,
    `succ_is_distinguishing`) from the atom `one = Raw.a`.  ℕ₊ is the count-Lens reading of iterated
    self-distinguishing — the descent leg's leg-1 headline, routed through the *canonical* Lens. -/
theorem generation_capstone (n : Nat) :
    succ (numeral n) = slashOrSelf (numeral n) Raw.b
    ∧ Lens.leaves.view (numeral n) = n + 1 :=
  ⟨rfl, leaves_numeral n⟩

end E213.Lens.Number.Nat213.Generation
