import E213.Meta.SelfRecognising
import E213.Research.CayleyDickson.ZOmega
import E213.Research.CayleyDickson.ZOmegaDomain
import E213.Tactic.DeriveR4Codomain

/-!
# Research: `ZOmega` (Eisenstein integers ℤ[ω]) as `R4Codomain`

Third confirmed counterexample to Paper 1's claim
"R1–R4 force ℂ".  ℤ[ω] is the ring of Eisenstein integers,
where ω is a primitive cube root of unity.  Its norm
`a² - ab + b²` has a cross-term, demonstrating that the
infrastructure handles more than diagonal `a² + D·b²` norms.

Generated by the `derive_r4_codomain` elab using bases
`Omega = ω` and `Omega2 = ω²`.
-/

open E213.Tactic E213.Research

derive_r4_codomain ZOmega with_bases Omega Omega2
