import E213.Lib.Math.NumberSystems.Real213.Completability.IntensionalCompletability

/-!
# ScalingOrbit — the rescaling orbit of a presentation, and its reduced base

`IntensionalCompletability` separated the presentation-relative *test* (`CrossDetSmall`)
from the presentation-invariant *truth* (the cut's completion).  This file gives the
**rescaling orbit** its structure: the presentations `(c·a, c·d)`, `c ≥ 1`, of one cut
form a monoid-action orbit, the cut is its complete invariant, the free-class membership
is antitone along it, and the orbit has a unique **reduced base** (`Reduced`: no common
scale factor beyond `1`).

This is the canonical-coordinate half of the rung-floor program: within a rescaling
orbit, the reduced base is the unique rung-minimal presentation — the canonical place to
read the cut's rung.  (Scope, honest: this covers the *rescaling* sub-family of
presentations, generated by a common constant factor; the rung floor over *all*
presentations of a cut — different convergent algorithms — is a strictly larger question
left open.)

  * `scaleBy_one` / `scaleBy_comp` — `scaleBy` is a monoid action of `(Nat, ·, 1)`.
  * `scaleBy_preserves_cut` — the cut is the orbit invariant (`rcut` unchanged).
  * `orbit_free_implies_base_free` — `CrossDetSmall` is antitone along the action: a free
    orbit member forces the base free (so the base is the canonical free-witness).
  * `reduced_scaling_trivial` — a `Reduced` base related to another presentation by a
    scaling has scale `1`: the reduced base is unique in its orbit.
  * `scaling_orbit_structure` bundles the four.

All zero-axiom.
-/

namespace E213.Lib.Math.NumberSystems.Real213.ScalingOrbit

open E213.Lib.Math.NumberSystems.Real213.CrossDetOvertake (CrossDetSmall)
open E213.Lib.Math.NumberSystems.Real213.RateModulus (rcut)
open E213.Lib.Math.NumberSystems.Real213.PresentationDependence (rcut_rescale)
open E213.Lib.Math.NumberSystems.Real213.IntensionalCompletability (crossDetSmall_rescale_antitone)
open E213.Tactic.NatHelper (mul_assoc)

/-! ## §1 — the rescaling action -/

/-- The rescaling action: multiply every term of a presentation by the constant `c`. -/
def scaleBy (c : Nat) (a : Nat → Nat) : Nat → Nat := fun i => c * a i

/-- Acting by `1` is the identity (pointwise). -/
theorem scaleBy_one (a : Nat → Nat) (i : Nat) : scaleBy 1 a i = a i := Nat.one_mul (a i)

/-- The action composes: `scaleBy c (scaleBy c' a) = scaleBy (c·c') a` (pointwise).  So
    `scaleBy` is a monoid action of `(Nat, ·, 1)` on presentations. -/
theorem scaleBy_comp (c c' : Nat) (a : Nat → Nat) (i : Nat) :
    scaleBy c (scaleBy c' a) i = scaleBy (c * c') a i :=
  (mul_assoc c c' (a i)).symm

/-! ## §2 — the cut is the orbit invariant -/

/-- ★ **The cut is the complete orbit invariant.**  Every member `(c·a, c·d)` of a
    rescaling orbit defines the *same* cut (`c ≥ 1`): the orbit sits inside one real. -/
theorem scaleBy_preserves_cut (c : Nat) (hc : 1 ≤ c) (a d : Nat → Nat) (i m k : Nat) :
    rcut (scaleBy c a) (scaleBy c d) i m k = rcut a d i m k :=
  rcut_rescale c hc a d i m k

/-! ## §3 — free-class membership is antitone along the action -/

/-- ★★ **The free class is antitone along the action.**  If a scaled member of the orbit
    (cross-determinant `c²·W` — `scaleBy (c·c) W` — against denominator `scaleBy c d`)
    satisfies `CrossDetSmall`, so does the base.  So the base is the canonical free-class
    witness: a real that fails the bridge at its base cannot be rescued by scaling up. -/
theorem orbit_free_implies_base_free (W d : Nat → Nat) (c : Nat) (hc : 1 ≤ c)
    (h : CrossDetSmall (scaleBy (c * c) W) (scaleBy c d)) : CrossDetSmall W d :=
  crossDetSmall_rescale_antitone W d c hc h

/-! ## §4 — the reduced base is unique in its orbit -/

/-- A presentation is **reduced** when it carries no common scale factor beyond `1`: it is
    not a non-trivial rescaling of any presentation. -/
abbrev Reduced (a d : Nat → Nat) : Prop :=
  ∀ (c : Nat) (a' d' : Nat → Nat), 1 ≤ c → (∀ i, a i = c * a' i) → (∀ i, d i = c * d' i)
    → c = 1

/-- ★★ **The reduced base is unique in its orbit.**  If a `Reduced` presentation `(a, d)`
    is a `c`-scaling of `(a', d')`, then `c = 1` and the two coincide pointwise — the
    reduced member of a rescaling orbit is unique (the canonical representative for the
    cut's rung). -/
theorem reduced_scaling_trivial (a d a' d' : Nat → Nat) (c : Nat) (hc : 1 ≤ c)
    (hred : Reduced a d) (ha : ∀ i, a i = c * a' i) (hd : ∀ i, d i = c * d' i) (i : Nat) :
    a i = a' i ∧ d i = d' i := by
  have hc1 : c = 1 := hred c a' d' hc ha hd
  refine ⟨?_, ?_⟩
  · rw [ha i, hc1, Nat.one_mul]
  · rw [hd i, hc1, Nat.one_mul]

/-! ## §5 — the orbit structure, bundled -/

/-- ★★★ **The rescaling-orbit structure.**  Within a rescaling orbit:

    1. `scaleBy` is a monoid action (`scaleBy_one`, `scaleBy_comp`);
    2. the cut is the complete invariant — every member is the same real;
    3. `CrossDetSmall` is antitone along the action (the base is the canonical
       free-witness);
    4. the `Reduced` base is unique.

    So the rescaling sub-family of a cut's presentations is a monoid orbit inside one
    real, with the free-class test antitone and a unique reduced representative — the
    canonical point at which to read the cut's rung. -/
theorem scaling_orbit_structure :
    (∀ a i, scaleBy 1 a i = a i)
    ∧ (∀ c c' a i, scaleBy c (scaleBy c' a) i = scaleBy (c * c') a i)
    ∧ (∀ c, 1 ≤ c → ∀ a d i m k,
        rcut (scaleBy c a) (scaleBy c d) i m k = rcut a d i m k)
    ∧ (∀ W d c, 1 ≤ c →
        CrossDetSmall (scaleBy (c * c) W) (scaleBy c d) → CrossDetSmall W d) :=
  ⟨scaleBy_one, scaleBy_comp,
   fun c hc a d i m k => scaleBy_preserves_cut c hc a d i m k,
   fun W d c hc h => orbit_free_implies_base_free W d c hc h⟩

end E213.Lib.Math.NumberSystems.Real213.ScalingOrbit
